
=== Order Assy Service

ifeval::["{backend}" != "pdf"]

[inline-toc]#<<order-assy-add-component,addComponent()>>#
[inline-toc]#<<order-assy-find-component-assembly-state,findComponentAssemblyState()>>#
[inline-toc]#<<order-assy-order-post-release,postRelease()>>#
[inline-toc]#<<order-assy-remove-component,removeComponent()>>#
[inline-toc]#<<order-assy-undo-component-remove,undoComponentRemove()>>#

endif::[]

The link:reference.html#order-assy-service[Order Assembly Service^] icon:share-square-o[role="link-blue"]
provides methods to process assembly information on an order or LSN.
This service provides the ability to assemble components and adds assembly
extensions to the mes core Order logic.
This includes copying component details to the order during release of the order.
See link:{mes-core-path}/guide.html#services[MES Core Services^] icon:share-square-o[role="link-blue"]
for details on the core service.

The service methods are exposed using the
link:groovydoc/org/simplemes/mes/assy/demand/OrderAssyController.html[OrderAssyController^]
icon:share-square-o[role="link-blue"].
These controller methods generally match the inputs and outputs of the services.  The only
difference is the values are passed as JSON strings.


[[order-assy-add-component,OrderAssyService.addComponent()]]
==== addComponent()

The link:reference.html#order-assy-add-component[addComponent()^] icon:share-square-o[role="link-blue"]
method adds a component to the given order/LSN.  It supports
link:{eframe-path}/guide.html#flex-types[Flex Types^] icon:share-square-o[role="link-blue"]
to define customer-specific input fields for the assembled components.
The component can be added for the entire order or just for a single LSN.

[[order-assy-add-component-example]]
==== JSON Example - addComponent()

To add a component using JSON via the controller, use this request _POST_ request:

*uri:* `/orderAssy/addComponent`

The JSON content passed to the controller contain the component to add:

[source,json]
.JSON Add Component
----
{
  "addOrderAssembledComponentRequest": {
    "order": "M1001",
    "lsn": {
      "lsn": "SN2037"
    },
    "component": "CPU",                         // <.>
    "location": "BIN 47",
    "workCenter": "CELL_17",
    "qty": 47.2,
    "assemblyData": "VENDOR",                   // <.>
    "assemblyData_LOT": "ACME-101"              // <.>
  }
}
----
<.> The component is a reference to a product domain record.
<.> `assemblyData` is a Flex Type.  This must come before the field values.
<.> The LOT assembly flex type supports a single data field 'LOT'.  The JSON field name
    needs to be formatted like this.


[[order-assy-find-component-assembly-state,OrderAssyService.findComponentAssemblyState()]]
==== findComponentAssemblyState()

The link:reference.html#order-assy-find-component-assembly-state[findComponentAssemblyState()^]
icon:share-square-o[role="link-blue"]
method finds the state of all the components needed for the given order/LSN.
If LSN is given, then the logic will attempt to reconcile order-based components
with this single LSN.  This will cause problems when mixing order-based and LSN-based
assembly for a given component. Typically, this will report a fully assembled component for LSN
when it is uncertain.

[[order-assy-order-post-release,postRelease()]]
==== postRelease()

This method is called after an order is released by the mes-core module.
This addition method will copy any ProductComponent (BOM) records to the order.

NOTE: Do not call this directly.  Call the mes-core OrderService.release() method instead.


[[order-assy-remove-component,OrderAssyService.removeComponent()]]
==== removeComponent()

The link:reference.html#order-assy-remove-component[removeComponent()^] icon:share-square-o[role="link-blue"]
method removes a specific component from the given order/LSN.  This requires the use of
the unique sequence number from OrderAssembledComponent record.
The API call is the same for an LSN (no LSN argument is needed).

This method simply marks the record as _Removed_ and records the user and date/time of the removal.

==== JSON Example - removeComponent()

To remove a component using JSON via the controller, use this request _POST_ request:

*uri:* `/orderAssy/removeComponent`

The JSON content passed to the controller contain the component to remove:

[source,json]
.JSON Remove Component
----
{ "removeOrderAssembledComponentRequest": {
    "order": "M1001",
    "sequence": 247           // <1>
  }
}
----
<1> Every assembled component record for the Order has a unique sequence.  This value must be used to remove it.



[[order-assy-undo-component-remove,OrderAssyService.undoComponentRemove()]]
==== undoComponentRemove()


The link:reference.html#order-assy-undo-component-remove[undoComponentRemove()^] icon:share-square-o[role="link-blue"]
reverses the component removal.  This simply marks the record as Assembled.
This requires the use of the unique sequence number from OrderAssembledComponent
record. The API call is the same for an LSN (no LSN argument is needed).

==== JSON Example - removeComponent()

To restore a removed component using JSON via the controller, use this request _POST_ request:

*uri:* `/orderAssy/undoComponentRemove`

The JSON content passed to the controller contain the component to restore:

[source,json]
.JSON Undo Component Remove
----
{ "componentRemoveUndoRequest": {
    "order": "M1001",
    "sequence": 247           // <1>
  }
}
----
<1> Every assembled component record for the Order has a unique sequence.  This value must be used to remove it.

