
==== eframe.js

The enterprise framework provides some Javascript functions to make it easier to perform some
tasks within the browser.  These are not absolutely required for your application, but they
make working with the server much simpler.  For example, there is a standard dialog window
function that is used for the core confirmation dialogs and the dashboard popup-questions.

NOTE: Any methods that start with an underscore (eg. __checkMissing_) are internal methods
      and are subject to change.


The detailed functions are listed in the reference section
link:reference.html#eframe-js[eframe.js^] icon:share-square-o[role="link-blue"] .
Some important functions are:

* link:reference.html#display-dialog[displayDialog^] icon:share-square-o[role="link-blue"]
* link:reference.html#display-question-dialog[displayQuestionDialog^] icon:share-square-o[role="link-blue"]
* link:reference.html#displaytextfielddialog[displayTextFieldDialog^] icon:share-square-o[role="link-blue"]
* link:reference.html#eframe-lookup[lookup^] icon:share-square-o[role="link-blue"]


===== Calling eframe.js Functions

These library functions use the prefix `eframe` to reduce the chance of name conflicts with any other javascript
libraries.  A short example is shown below:

[source,javascript]
.EFrame Javascript Example
----
// Display a simple confirmation.
ef.displayQuestionDialog({title: 'Delete',
       question: 'Ok to Delete?',
       done: function (e) {
         // Handles Ok button
         deleteRecord();
       }
     });
----


NOTE: If the name _ef_ conflicts with any other javascript variables, then you can use
      _eframe_ instead.

