
== Domains

ifeval::["{backend}" != "pdf"]

[inline-toc]#<<Guidelines>>#

[inline-toc-header]#Demand#
[inline-toc]#<<Order>>#
[inline-toc]#<<lsn>>#
[inline-toc]#<<CodeSequences>>#

[inline-toc-header]#Product#
[inline-toc]#<<Product>>#
[inline-toc]#<<Routing>>#

[inline-toc-header]#Floor#
[inline-toc]#<<WorkCenter>>#

[inline-toc-header]#Tracking#
[inline-toc]#<<ActionLog>>#
[inline-toc]#<<ProductionLog>>#


endif::[]

The SimpleMES data model contains many domain classes to support production operations.
The object big picture looks like this:


//workaround for https://github.com/asciidoctor/asciidoctor-pdf/issues/271
:imagesdir: {imagesdir-build}

[plantuml,"bigPicture",align="center"]
.MES Object Big Picture
----
@startuml

object Order
object Product
object Routing
object RoutingOperation
object LSN

object ActionLog
object ProductionLog

object CodeSequence
object OrderSequence
object LSNSequence

object WorkCenter

Order o-- LSN
Order -- Product
Product -- Routing
Routing -- RoutingOperation
LSN -- Routing
Order -- ActionLog : has actions logged
Order -- ProductionLog : has production logged

CodeSequence <|-- OrderSequence
CodeSequence <|-- LSNSequence

@enduml
----

//end workaround for https://github.com/asciidoctor/asciidoctor-pdf/issues/271
:imagesdir: {imagesdir-src}

=== Guidelines


ifeval::["{backend}" != "pdf"]

[inline-toc]#<<Diagrams>>#
[inline-toc]#<<Name Fields (Primary Keys)>>#
[inline-toc]#<<Title (Short Description)>>#
[inline-toc]#<<Custom Field Extensions>>#
[inline-toc]#<<Status>>#

endif::[]


The data model and documentation for SimpleMES follows some general guidelines.

==== Diagrams

There are a number of object diagrams to show you the relationships between various objects. These follow a general
shape and color scheme as shown below:

//workaround for https://github.com/asciidoctor/asciidoctor-pdf/issues/271
:imagesdir: {imagesdir-build}


.Color and Package Conventions
[ditaa,"packages"]
----
        Shapes               Colors
       (Objects)           (Packages)

    +-------------+     +-------------+
    | Controllers |     |   Demand    |
    |   {io}    io|     |         c6D6|6D6
    +-------------+     +-------------+
    /-------------\     |   Product   |
    |   Domains   |     |         c4CF|4CF
    |             |     +-------------+
    \-------------/     |    Floor    |
    +-------------+     |         cF90|F90
    |  Services   |     +-------------+
    |             |     |   Defects   |
    +-------------+     |         cF88|F88
                        +-------------+
                        |   System    |
                        |         cCCC|CCC
                        +-------------+
                        |   Others    |
                        |         cEB9|EB9
                        +-------------+

----


==== Name Fields (Primary Keys)

Most top-level objects have a primary key field that is generally referred to as the record's
_'name'_.  This is usually the primary key for the record.  Most objects have just one primary
key field.  For example, `Order` has a primary key field _'order'_.  This field must be unique in
most cases.  No other `Order` can have the same _order_ value.

SimpleMES uses the term _'name'_ as the record's identifier, as the user sees it.  SimpleMES uses
this _'name'_ term to avoid confusion with the _ID_ used in the database.

Some ERP systems use the term 'Internal Reference'.  This is the same as the _'name'_ in SimpleMES.

NOTE: Most search mechanisms allow you to search on the name and the title.



==== Title (Short Description)

Most top-level objects have a _'title'_.  This is normally treated as a one line short
title/description for the user. This value does not have to be unique, but it is best if your
records have unique titles.  This title is frequently used in drop-down lists and other GUI
elements.

Some objects have a longer description, but this is not as common.  The _'description'_ field is
used for multi-line descriptions that are used in only a few places such as _Product_.


include::statusGuide.adoc[]


==== Custom Field Extensions

Most domain classes in SimpleMES can be extended with a limited number of custom fields.
These are marked with the `@ExtensibleFields` annotation in the
link:groovydoc/index.html[Groovy API^] documents.  See the Field Extension documentation in
the <<Enterprise Framework>> allows you to add new fields.
Most SimpleMES definition GUIs allow you to edit these custom fields:

=== Demand

The `demand` package defines the demand for production within the shop floor. This includes key
elements such as Orders and Lot/Serial Numbers (LSN).

include::orderGuide.adoc[]

include::lsnGuide.adoc[]

include::sequenceGuide.adoc[]

=== Product Definition

The `product` package defines the products (materials or part numbers) to be be produced.
This also includes details on how to build the products.

include::productGuide.adoc[]

include::routingGuide.adoc[]


=== Floor

The `floor` package defines elements on the shop floor, such as Work Centers.

include::workCenterGuide.adoc[]

=== Tracking

The `tracking` package defines domains that track activity on the shop floor.

include::actionLogGuide.adoc[]

include::productionLogGuide.adoc[]



=== System

The `system` package defines common domains used by other packages or that support the
general setup of the application.



