
[[lsn,LSN (Lot/Serial Number)]]
=== LSN

An link:reference.html#lsn[LSN^] icon:share-square-o[role="link-blue"]
is a portion of an Order.  This is the finest level of tracking possible in SimpleMES. An LSN has
a quantity that is based on the lot size for the product.  If the LSN
represents a serial number then the lot size and quantity are usually 1.0.

==== Orders and LSNs

The relationship between Orders and LSNs is shown below.

//workaround for https://github.com/asciidoctor/asciidoctor-pdf/issues/271
:imagesdir: {imagesdir-build}

[ditaa,"orderLSNRelationship",align="center"]
.Order/LSN Relationship
----

+--------------+
|              |
|    Order     |
|          c6D6|
++-------------++
 |              |
 |   LSN0       |
 |          c6D6|
 +--------------+
 |   LSN1   c6D6|
 +--------------+
 |   LSN2   c6D6|
 +--------------+

----


LSNs are children of Orders.  They are optional and do not need to be created in all cases.  See <<LSN Tracking Option>> and
<<LSN Creation Options>> for details.

NOTE: Because this LSN has a combination primary key of `order` + `lsn`, the API calls using JSON need
      to be a little more complex.  For example:

[source,json]
.LSN JSON Request
----
{
  "order": "M1001",
  "lsn": "SN2001"
}
----

If the `lsn` (_SN2001_ above) is unique, then you can leave off the `order` element.
If the LSN is not unique, then you may receive an error if you attempt to process the LSN
(e.g. Start).

This is a little awkward, but it gives you the ability to re-use the LSN in other orders.
This might be useful for RMA processing or returned products.  It might also be useful
when you have no control over the serial numbers you need to use (e.g. your custom
provides the serial numbers).

LSNs may be globally unique or can be unique within a given product or order.  SimpleMES will
attempt to find the appropriate LSN.  


==== LSN Tracking Option

Tracking within SimpleMES is performed at the order level or at the LSN level.
You must decide how LSNs will be used in producing the orders in SimpleMES.  For a given <<Product>>,
you have these options:

[cols="1,4", width=75%]
|=== 
| LSN Tracking Option | Description

| Order Only   | No LSN tracking is permitted.  The order is processed as one large lot.  No LSNs are used.
| LSN Allowed  | Orders or individual LSNs may be processed.  If LSNs exist, SimpleMES can pick LSNs to process if not specified in the request.
| LSN Only     | Only individual LSNs may be processed.  If just and order is specified, then an error will occur in production actions.
|=== 

The options for tracking these LSNs are defined at the product level, but are copied to the order upon creation.
This prevents problems when the tracking option changes later.  The tracking option at the order level is the one
used during production.

Some production actions can prevent processing by the entire order.  This can be used to force use of LSNs in many
scenarios.

==== LSN Creation Options

LSNs may be assigned at order creation time or later as needed.  This is configured by assigning an LSN Sequence to the
product. See <<Product>> for details on how this is configured at the product level.  LSNs are only automatically
assigned on release when the product's `LSN Tracking Option` is set to _LSN Only_.  You can create the LSN yourself using the
GUI or API for the other scenarios.

The automatic creation of LSNs is done by SimpleMES during the order release process.
See <<OrderService>> for details.  This only happens when the Order's effective
<<LSN Tracking Option>> is set to _LSN_ONLY_.


==== LSNs, Routings and Quantity Tracking

Depending on the <<Product,Product's>> <<LSN Tracking Option>>, individual pieces can be tracked by a unique LSN or
as part of a larger lot. These flexible options mean that the quantity to be worked can be tracked at the order level
or at the LSN level. This means the quantity is stored in multiple places in SimpleMES.  The possible quantity
tracking options are shown below:

//workaround for https://github.com/asciidoctor/asciidoctor-pdf/issues/271
:imagesdir: {imagesdir-build}


[ditaa,"orderLSNRoutingRelationship",align="center",scale=".80"]
.Order/LSN and Routing Relationship
----
          may have   +--------------+
        +------------+              |
        |            |   Product    |
+-------+------+     |          c4CF|
|              |     +--------------+
|   Routing    |
|          c4CF|
+--------------+
|   Routing    |
| Operations   |
|          c4CF|
+------+-------+
       |                                                                     ---+
       |  may have routing   +---------------+                                  |
       +-------------------->|               |qtyInQueue                        |
                             |    Order      |qtyInWork                         |
                             |          c6D6 |qtyDone                           |
                             |               |     +------------+               |
                             |               |     |            |qtyInQueue     |
                             |               |---->| Operations |qtyInWork      |     +----------+
                             |               |     |        c4CF|qtyDone        |     |          |
                             ++--------------+     +------------+               +-----+ Resolve  |
                              |              |qtyInQueue                        |     | Service  |
                              |   LSN        |qtyInWork                         |     |      c6D6|
                              |          c6D6|qtyDone                           |     +----------+
                              +--------------+     +------------+               |
                              |              |     |            |qtyInQueue     |
                              |  LSNRouting  |---->| Operations |qtyInWork      |
                              |          c6D6|     |        c4CF|qtyDone        |
                              +--------------+     +------------+               |
                                                                                |
                                                                             ---+

----


If the routing exists for the product/order, then the quantities are tracked at a routing operation level.  Each
operation has the `qtyInQueue`, `qtyInWork`, etc.  The basic relationship of the objects when routings are used are
shown below:


//workaround for https://github.com/asciidoctor/asciidoctor-pdf/issues/271
:imagesdir: {imagesdir-build}


[plantuml,"orderLSNOperation",align="center"]
.Order/LSN and Operation Relationship
----
@startuml

object Order
object RoutingOperation
object LSN
object LSNOperState
object OrderOperState

Order o-- RoutingOperation  : may have operations
LSN o-- RoutingOperation    : may have operations
RoutingOperation -- OrderOperState : has state
RoutingOperation -- LSNOperState : has state

@enduml
----

//end workaround for https://github.com/asciidoctor/asciidoctor-pdf/issues/271
:imagesdir: {imagesdir-src}


If  `LSN Tracking Option` is _LSN Allowed_ or _LSN Only_, then LSN records will exist for the order.  The quantity is
then tracked at the LSN level.  If  `LSN Tracking Option` is _Order Only_, then the quantities are tracked at the Order
level.

NOTE: The quantities are always tracked at one level for a given order.
      The locations are shown in the table below.


//workaround for https://github.com/asciidoctor/asciidoctor-pdf/issues/271
:imagesdir: {imagesdir-build}

[ditaa,"LSNMatrix",align="center"]
.LSN/Order Quantity Tracking Scenarios
----


               |            LSN Tracking Option             |
               |    Order     |     LSN      |     LSN      |
               |    Only      |    Allowed   |     Only     |
 --------------+--------------+--------------+--------------+
               |              |              |              |
   No Routing  |    Order     |     LSN      |     LSN      |
               |              |              |              |
 --------------+--------------+--------------+--------------+
               | Order        | Order        | Order        |
    Routing    |  .operations |  .operations |  .operations |
               |          cCCC|         cCCC |          cCCC|
 --------------+--------------+--------------+--------------+

----

//end workaround for https://github.com/asciidoctor/asciidoctor-pdf/issues/271
:imagesdir: {imagesdir-src}


Upon order release, the _Order_ copy of the operations are created.  These are copied from the
effective routing from the _Product_  or _MasterRouting_.  It is also possible
to import an order with its own _operations_ if needed.

The detailed operation states are stored in various places, depending on how work is tracked.  All of these
places implement the
link:groovydoc/org/simplemes/mes/demand/WorkStateTrait.html[WorkStateTrait^] icon:share-square[role="link-blue"].
This Trait provides most of the logic and persistent fields needed to track the state.  It provides common
methods such as `queueQty()` or `startQty()`.

The various places this state is stored are:

[cols="4,4",width=75%]
|===
|Scenario           | Work State Object
| No LSN, No Routing| link:groovydoc/org/simplemes/mes/demand/domain/Order.html[Order^] icon:share-square[role="link-blue"]
| No LSN, Routing| link:groovydoc/org/simplemes/mes/demand/domain/OrderOperState.html[OrderOperState^] icon:share-square[role="link-blue"]
| LSN, No Routing| link:groovydoc/org/simplemes/mes/demand/domain/LSN.html[LSN^] icon:share-square[role="link-blue"]
| LSN, Routing| link:groovydoc/org/simplemes/mes/demand/domain/LSNOperState.html[LSNOperState^] icon:share-square[role="link-blue"]
|
|===





