
=== ProductionLog

The link:reference.html#productionlog[ProductionLog^] icon:share-square-o[role="link-blue"]
class represents the result of a production action on the shop floor.
Typically, this is written when the order/LSN is taken out of work so that the
elapsed time can be calculated.
This includes actions like complete and reverse start.

These records are designed to exist without direct references to other domain objects.  This means
the references use the primary key field for the object (e.g. Order, LSN, etc).  Those referenced
objects can be archived and these production log records can be kept in the database
longer than the other domain objects if needed.

For detailed field information, see the API Documentation at:
link:groovydoc/org/simplemes/mes/tracking/domain/ProductionLog.html[ProductionLog^]
icon:share-square-o[role="link-blue"].


==== Production Log Archiving

By default, these records are automatically archived after 6 months.  You can alter these settings
by changing the Background Task for the production log archiver.  This task has these options:

// TODO: Implement when ef supports this.

[cols="1,4",width=75%]
|===
|Field | Description

|ageDays   | The age to archive old records from the production log (*Default:* 180 days).
|batchSize | Number of records to archive in one batch.  This sets the
             database transaction size and the size of the archive JSON file created (*Default:* 500).
|delete    | If checked, then the production log records will be delete instead of writing
             to an archive JSON file (*Default:* unchecked).
|===

WARNING: When checked, the Delete option means the old records are deleted with no
         copy of the records kept by the system.

NOTE: When archiving these records, there is no _ArchiveLog_ record created and the JSON is
      not verified.  These features are disabled automatically, no matter how the
      _application.yml_ configuration is set. This improves the performance.

The archive JSON files are created using the `ProductionLog.toShortString()` method to form the
file name.  This contains the date/time of the first production log record in the archive.
For example:

  ProductionLog-2018-04-18-15-42-35.arc

There is no ordering within the archive files, so it is possible for records from other date/times
to be stored in the file.

