
=== Routing

A link:reference.html#routing[Routing^] icon:share-square-o[role="link-blue"]
is a sequence of operations needed to manufacture a <<Product>>.
These operations can be simple actions
such as _ASSEMBLE_ or _TEST_. They may also be a composite operation that is made up of several
actions that are not tracked within SimpleMES.

Some examples are:

* 10 - ASSEMBLE
* 20 - PAINT
* 30 - PACK
* 40 - TEST

The routing may be a master routing that can be used on multiple products or it may be specific
to a single product. This decision is made when defining the product.

Operations can be optionally defined to execute within a <<WorkCenter>>.  This is useful to
limit where specific operations can be performed.

For detailed field information, see the API Documentation at:
link:groovydoc/org/simplemes/mes/product/domain/Routing.html[Routing^]
icon:share-square-o[role="link-blue"].

=== Routing Object Model

The routing-related object model is somewhat complex.  It supports routings at two levels:
_MasterRouting_ and _Product_.  There is also a copy of the routing at the order level.

The key objects are:

//workaround for https://github.com/asciidoctor/asciidoctor-pdf/issues/271
:imagesdir: {imagesdir-build}

[plantuml,"routingModel",align="center"]
.MES Routing Object Model
----
@startuml

object Order
object Product
object LSN
object RoutingTrait
object MasterRouting
object OperationTrait
object OrderOperation
object ProductOperation
object MasterOperation


Order o-- LSN
Order o-- OrderOperation
Order -- Product
Product -- RoutingTrait
RoutingTrait o-- OperationTrait
RoutingTrait <|-- MasterRouting
OperationTrait <|-- OrderOperation
OperationTrait <|-- ProductOperation
OperationTrait <|-- MasterOperation
Product o-- ProductOperation


@enduml
----


//end workaround for https://github.com/asciidoctor/asciidoctor-pdf/issues/271
:imagesdir: {imagesdir-src}

A _product_ can refer to a _MasterRouting_ or have its own routing.  When
released, the _Order_ will have a copy of the routing operations from the
product/master routings.

Each routing has a list of operations.  These operations all implement
the _OperationTrait_.  When released, the _Order_ or _LSN_ will have an
operation state record created for each operation on the routing.  See
<<Order Object Model>> for details.
