
=== Status

Status codes use the framework's
link:{eframe-path}/guide.html#encoded-types[Encoded Types^] icon:share-square-o[role="link-blue"]
capability.  These are normal POGO's with a short string used for storage in
a single column in the domain.
This also allows modules to add additional status codes.

These statuses are stored as a single field in the domain object they 'control'.
The base class defines the methods needed at run-time to operate.  For example, the
link:groovydoc/org/simplemes/mes/demand/OrderStatus.html[OrderStatus^] icon:share-square-o[role="link-blue"]
defines a `isWorkable()` method to determine if the order can be worked.  Each status sub-class will
will define whether it means the order is workable or not.

An example use of the `OrderStatus` is shown below:

[source,groocy]
.Example - Order Status Use
----
class Order {
  String order
  OrderStatus status = OrderStatus.defaultStatus  // <.>

  void start() {
    if (!status.isWorkable()) {  // <.>
      thrown new BusinessException(. . .)
    }
    . . .
  }
}
----
<.> The default status is provided by the base `OrderStatus` class.
<.> The status is checked to make sure it means the order is workable.


==== Status Usage

Each domain object will decide which status(es) it will use.  The most important objects and
statuses used are:

[cols="1,1,4",width=75%]
|===
|Domain | Status | Default Status Codes
| `Order`
| link:groovydoc/org/simplemes/mes/demand/OrderStatus.html[OrderStatus^]
| link:groovydoc/org/simplemes/mes/demand/OrderCreatedStatus.html[OrderCreatedStatus^],
  link:groovydoc/org/simplemes/mes/demand/OrderReadyStatus.html[OrderReadyStatus^],
  link:groovydoc/org/simplemes/mes/demand/OrderHoldStatus.html[OrderHoldStatus^],
  link:groovydoc/org/simplemes/mes/demand/OrderDoneStatus.html[OrderDoneStatus^]

| `LSN`
| link:groovydoc/org/simplemes/mes/demand/LSNStatus.html[LSNStatus^]
| link:groovydoc/org/simplemes/mes/demand/LSNReadyStatus.html[LSNReadyStatus^],
  link:groovydoc/org/simplemes/mes/demand/LSNHoldStatus.html[LSNHoldStatus^],
  link:groovydoc/org/simplemes/mes/demand/LSNDoneStatus.html[LSNDoneStatus^],
  link:groovydoc/org/simplemes/mes/demand/LSNScrappedStatus.html[LSNScrappedStatus^]
     
| `WorkCenter`
| Framework `BasicStatus`
| EnabledStatus, DisabledStatus

|
|===

