
== Services

ifeval::["{backend}" != "pdf"]

[inline-toc]#<<Service Transactions>>#
[inline-toc]#<<Arguments and Return Values>>#
[inline-toc]#<<Domain Validation Errors>>#

endif::[]



Services are where much of your business logic will be implemented.
Your service classes have a few requirements to be easily used within the framework.
Your services should be in proper packages, but that is not required.

=== Service Transactions

All services that perform database changes should be marked as transactional:


[source,groovy,linenum]
.Transactional Service
----
package org.simplemes.mes.assy.floor

import grails.gorm.transactions.Transactional

@Transactional  // <1>
class WorkCenterAssyService {

  void someMethod() {
   . . .
  }
}

----
<1> Makes all public methods as transactional.  Can be called from within an existing transaction
    without creating a new session/transaction.


=== Arguments and Return Values

Most services will need arguments passed in and will return values.  These values should be
Java/Groovy objects (e.g. Domains, POJOs or POGOs).  Passing and returning JSON should be
handled by the controllers.

In addition, most services that need multiple inputs should use a POGO to make a more readable API.
This makes it much easier to pass a large number of objects in a clear way.

NOTE: Most service methods should be designed to take domain objects as inputs, when possible.
      This is done instead of passing key field (e.g. Strings) as parameters.
      This reduces the amount of database access, but also forces you to manage <<Transactions>> in
      the calling code.


[source,groovy,linenum]
.Example Service Arguments
----
@Transactional
class WorkCenterAssyService {

  /**
   * This method adds a component...
   */
  WorkCenterComponent addComponent(AddComponentRequest addComponentRequest) {  // <.>
   . . .
  }
}

/**
 * This class is the request to add a component to a work center's current setup.
 */
class AddComponentRequest {
  WorkCenter workCenter   // <.>
  Product component
  String location
  BigDecimal qty
}
----
<.> A POGO is passed in and a domain object is returned.
<.> The fields can be domain objects.  This means teh caller will populate this POGO
    within its own transaction.

The above example uses POGO to receive a large number of arguments.  It then returns a domain object
(WorkCenterComponent) that was created by this request.


=== Domain Validation Errors

Frequently, your services will process domain objects and attempt to save them.  Sometimes, these
will fail due to validation errors.  To display/return these consistently, it is best to let
GORM throw an exception upon save using the _failOnError: true_ option.

See <<GORM>> for ways to make this the default setting.


