
=== ScanService

ifeval::["{backend}" != "pdf"]

[inline-toc]#<<Scan - Architecture and Modules>>#
[inline-toc]#<<Scan - Order/LSN Processing>>#
[inline-toc]#<<Handling Other Objects>>#
[inline-toc]#<<Barcode Formats>>#
[inline-toc]#<<Scan Actions>>#

endif::[]

The link:reference.html#scanservice[ScanService^] icon:share-square-o[role="link-blue"]
is used resolve a barcode input to a <<Scan Dashboard>> and perform an action on that input.
This action can be to start an Order/LSN or to press a button on the dashboard.

This service's methods are exposed by the
link:groovydoc/org/simplemes/mes/system/controller/ScanController.html[ScanController^]
icon:share-square[role="link-blue"].  This controller supports the request/response POGOs
in JSON format.

The scan service resolves a barcode input using a basic simple search routine.  The optional
link:{mes-path}/guide.html#modules[Modules^] icon:share-square-o[role="link-blue"]
can add additional types of objects support by the scan service using method
extensions.  The core search routine follows this search order:

. Internal Barcode Format (delimited with ^).
. Configured Barcode Format (TBD).
. Intelligent search routine:
.. LSN
.. Order
.. (Module-specific objects such as Component, Location)

Once the barcode content is determined, then the scan service will optionally perform
an action on the scanned object.

Once any action is completed, the result is returned to the dashboard for display and possible
additional GUI actions such as:

* Dashboard Button Press
* GUI Refresh
* Module-Specific actions (e.g. start assembly process by selecting a component).

==== Scan - Order/LSN Processing

The MES core logic will start the Order/LSN if it is in queue. This start can be reversed with the normal dashboard
link:{eframe-path}/guide.html#undo[Undo^] icon:share-square-o[role="link-blue"] feature.

==== Scan - Architecture and Modules

The <<Scan Dashboard>> is designed to work with optional modules.  These optional modules can change the
default flow and add more options to the dashboard behavior.  To make this work, the scan dashboard
and related objects work together to handle scans and update the dashboard as needed.  The basic
flow of a scan (Order scan) is shown below:

//workaround for https://github.com/asciidoctor/asciidoctor-pdf/issues/271
:imagesdir: {imagesdir-build}

[ditaa,"scanDashboardFlow"]
----
                       |
 Dashboard(Client)     |           Server
                       |

+------------------+      +---------------------+
|  Scan            +----->| ScanController cBLU |
|    (Order)  cGRE |      |  scan()             |
+------------------+      +----------+----------+
                                     |
                            +--------+------------+
                            | ResolveService cBLU |
                            |  resolveID()        |
                            +--------+------------+
                                     |
                            +--------+------------+
                            | WorkService    cBLU |
                            |  start()            |   +-----------------+
                            +--------+------------+   | AssyScanService |
                                     |<---------------+  postScan()     |
+------------------+      +----------+----------+     |            cYEL |
|  Update UI       |<-----+ Response       cCCC |     +-----------------+
|             cGRE |      |  ScanAction/Message |
+------------------+      +----------+----------+

----

//end workaround for https://github.com/asciidoctor/asciidoctor-pdf/issues/271
:imagesdir: {imagesdir-src}

The scan request is sent to the server, which determines what the scan is and what to do
with it.  In this case, it is an order that is in queue and the server starts the
order.  After the start, a response is returned to the client that tells the dashboard
to update the UI for the started order.

==== Handling Other Objects

The default core logic attempts to resolve inputs using the following precedence:

. LSN
. Order

The optional link:{mes-path}/guide.html#modules[Modules^] icon:share-square-o[role="link-blue"]
can add objects to this list before or after the core objects.

To handle additional objects, the module should define a post method extension on the `ScanService.scan()`
method as shown above.
The link:{mes-path}/guide.html#modules[Assembly^] icon:share-square-o[role="link-blue"]
module adds components to the search list (after the core objects).
The extension looks for components to be assembled.  It can then open an activity to collect other
barcode inputs for the assembly data needed for that component.

The core dashboard logic will handle LSN and order scanning.  Once resolved, the scanned order/LSN will
become the 'current' order/LSN.  This will be passed with the scan request so that the module can use this
to help narrow down the choices for the scanned item.  This helps find components required for a given order.

// Configuration Options

==== Barcode Formats

Barcode formats come in many shapes and sizes.  SimpleMES does not require any specific
format or scanner.  The main requirements are:

* The scanner sends the data to the browser as keyboard input.
* The scanner sends a TAB character as the suffix after the data is sent.

Additional barcode format details are supported including:

* Data only (e.g. The order ID is the only value encoded in the barcode: 'M1001').
* Internal Structure (Delimited data using ^ as a delimiter: '\^PRD^BIKE-27A').
* Configurable formats (TBD)

The scan service will use any formatted barcode values to determine the type of object
scanned.  If no formatting is used, then the intelligent search logic will find the right
object that matches the scanned value.  The precedence in the core MES module is:

. LSN
. Order

The optional link:{mes-path}/guide.html#modules[Modules^] icon:share-square-o[role="link-blue"]
can add objects to this list before or after the core objects.
For example, the link:{mes-path}/guide.html#modules[Assembly^] icon:share-square-o[role="link-blue"]
module adds component to the search list (after the core objects).



==== Scan Actions

For every scan, there is a
link:reference.html#scan-response-interface[ScanResponseInterfaces^] icon:share-square-o[role="link-blue"]
returned.
This response contains a list of
link:groovydoc/org/simplemes/mes/system/ScanAction.html[ScanActions^] icon:share-square-o[role="link-blue"]
that indicate what should be performed on the client.

These actions are POGOs that must contain a `type`, which indicates what the event is or action is.
It is up to the client to determine how to process them.  Each scan action will be sent to all dashboard
activities as <<Dashboard Events>>.

See link:reference.html#scan-actions[Scan Actions^] icon:share-square-o[role="link-blue"]
for specific details on the actions.
