
=== CodeSequence

link:groovydoc/org/simplemes/mes/numbering/CodeSequenceTrait.html[CodeSequenceTrait^] icon:share-square-o[role="link-blue"]
control how various system generated key values are generated within SimpleMES.
There are a number of specific classes used to generate keys for objects such
as <<lsn,LSN's>> or <<Order,Orders>>. This section covers features common to all code sequences.
Specific sequences such as <<LSNSequence>> inherit these features.


The sequence is defined using a format string and an optional sequence number.  The format string
can be a simple value or it can contain replaceable parameters that are replaced at generation
time.  For example, to generate some codes/keys for the form _XYZ-123_, you would use the
format string:


[source,groovy]
.Example LSN Sequence
----
XYZ-$currentSequence
----

This will result in codes like _'XYZ-001','XYZ-002'_...

At generation time, these '$' strings are replaced by the actual value in use at the time.  These '$' strings follow
the standard Groovy G-String formats. There are a number of standard parameters that can be used in all code sequences:

[cols="1,4",width=75%]
|===
| Parameter | Description

| $currentSequence | Standard sequence counter.  This is incremented after each code is generated.
| ${date.format('yyMMdd')} | The date/time the code was generated.  The various format strings are shown below.
|=== 

This list is much larger for the specific sequences such as <<LSNSequence>>.

NOTE: The simple format _'$pogo.field'_ is not supported.  You should use the format with curly brackets version
      _'${pogo.field}'_

==== Date Formats

The common date/time formatting strings are shown below.  The number of characters 

[cols="1,1,2",width=75%]
|===
| String | Description | Example

|y|Year                 |1996; 96
|M|Month in year        |July; Jul; 07
|w|Week in year         |27
|W|Week in month        |2
|D|Day in year          |189
|d|Day in month         |10
|F|Day of week in month |2
|E|Day in week          |Tuesday; Tue
|a|Am/pm marker         |PM
|H|Hour in day (0-23)   |0
|k|Hour in day (1-24)   |24
|K|Hour in am/pm (0-11) |0
|h|Hour in am/pm (1-12) |12
|m|Minute in hour       |30
|s|Second in minute     |55
|=== 

You can use as many digit characters as needed.  Some format strings use abbreviation for shorter values.  For example,
_MMM_ will be displayed as _Jul_.  See the Java class
http://java.sun.com/j2se/1.5.0/docs/api/java/text/SimpleDateFormat.html[SimpleDateFormat^]
for full details.

More complex logic can be used in these format strings if needed. For example, this format:

[source,groovy]
.Complex Date Format
----
${def d=date+1;d.format('yyMMdd')}
----

This will format _tomorrow's_ date into the _yyMMdd_ format.  The length of the format string is limited, so complex
script logic should be avoided.


