
=== Standard Fields

Almost all persistent objects in SimpleMES have a number common fields.  The standard fields are:

[cols="1,4",width=90%]
|===
|Field | Description

|`uuid` |The Internal DB UUID for this object.  This is used for internal references between
         objects in SimpleMES.  (*database primary key*)
|`key(s)/name` | One or more primary key fields for the object.  These are usually unique and
                 provided by the user.  The user will typically retrieve the records by these
                 key fields.  The first key field is usually named the same as the object
                 (e.g. _Order_ has a key field of `order`).  Sometimes, the word 'name' is used
                 in place of key field.
|`title`| The displayed title of the object.  This is typically a short one line description of
          the object.  This is displayed in most cases in parentheses along with the code field.
|`version`| The internal version of this object.  This allows optimistic locking of the object.
            This is incremented on each save and prevents one user from overwriting another
            user's data.
|`dateCreated`| The date/time this object was created (not all objects).
|`dateUpdated`| The date/time this object was last updated (not all objects).
|=== 
