
[[order-assy-service]]
=== OrderAssyService

ifeval::["{backend}" != "pdf"]

[inline-toc]#<<order-assy-add-component,addComponent()>>#
[inline-toc]#<<order-assy-find-component-assembly-state,findComponentAssemblyState()>>#
[inline-toc]#<<order-assy-remove-component,removeComponent()>>#
[inline-toc]#<<order-assy-undo-component-remove,undoComponentRemove()>>#

endif::[]



The link:groovydoc/org/simplemes/mes/assy/demand/service/OrderAssyService.html[OrderAssyService^]
icon:share-square-o[role="link-blue"]
provides methods to process assembly information on an order or LSN.
This service provides the ability to assemble components and adds assembly
extensions to the mes core Order logic.
This includes copying component details to the order during release of the order.
See link:{mes-core-path}/guide.html#services[MES Core Services^] icon:share-square-o[role="link-blue"]
for details on the core service.

The service methods are exposed using the
link:groovydoc/org/simplemes/mes/assy/demand/OrderAssyController.html[OrderAssyController^].
icon:share-square-o[role="link-blue"]
These controller methods generally match the inputs and outputs of the services.
The only difference is the values are passed as XML/JSON strings.

The controller does not expose the normal CRUD (Create, Read, Update and Delete) methods that are common
with domain objects.  The methods provide a way to maintain all component records, but preserves
the long-term history of the component setup records.


[[order-assy-add-component,OrderAssyService.addComponent()]]
==== addComponent()

This method adds a component to the given order/LSN.  It supports
<<{eframe-path}/guide.adoc#flexible-fields,Flexible Fields>> to define customer-specific input fields
for the assembled components.
The component can be added for the entire order or just for a single LSN.

This method is considered part of the link:{mes-core-path}/guide.html#stable-api[Stable API^] icon:balance-scale[role="green"].

The link:groovydoc/org/simplemes/mes/assy/demand/AddOrderAssembledComponentRequest.html[AddOrderAssembledComponentRequest^]
icon:share-square-o[role="link-blue"] object is the main argument for the `addComponent()` method.
This is a simple POGO that you must populate before you call the method.

[cols="1,4", width=75%]
|===
|Field | Description
| `order`     | The link:{mes-core-path}/guide.html#order[Order^] icon:share-square-o[role="link-blue"] the
                component is to be assembled on (*Required*).
| `lsn`       | The link:{mes-core-path}/guide.html#lsn[LSN^] icon:share-square-o[role="link-blue"] the component
                is to be assembled on (*optional*).
| `bomSequence`| The link:groovydoc/org/simplemes/mes/assy/demand/OrderBOMComponent.html[OrderBOMComponent^]
                    icon:share-square-o[role="link-blue"] from the order's list of components (*Optional*).
| `component` | The component link:{mes-core-path}/guide.html#product[Product^] icon:share-square-o[role="link-blue"]
                to be added to the order (*Required*).
| `workCenter`| The link:{mes-core-path}/guide.html#work-center[Work Center^] icon:share-square-o[role="link-blue"]
                the component is to be assembled in (*Optional*).
| `location`  | The location that the component is to be assembled from.  This could be a bin location in the work center
                (*default: '@'*).
| `qty`       | The number of pieces to assemble.  Will use the `component.qty` if provided in the input. (*Default: 1.0*).
| `assemblyData`  | The FlexType used to define the assembly data for this component.  See
                link:{eframe-path}/guide.html#flexible-fields[Flexible Fields^]
                icon:share-square-o[role="link-blue"] for details (*Optional*).
|===

This method returns the
The link:groovydoc/org/simplemes/mes/assy/demand/OrderAssembledComponent.html[OrderAssembledComponent^]
icon:share-square-o[role="link-blue"] created for this request.

NOTE: To handle assembly data values from the flex type, you must provide the assemblyData element
      in the JSON input (via the controller) first.
      This can be the flexType key field or its UUID.  If not given first, then the 'assemblyData_'
      values will be ignored.

[[order-assy-add-component-example]]
===== JSON Example

To add a component using XML/JSON via the controller, use this request _POST_ request:

*uri:* `/orderAssy/addComponent`

The JSON content passed to the controller contain the component to add:

[source,json]
.JSON Add Component
----
{
  "addOrderAssembledComponentRequest": {
    "order": "M1001",
    "lsn": {
      "lsn": "SN2037"
    },
    "component": "CPU",                         // <1>
    "location": "BIN 47",
    "workCenter": "CELL_17",
    "qty": 47.2,
    "assemblyData": {                               // <2>
      "flexType": "$flexType.flexType",
      "category": "$flexType.category"
    },
    "assemblyDataValues": {                         // <3>
      "ASSEMBLY0": "ACME4"
    }
  }
}
----
<1> The component is a reference to a product domain record.
<2> `assemblyData` is a Flex Type.  This must come before the field values.
<3> The LOT assembly flex type allows input of `vendor` and `lot` values.


[[order-assy-find-component-assembly-state,OrderAssyService.findComponentAssemblyState()]]
==== findComponentAssemblyState()

This method finds the state of all the components needed for the given order/LSN.
If LSN is given, then the logic will attempt to reconcile order-based components
with this single LSN.  This will cause problems when mixing order-based and LSN-based
assembly for a given component. Typically, this will report a fully assembled component for LSN
when it is uncertain.

This method does no pagination or filtering, but it does sort by sequence.
This method supports
<<{eframe-path}/guide.adoc#flexible-fields,Flexible Fields>> to define customer-specific input fields
for the assembled components.

The request is a
link:groovydoc/org/simplemes/mes/assy/demand/FindComponentAssemblyStateRequest.html[FindComponentAssemblyStateRequest^]
icon:share-square-o[role="link-blue"] with these elements:


[cols="1,4", width=75%]
|===
|Field | Description
| `demand`        | The order/LSN to find the components for.
| `hideAssembled` | If true, then all components that are fully assembled or over assembled will be filtered out (*Default*: false).
|===

This method returns a list of
The link:groovydoc/org/simplemes/mes/assy/demand/OrderComponentState.html[OrderComponentState^]
icon:share-square-o[role="link-blue"] objects that can displayed in GUIs.  This object includes a number
of display values, that are localized by the request's locale.

[[order-assy-find-component-assembly-state-example]]
===== JSON Example

To find the current components on an order or LSN, you perform a _GET_ request on:

*uri:* `/orderAssy/findComponentAssemblyState?order=M1001&format=json`

The response is a map with the total number of rows available and a list of the _OrderComponentState's_.

[source,json]
.JSON findComponentAssemblyState() Response Example
----
{ "totalAvailable": 2,
  "fullyAssembled": true,
  "list": [ {
      "class": "org.simplemes.mes.assy.demand.OrderComponentState",
      "assemblyDataAsString": "<b>ASSEMBLY1</b>: 2017103 <b>ASSEMBLY0</b>: ACME_DEPOT",
      "qtyRequired": 1.00,
      "component": "CPU",
      "assemblyData": {
        "class": "org.simplemes.eframe.custom.FlexType",
        "id": 1,
        "flexType": "ASSEMBLY",
        "category": "BASIC"
      },
      "qtyAndStateString": "1/1 Full",
      "sequence": 10,
      "percentAssembled": 100,
      "overallState": "FULL",
      "overallStateString": "Full",
      "location": "&#64;",
      "assemblyDataValues": {
        "ASSEMBLY0": "ACME_DEPOT",
        "ASSEMBLY1": "2017103"
      },
      "qtyAssembled": 1.00
    }, {
      "class": "org.simplemes.mes.assy.demand.OrderComponentState",
      "assemblyDataAsString": "<b>ASSEMBLY1</b>: 2016879 <b>ASSEMBLY0</b>: ACME_PRIME",
      "qtyRequired": 2.00,
      "component": "MOTHERBOARD",
      "assemblyData": {
        "class": "org.simplemes.eframe.custom.FlexType",
        "id": 1,
        "flexType": "ASSEMBLY",
        "category": "BASIC"
      },
      "qtyAndStateString": "2/2 Full",
      "sequence": 20,
      "percentAssembled": 100,
      "overallState": "FULL",
      "overallStateString": "Full",
      "location": "&#64;",
      "assemblyDataValues": {
        "ASSEMBLY0": "ACME_PRIME",
        "ASSEMBLY1": "2016879"
      },
      "qtyAssembled": 2.00
    }
  ]
}
----


[[order-assy-remove-component,removeComponent()]]
==== removeComponent()

This method removes a component from the given order/LSN.
The component can be added for the entire order or just for a single LSN.
This requires the use of
the unique sequence number from <<order-assembled-component,OrderAssembledComponent>> record.
The API call is the same for an LSN (no LSN argument is needed).

This method simply marks the record as _Removed_ and records the user and date/time of the removal.
This method is considered part of the link:{mes-core-path}/guide.html#stable-api[Stable API^] icon:balance-scale[role="green"].

The link:groovydoc/org/simplemes/mes/assy/demand/RemoveOrderAssembledComponentRequest.html[RemoveOrderAssembledComponentRequest^]
icon:share-square-o[role="link-blue"] object is the main argument for the `removeComponent()` method.
This is a simple POGO that you must populate before you call the method.  Also, these arguments can be passed
from input fields or as HTTP parameters if needed.

[cols="1,4", width=75%]
|===
|Field | Description
| `order`     | The link:{mes-core-path}/guide.html#order[Order^] icon:share-square-o[role="link-blue"] that the
                component was assembled on (*Required*).
| `sequence`  | The unique sequence from the <<order-assembled-component,OrderAssembledComponent>> record
                to mark as removed (*Required*).
|===

This method returns a map with these elements:

[cols="1,4", width=75%]
|===
|Field | Description
| `orderAssembledComponent`     |The link:groovydoc/org/simplemes/mes/assy/demand/OrderAssembledComponent.html[OrderAssembledComponent^]
                                 icon:share-square-o[role="link-blue"] that was marked as removed for this request
| `infoMsg`  | The user-readable message that indicates the component removed.
| `undoActions`  | The list of undo actions to undo this removal.
|===

===== JSON Example

To remove a component using JSON via the controller, use this request _POST_ request:

*uri:* `/orderAssy/removeComponent`

The JSON content to remove the component is:

[source,json]
.JSON Remove Component
----
{ "removeOrderAssembledComponentRequest": {
    "order": "M1001",
    "sequence": 247
  }
}
----


[[order-assy-undo-component-remove,undoComponentRemove()]]
==== undoComponentRemove()

This method reverses the component removal.  This simply marks the record as Assembled and clears the user it
was removed by and clears the removed date. This requires the use of the unique sequence number from
OrderAssembledComponent record. The API call is the same for an LSN (no LSN argument is needed).

This method simply marks the record as _Assembled_ and then it clears removed by user and date/time of the removal.
This method is considered part of the link:{mes-core-path}/guide.html#stable-api[Stable API^] icon:balance-scale[role="green"].

The link:groovydoc/org/simplemes/mes/assy/demand/ComponentRemoveUndoRequest.html[ComponentRemoveUndoRequest^]
icon:share-square-o[role="link-blue"] object is the main argument for the `undoComponentRemove()` method.
This is a simple POGO that you must populate before you call the method.  Also, these arguments can be passed
from input fields or as HTTP parameters if needed.

[cols="1,4", width=75%]
|===
|Field | Description
| `order`     | The link:{mes-core-path}/guide.html#order[Order^] icon:share-square-o[role="link-blue"] that the
                component was assembled on (*Required*).
| `sequence`  | The unique sequence from the <<order-assembled-component,OrderAssembledComponent>> record
                to mark as removed (*Required*).
|===

This method returns the
The link:groovydoc/org/simplemes/mes/assy/demand/OrderAssembledComponent.html[OrderAssembledComponent^]
icon:share-square-o[role="link-blue"] that was marked as assembled for this request.

===== JSON Example

To restore a removed component using JSON via the controller, use this request _POST_ request:

*uri:* `/orderAssy/undoComponentRemove`

The JSON content to restore the removed component is:

[source,json]
.JSON Undo Remove Component
----
{ "componentRemoveUndoRequest": {
    "order": "M1001",
    "sequence": 247
  }
}
----

