
== API

ifeval::["{backend}" != "pdf"]

[inline-toc]#<<JSON>>#
[inline-toc]#<<Rest API>>#
[inline-toc]#<<API Formats>>#
[inline-toc]#<<API Actions - Non-CRUD>>#
[inline-toc]#<<API Error Handling>>#

endif::[]



This section describes how you can create consistent and easy to use APIs for your application.
The goal is to provide you with tools to create the APIs and avoid repeating yourself too much
in the process.

Many of the default Micronaut/Jackson features come close to the proper enterprise approach,
but they miss out in key areas.  This includes dealing with domain references and other
related issues.  These issues are mostly hidden from you when you use the built-in <<Rest API>>
support for this framework.  It handles most of the strange database issues and supports the
right formats (e.g. ISO Date formats, etc).


If you do not use the built-in <<Rest API>>, then you will need to handle these types of issues:

* Create/Read/Update/Delete (CRUD).
* Child records.
* Date/time encoding (ISO).
* Child record removal.
* Clean key field handling (no database UUIDs needed).
* Support for optional database UUID in references to other objects.
* One-to-one relationship handling.
* One-to-many relationship handling (children).
* Standardized Controller/Service use for APIs.


include::json.adoc[]

include::restAPI.adoc[]

include::apiFormats.adoc[]

include::apiOther.adoc[]


