
=== API Formats

ifeval::["{backend}" != "pdf"]

[inline-toc]#<<Common Element Formats>>#
[inline-toc]#<<ISO 8601 Date/Time Formats>>#
[inline-toc]#<<Enumerations>>#
[inline-toc]#<<References to Domain Objects>>#
[inline-toc]#<<Custom Fields>>#

endif::[]




The REST APIs support JSON for the objects processed.  The formatting and parsing is handled by
Jackson, with some help from framework logic. This section covers the common text formats supported
for things like dates and numbers.  It also covers how references to
domain objects are handled and specific limitations of various formats.

==== Common Element Formats

Since JSON is a text-based format, you must follow specific formats for some internal data types.
A short example is shown below:

[source,json]
.JSON Format for Example Order Domain
----
{
  "orderCode": "10102-23",
  "qty": 12.2,
  "enabled": false,
  "dateOrdered": "2009-02-13T18:31:30.000-05:00",
  "dateToBeDelivered": "2013-08-04"
}
----

The normal JSON primitive field formats allowed are:

[cols="1,4"]
|=== 
|Type|Description

|Number|Numbers with fractions must use the decimal point as the decimal separator.
|Booleans| Booleans are encoded as _true_ or _false_.
|Dates| Dates are in ISO date format: yyyy-mm-dd.
|DateTimes| Date/Times are in ISO date/time format: yyyy-mm-ddThh:mm:ss.sssZZZZZ.  (The Z is the timezone offset).
|=== 

==== ISO 8601 Date/Time Formats

The framework can read and write ISO date/time formats.  There are a few variations supported:

[cols="2,4"]
|===
|Format|Example

|yyyy-mm-ddThh:mm:ss.sssZ| 2009-02-13T23:31:30.000Z  (Always in UTC Timezone)
|yyyy-mm-ddThh:mm:ssZ| 2009-02-13T23:31:30Z  (Always in UTC Timezone)
|yyyy-mm-ddThh:mm:ss.ssszzzzzz| 2009-02-13T18:31:30.000-05:00 (Format used when writing a date/time).
|yyyy-mm-ddThh:mm:sszzzzzz| 2009-02-13T18:31:30-05:00
|=== 

The first format is used when writing date/times for JSON.


==== Enumerations

The Java Enums typically have an internal ID that is stored in the database and a `toString()`
representation that is more human-readable.
The framework expects both values to be unique within the enumeration.

For JSON, the output is the human-readable format (not localized):

[source,json]
.JSON Format
----

"fieldFormat": "STRING"

----


==== References to Domain Objects


Foreign keys within domain objects are stored with their IDs in a column in the database.
The JSON format for these references can use the 'id' format:


[source,json]
.JSON Foreign Reference by ID
----
{
  "orderCode": "10102-23",
  "customer": {
    "uuid": "dbb0c868-3ae5-4fd1-a0a4-e0ddda375e2b"  // <1>
  }
}
----
<1> The internal ID of the customer record.


You can also use the key fields for these foreign references:

[source,json]
.JSON Foreign Reference by Key Field(s)
----
{
  "orderCode": "10102-23",
  "product": {
    "product": "BIKE_27"  // <1>
  }
}
----
<1> The primary key of the foreign record to reference.


You can also use the key fields in a simple format using the simplified
<<json-by-key,@JSONByKey>> format:

[source,json]
.JSONByKey Foreign Reference by Key Field
----
{
  "orderCode": "10102-23",
  "product": "BIKE_27"  // <1>
}
----
<1> The primary key of the foreign record to reference.

NOTE: You must mark the reference using the <json-by-key,@JSONByKey>> annotation.


==== Custom Fields

<<Field Extensions>> and <<Configurable Types>> are special fields that are added by
your users and sometimes by module programmers.  These are accessed via the JSON like normal
fields.

For example, a custom `Order` with two custom fields ('promiseDate', 'caseColor') would be
accessed like this:

[source,json]
.JSON Format for Field Extensions
----
{
  "order": "M10102-23",
  "qty": 12.2,
  "_fields": {
    "promiseDate": "2009-02-13T18:31:30.000-05:00",
    "caseColor": "BLUE"
    "_config": {
      . . .   <.>
    }
  }
}
----
<.> The custom field configurations.  This is stored with the field values to allow
    the definitions to change without los of data/type information.
    See <<Custom Field Storage>> for more details.

These will be stored in the normal storage location for <<Field Extensions>>.

If you use <<Configurable Types>> for an RMA object, you might have a field that the uses
<<Flex Types>> that lets the customer define their own data fields.  The RMA domain object
might look like this:

[source,groovy]
.Example Flex Type Domain
----
class RMA {
  String rma
  String product
  BigDecimal qty
  Date returnDate
  FlexType rmaType  <.>

  @Nullable
  @ExtensibleFieldHolder  <.>
  @MappedProperty(type = DataType.JSON)
  String fields

}

----
<.> The field `rmaType` will hold the reference to the appropriate flex type.  The actual
    values will be stored as described in <<Custom Field Storage>>.
<.> Defines the column that will hold the JSON values of the custom fields.

The API format for this type of data field would be:

[source,json]
.JSON Format for Configurable Type Fields
----
{
  "rma": "R10102-23",
  "qty": 12.2,
  "_fields": {                  <.>
    "retailerID": "ACME-101",
    "returnCode": "DEFECTIVE"
  }
}
----
<.> The fields are stored with the <<Custom Field Storage>> location
    (`fields` in this example).


NOTE: <<Custom Child List>> will use the API format described in
      <<Custom Child List Storage>>.  This follows the normal JSON array format, but
      the element is stored at the top-level, under the name of the custom field.

Updates are allowed for the `_fields` element, but the `_config` element
(<<Custom Field Storage>>) are ignored.

===== Custom Fields - Provide Type via CRUD API

Creations and updates via the <<Rest API>> can define the field type on creation.
This is normally not needed for the normal JSON field types (string, number, boolean).
For example, if you need to create a custom field that is a DateOnly
type, you can specify the field type in the JSON.  The format is identical to the
<<Custom Field Storage>> format. You can create these types using the JSON below:

[source,json]
.JSON Format - Types for Custom Fields
----
{
  "rma": "R10102-23",
  "qty": 12.2,
  "_fields": {
    "dueDate": "2021-01-31",   <.>
    "_config": {               
      "dueDate": {
        "type": "D",           <.>
        "tracking": "ALL"        <.>
      }
    },
  }
}
----
<.> The value for the `dueDate` custom field.  ISO Date formatted string.
<.> The custom field type.  This type is defined as the DB value in <<Field Types>>.
<.> The history tracking option.  See <<Custom Field History>> for details.

NOTE: Any changes to the type are not allowed on existing fields.
      The update will fail if the type is changed.

