
==== API Actions - Non-CRUD

The framework supports many types of API calls that are not related to Create, Read, Update, Delete
(CRUD) actions. These follow the general REST approach, but primarily use the HTTP `POST` method.
These APIs also do not use the HTTP URL to identify the objects being processed in most cases.
The HTTP request content is assumed to be JSON and it will contain the objects to be processed.

These types of API calls are always implemented as a normal Service that is exposed by a controller.
You must implement a controller associated with the service and provides the REST-style HTTP access.
Internal programs running within the application server should use
the service directly.  The HTTP API is only intended for access from external clients
(GUIs, machines, etc).

An example of this service might be an Order `charge()` method.  This method might charge the
customer's credit card for the given order.  The JSON content is a POGO that the controller knows how
to process.

To perform this charge, the following request is used:

*url:* `/order/charge`  _(POST)_

[source,json]
.JSON ChargeRequest
----
{
  "order": "10102-23",
  "total": 50.00
}
----

[source,groovy]
.POGO for Request Object
----
package orders

Class ChargeRequest {
  Order order  // <1>
  BigDecimal total
}
----
<1> A reference to a domain class by key (Order).  See <<references-to-domain-objects>> for details.

[source,groovy]
.Controller Logic For POGO-Based APIs
----
@Secured("ADMIN")
@Controller("/chargeAPI")
class ChargeController {
  def orderService  // <1>

  @Post(value = "/charge")
  ChargeResponse charge(@Body ChargeRequest chargeRequest, @Nullable Principal principal) {  // <2>
    return orderService.charge(chargeRequest)       // <3>
  }

}
----
<1> The `OrderService` will handle this request.  It is injected by Micronaut here.
<2> The content will be parsed into our POGO _ChargeRequest_ by Micronaut.
<3> The `OrderService.charge()` method will process the request and return a POGO as the results.


==== API Error Handling

Exceptions encountered during these CRUD and other service calls will be returned to the caller.
When the REST-style API is used over HTTP, any exception
will be returned in a standardized JSON an HTTP 'bad' response code (typically 400).
In most cases an error code will also be part of the response.  Below, the code 1001 refers to an
error message in the standard _messages.properties_ file.
An example error response is shown below:

[source,json]
.JSON Error Response
----
{"message":
  {"level": "error",
   "text":"Order 'M1657334' cannot be worked.  Status='Done'",
   "code":"1001"}
}
----

Most errors will be triggered as an exception.  The exception's `toString()`
method is typically used to get the displayable error message string.


Multiple messages and other levels can be returned by other controller methods as described in
<<reference.adoc#responses,Responses>>.

To return these responses consistently, you can use the
link:groovydoc/org/simplemes/eframe/controller/BaseController.html[BaseController^]
icon:share-square-o[role="link-blue"].  This base class adds a standard Micronaut `error()` method
for the controller.

[source,groovy]
.Controller Error Handling
----
@Secured("ADMIN")
@Controller("/charge")
class ChargeController extends BaseController {  // <1>
 . . .
}
----
<1> All exceptions will be handled consistently and returned to the caller as an error response.


