
[[dashboard-complete-activity]]
==== Complete Activity

*uri:* `/work/completeActivity`

This Complete activity is a
link:{eframe-path}/guide.html#dashboard-activity-non-gui[Non-GUI Activity^] icon:share-square[role="link-blue"].
This means it normally does not display a GUI and just performs the complete action.
This activity works with the
link:groovydoc/org/simplemes/mes/demand/controller/WorkController.html[WorkController^] icon:share-square[role="link-blue"]
`complete()` method to perform the action.

The complete activity uses the Order/LSN parameter from the <<Work Center Selection>>
activity and attempts to complete the work on it.  The Order/LSN is passed to the
`complete()` method in the `barcode` field in the
link:groovydoc/org/simplemes/mes/demand/CompleteRequest.html[CompleteRequest^] icon:share-square[role="link-blue"].
Any errors are displayed in the dashboard's message area.


===== GUI Events

This activity will trigger these GUI events:

* <<ORDER_LSN_STATUS_CHANGED>> -  Sent when the order/LSN is complete.

===== Provided Parameters Used

This activity uses the
link:{eframe-path}/guide.html#dashboard-provide-parameters[parameters provided^] icon:share-square[role="link-blue"]
by other activities:

* order -  The order/LSN from the input field (typically from the <<Work Center Selection>>
           activity).
