

=== Scan Actions

ifeval::["{backend}" != "pdf"]

[inline-toc]#<<ButtonPressAction>>#
[inline-toc]#<<OrderLSNChangeAction>>#
[inline-toc]#<<RefreshOrderStatusAction>>#

endif::[]

The actions triggered by the scan processing in the
link:groovydoc/org/simplemes/mes/system/service/ScanService.html[ScanService^] icon:share-square[role="link-blue"].
A scan action is used to tell the client to execute a specific client-side action due
to some processing on the server.  This includes actions such as pressing a button in
the GUI, refreshing due to status changes and
to indicate what order/LSN was scanned.

These actions are generally published as a dashboard event so all activities can
receive these actions. In general, the scan dashboard will handle these action requests.
See
link:{eframe-path}/guide.html#dashboard-events[Dashboard Events^] icon:share-square-o[role="link-blue"]
for an overview.

NOTE: These actions may be related to similarly name dashboard events.  For example,
      the <<OrderLSNChangeAction>> will likely trigger the <<ORDER_LSN_CHANGED>> event
      after the change has happened on the dashboard.

==== ButtonPressAction

The link:groovydoc/org/simplemes/mes/system/ButtonPressAction.html[ButtonPressAction^] icon:share-square-o[role="link-blue"]
action tells the client dashboard to press a configured dashboard button.
This is generally triggered by a scan of an encoded button ID.  The internal format is:

  ^BTN^START

This barcode prefix (_BTN_) is used to tell the client to press a button.  This is used to avoid
keyboard/mouse input in a scan-oriented dashboard. See
link:guide.html#barcode-formats[Barcode Formats^] icon:share-square-o[role="link-blue"]
for more details on general formats.

===== Scan Action Properties

The main properties of the scan action are:

* `type` - _BUTTON_PRESS_
* `button` - The button ID.

NOTE: There is a special button ID __UNDO_ that will trigger the undo action.  This is not a true dashboard configured
      button, but it works the same.


==== OrderLSNChangeAction

The link:groovydoc/org/simplemes/mes/system/OrderLSNChangeAction.html[OrderLSNChangeAction^] icon:share-square-o[role="link-blue"]
is used to notify the client that the current order/LSN needs to be changed in the client.
This is used when an order/LSN is scanned should be the 'current' order to be processed in the client.

===== Scan Action Properties

The main properties of the scan action are:

* `type` - _ORDER_LSN_CHANGED_
* `order` - The new order.
* `lsn` - The new LSN (optional).
* `qtyInQueue` - The qty in queue after processing.
* `qtyInWork` - The qty in work after processing.

==== RefreshOrderStatusAction

The link:groovydoc/org/simplemes/mes/system/RefreshOrderStatusAction.html[RefreshOrderStatusAction^] icon:share-square-o[role="link-blue"]
is used to notify the client that the status of an order has changed.  Typically, this is used by specific
dashboard activities to refresh the displayed status of the current order.

===== Scan Action Properties

The main properties of the scan action are:

* `type` - _REFRESH_ORDER_STATUS_
* `order` - The order ID of the order that has a changed status.

