=== Scan Dashboard Optional Methods

Some special-purpose dashboards use optional methods in some activities to coordinate
between those activities and the server.   For example, the
link:guide.html#scan-dashboard[Scan Dashboard^] icon:share-square-o[role="link-blue"]
will work with the main scan dashboard _display.ftl_
activity to pass the 'current' order/LSN to the server for processing of the scan.
This is done through the `providedScanParameters()` mechanism.

==== Provided Scan Parameters

The link:guide.html#scan-dashboard[Scan Dashboard^] icon:share-square-o[role="link-blue"]
uses a main display page to hold the current state of the GUI. The current order/LSN is
passed to the server along with the scanned barcode for processing. This is done by
implementing an optional method in the _display.ftl_ page that returns the current
order and/or LSN. These will then be added to the
link:groovydoc/org/simplemes/mes/system/ScanRequest.html[ScanRequest^] icon:share-square-o[role="link-blue"]
as sent to the server.

You will probably not need to implement this method, but it is available for other
modules to use if needed.
In the _display.ftl_, this is how the method is implemented.

An example:

[source,groovy,linenums]
.Example .ftl activity with provideScanParametersX()
----
<script>
  ${params._variable}.provideScanParameters = function(event) {  // <.>
    return {
      order: $('#order').val(),  // <.>
    }
  }
</script>
----
<.> The `provideScanParameters()` method (unique to each panel, so the `params._variable`
    variable is used to make the name unique.  This also makes it available in the
    global javascript name space for the dashboard to access.
<.> Grabs the current value of the input field an returns it in a javascript object.

