[[dashboard-event-reference]]
=== Dashboard Events


This section will describe the dashboard events provided for the MES dashboards.
These events allow the activities to work together to provide a simple looking GUI that
reduces the effort to get things done. See framework
link:{eframe-path}/guide.html#dashboard-api[Dashboard API^] icon:share-square-o[role="link-blue"]
for an overview of events and example event handlers.



==== ORDER_LSN_CHANGED

This event is triggered when the user changes the Order/LSN in the
<<guide.adoc#dashboard-work-center-selection,Work Center Selection>> activity.
This event can be used to synchronize all activities with the currently selected
order/LSNs.

This is typically used by many activities to update their display for the new selection.

===== Event Properties

The main properties of the event are:

* `type` - _'ORDER_LSN_CHANGED'_.
* `source` - The source of the event.  Usually the name of the dashboard activity
  (e.g. 'workCenterSelection').
* `list` - The list of selected orders and/or LSNs.
** `order` - The selected order from the list. (*String*)
** `orderID` - The selected order's ID from the list. (*Number*)
** `lsn` - The selected LSN.  Might be undefined. (*String*)
** `lsnID` - The selected LSN's ID.  Might be undefined. (*Number*)
** `operationSequence` - The selected row's operation sequence.  Only populated from
   _WORK_LIST_SELECTED_.  (*Number*)
** `product` - The product the Order/LSN represents.   Only populated from
   _WORK_LIST_SELECTED_. (*String*)
** `productID` - The product's ID.   Only populated from _WORK_LIST_SELECTED_.
   (*Number*)
** `qtyInQueue` - The quantity in queue.  Only populated from _WORK_LIST_SELECTED_.
   (*Number*)
** `qtyInWork` - The quantity in work.   Only populated from _WORK_LIST_SELECTED_.
   (*Number*)

This event can be triggered by user input to the field or when the _WORK_LIST_SELECTED_
is received.  Not all fields are populated when triggered by the user input.  

===== Event Sources

This event can be triggered by these activities:

* <<Work Center Selection>>.



==== ORDER_LSN_STATUS_CHANGED

This event is triggered when the status of an Order/LSN is changed.
This event can be used to update the status displayed by other activities.

===== Event Properties

The main properties of the event are:

* `type` - _'ORDER_LSN_STATUS_CHANGED'_.
* `source` - The source of the event.  Usually the name of the dashboard activity
  (e.g. 'startActivity').
* `list` - The list of orders and/or LSNs that changed their status.
** `order` - The order with the status change. (*String*)
** `lsn` - The LSN with the status change.  (*String: Optional*)

===== Event Sources

This event can be triggered by these activities:

* <<Start Activity>>.
* <<Complete Activity>>.
* <<Reverse Start Activity>>.


==== WORK_CENTER_CHANGED

This event is triggered when the work center
<<guide.adoc#dashboard-work-center-selection,Work Center Selection>> activity is changed.
This event is be used to synchronize all activities with the currently selected
order/LSNs.

This is typically used by many activities to update their display for the new selection.

===== Event Properties

The main properties of the event are:

* `type` - _'WORK_CENTER_CHANGED'_.
* `source` - The source of the event.  Usually the name of the dashboard activity
  (e.g. 'workCenterSelection').
* `workCenter` - The new work center (*String*).

===== Event Sources

This event can be triggered by these activities:

* <<Work Center Selection>>.



==== WORK_LIST_SELECTED

This event is triggered when the user changes the work selection changes in the
<<Work List>> activity.  This event can be used to synchronize
all activities with the currently selected order/LSNs.

This is typically used by the <<Work Center Selection>> activity to populate the
Order/LSN field.

===== Event Properties

The main properties of the event are:

* `type` - _'WORK_LIST_SELECTED'_.
* `source` - The source of the event.  Usually the name of the dashboard activity
  (e.g. 'workList').
* `list` - The list of selected elements.
** `order` - The selected order from the list. (*String*)
** `orderID` - The selected order's ID from the list. (*Number*)
** `lsn` - The selected LSN.  Might be undefined. (*String*)
** `lsnID` - The selected LSN's ID.  Might be undefined. (*Number*)
** `operationSequence` - The selected row's operation sequence.  Might be undefined.
   (*Number*)
** `product` - The product the Order/LSN represents.  Might be undefined. (*String*)
** `productID` - The product's ID.  Might be undefined. (*Number*)
** `qtyInQueue` - The quantity in queue.  (*Number*)
** `qtyInWork` - The quantity in work.  (*Number*)

===== Event Sources

This event can be triggered by these activities:

* <<Work List>>.

