
[[dashboard-reverse-complete-activity]]
==== Reverse Complete Activity

*uri:* `/work/reverseCompleteActivity`

This Reverse Complete activity is a
link:{eframe-path}/guide.html#dashboard-activity-non-gui[Non-GUI Activity^] icon:share-square[role="link-blue"].
This means it normally does not display a GUI and just performs the complete action.
This activity works with the
link:groovydoc/org/simplemes/mes/demand/controller/WorkController.html[WorkController^] icon:share-square[role="link-blue"]
`reverseComplete()` method to perform the action.

The reverse complete activity can use the Order/LSN parameter from the <<Work Center Selection>>
activity and attempts to reverse a previous complete on it.  The Order/LSN is passed to the
`reverseComplete()` method in the `barcode` field in the
link:groovydoc/org/simplemes/mes/demand/CompleteRequest.html[CompleteRequest^] icon:share-square[role="link-blue"].
Any errors are displayed in the dashboard's message area.

This reverse action will mark the Order/LSN as not done and issue a negative <<ProductionLog>>
record. This action also places the Qty back in queue.  It does not perform a start on the
qty.

This activity is also used to as an Undo action for the <<Start Activity>>.

===== GUI Events

This activity will trigger these GUI events:

* <<ORDER_LSN_STATUS_CHANGED>> -  Sent when the order/LSN complete is reversed.


===== Provided Parameters Used

This activity uses the
link:{eframe-path}/guide.html#dashboard-provide-parameters[parameters provided^] icon:share-square[role="link-blue"]
by other activities:

* order -  The order/LSN from the input field (typically from the
           <<Work Center Selection>> activity).
