[[order-assembled-component-guide]]
=== Order Assembled Component

Defines a single component assembled into an order (and optionally an LSN).
This includes a 'location' mechanism to track where the component was loaded from on the work center setup.
This location can be a bin, shelf or automated feeder location.
These are stored in the <<reference.adoc#order-assembled-component,OrderAssembledComponent>> domain class.

This object records the long-term component history, so there are no real primary keys for the
record.  No records are deleted from this table (except during order archive or other order delete
scenarios).
A unique sequence is assigned to each record added.

The component's history is tracked using assembly data (e.g. the supplier, lot code, date code, etc)
provided by the operators.  This assembly data is stored in a
<<{eframe-path}/guide.adoc#flexible-fields,Flexible Field>> based on the `assemblyData` Flex Type.
This means the actual assembly data is stored in XML in the field `assemblyDataValues`.
This allows the GUIs to collect configurable data from your operators without forcing any database
or other customizations.


=== Order/LSN/Component Relationship

This component history is associated with an Order and optionally with an LSN.  This means you can
track component usage at the order level or at a lower level for the individually unit or lot (LSN).

//workaround for https://github.com/asciidoctor/asciidoctor-pdf/issues/271
:imagesdir: {imagesdir-build}

[ditaa,"orderLsnComponentRelationship"]
----
+------------------+
|      Order       |
|                  |                     +--------------------------+
|             cGRE +=====================+OrderAssembledComponent   |
+-------+----------+                     |   Order   cGRE           |
        | Has Optional LSNs              |   LSN (optional)         |
        |       +------------+           +-------+------------------+
        +-------+ LSNs  cGRE |                   |
                |            +===================+
                +------------+     Can have component for LSN

----

//end workaround for https://github.com/asciidoctor/asciidoctor-pdf/issues/271
:imagesdir: {imagesdir-src}

The OrderAssembledComponent domain is loosely linked to an Order and an optional LSN.  This means component
can be assembled as a lot assembled into a lot, or a serailized component assembled into a
specific unit (LSN).


==== Archiving

This object is archived when the parent order is archived.
