[[order-bom-component-guide]]
=== Order BOM Component

Most orders will be built with components of some sort.  The required components are pre-defined
in the link:{mes-core-path}/guide.html#product[Product^] icon:share-square-o[role="link-blue"].
These are copied to the order upon release so each order has its own specific list of components
required.  These are stored in the
link:reference.html#order-bom-component[OrderBOMComponent^]
icon:share-square-o[role="link-blue"] domain class.

The <<order-assembled-component-guide>> tracks the actual components assembled into the order.
This includes optional details on the source of the components (e.g. vendor and lot).

This element informally belongs to the MES Core
link:{mes-core-path}/guide.html#order[Order^] icon:share-square-o[role="link-blue"]
parent.  Since the Order is in another module, the normal child relationship notation can't
be used. Instead, this module maintains the relationship between the component and order records.
It also provides an archive mechanism to keep the component requirement data long term.


==== Archiving

This object is archived when the parent order is archived.
