=== Architecture

The framework supports an the following architecture:


//workaround for https://github.com/asciidoctor/asciidoctor-pdf/issues/271  and IDEA plugin dir issue
:imagesdir: {imagesdir-build}
ifeval::[{env}==idea]
:imagesdir-build: .asciidoctor
:imagesdir: .asciidoctor
endif::[]

.Architecture Layers
[ditaa,"architectureLayers"]
----
+------------------------------+
| Application (Deployable JAR) |
| o Customized GUIs       cGRE |
| o Customized Business Logic  |
+------------------------------+
| Custom Module                |
|                              |
|                         cYEL |
+---------------+--------------+
|  App Module1  |  App Module2 |
|          cBLU |         cBLU |
+---------------+--------------+
|   Application Core Module    |
|                         cBLU |
+------------------------------+
| Enterprise Framework Module  |
| o  GUI Helpers               |
| o  Extension Support         |
+------------------------------+
| Micronaut                    |
| o  Micronaut Data            |        +----------+
| o  Netty HTTP Server         |--------|{s}       |
+------------------------------+        | Database |
                                        |          |
                                        +----------+

----

//end workaround for https://github.com/asciidoctor/asciidoctor-pdf/issues/271
:imagesdir: {imagesdir-src}

The goal of this architecture is to allow you (as the application developer) to modularize your
application into multiple modules (Core module, Module1 and Module2 above).
In addition, custom modules can be added to the build to add new features to your applications.
Other organizations (integrators, end-users, etc) may want to mix and match various modules.
These organizations may even remove optional modules of your application.

This is made possible with Micronaut's bean framework.  New beans are easily added in the modules.
Add-on functional behavior are also possible using Micronaut's ability to define multiple
beans for a specific feature.  For example, each module can provide custom fields  on the core
module domains and GUIs by implementing a bean with the AddOnFieldsInterface.  The framework will
use these add-on fields as if they are part of the core module.

An example extension module for the OrderService is shown below:

//workaround for https://github.com/asciidoctor/asciidoctor-pdf/issues/271  and IDEA plugin dir issue
:imagesdir: {imagesdir-build}
ifeval::[{env}==idea]
:imagesdir-build: .asciidoctor
:imagesdir: .asciidoctor
endif::[]


.Extension Example
[plantuml,"OrderExtensionFlow",align="center"]
----
@startuml
actor user #red
user -> GUI: release
GUI -> OrderController: release()
participant "Order\nController" as OrderController
participant "Order\nService" as OrderService
OrderController -> OrderService: release()
participant "Module1OrderExt\nImpl of OrderReleasedInterface" as Module1OrderRelease
OrderService -> Module1OrderRelease: orderReleased()

@enduml
----

//end workaround for https://github.com/asciidoctor/asciidoctor-pdf/issues/271
:imagesdir: {imagesdir-src}


In this example, a core `OrderService.release()` method will call all registered
beans that implement the _OrderReleasedInterface_.  This interface has the method
`orderReleased()`, which notifies the Module (Module1) that an order is released.

These extension methods can perform database actions and even rollback the transaction as
needed.

==== Why Groovy?

Why choose Groovy over Java or Kotlin?  One simple reason: clarity.

The biggest cost of successful software is the cost of maintaining the code for years or
decades after you have written it.  Clarity becomes critical when looking at code that
was written a long time ago.  For that reason, all decisions on this framework
and application are driven by the need to appear simple to the user and to
minimize the complexity for the application developer.

Groovy is clearer because:

* Reduced boiler-plate code.
* Reduction in if nesting due to the null-safe access to methods/properties.
* The default value operator ?: .
* List and Map usage simplifications.
* The excellent link:http://spockframework.org/spock/docs/1.3/index.html[Spock^] test system
* Easy ability to modify the byte-code at compile time to add features
  (see <<Domain Entities>>).
* Many other features.  See
  link:https://dev.to/jcoelho/10-reasons-to-use-groovy-in-2019-431f[10 Reasons].
* Null safe equality.
* No need for checked exceptions on methods.

We don't want to write a 10 page summary of why Groovy is clearer, but here is a short
example using a pattern often seen in application code.  We need to call methods
on a nested set of objects that may return null.

[source,groovy]
.Example - Domain Entity - Groovy
----
  def routing = order?.product?.determineEffectiveRouting() ?: defaultRouting
----


[source,java]
.Example - Domain Entity - Java
----
  Routing routing = defaultRouting;
  if (order != null) {
    if (order.getProduct() != null) {
      if (order.getProduct.determineEffectiveRouting() != null) {
        routing = order.getProduct.determineEffectiveRouting()
      }
    }
  }

----

Using just two Groovy features reduces the code complexity significantly.  Later versions
of Java help in some areas (e.g. use of *var*), but the overall code clarity still suffers
in Java (see Streams).

One caveat: Groovy has some terse and cryptic syntax.  We have chosen to avoid those
types of features that are not clear to the user.  Features such as method pointers
are wonderfully short, but not very clear.  See <<Groovy Features to Use or Avoid>> for
details.

