=== Architecture

The framework supports an the following architecture:


//workaround for https://github.com/asciidoctor/asciidoctor-pdf/issues/271  and IDEA plugin dir issue
:imagesdir: {imagesdir-build}
ifeval::[{env}==idea]
:imagesdir-build: .asciidoctor
:imagesdir: .asciidoctor
endif::[]

.Architecture Layers
[ditaa,"architectureLayers"]
----
+------------------------------+
| Application (Deployable JAR) |
| o Customized GUIs       cGRE |
| o Customized Business Logic  |
+------------------------------+
| Custom Module                |
|                              |
|                         cYEL |
+---------------+--------------+
|  App Module1  |  App Module2 |
|          cBLU |         cBLU |
+---------------+--------------+
|   Application Core Module    |
|                         cBLU |
+------------------------------+
| Enterprise Framework Module  |
| o  GUI Helpers               |
| o  Extension Support         |
+------------------------------+
| Micronaut                    |
| o  Micronaut Data            |        +----------+
| o  Netty HTTP Server         |--------|{s}       |
+------------------------------+        | Database |
                                        |          |
                                        +----------+

----

//end workaround for https://github.com/asciidoctor/asciidoctor-pdf/issues/271
:imagesdir: {imagesdir-src}

The goal of this architecture is to allow you (as the application developer) to modularize your
application into multiple modules (Core module, Module1 and Module2 above).
In addition, custom modules can be added to the build to add new features to your applications.
Other organizations (integrators, end-users, etc) may want to mix and match various modules.
These organizations may even remove optional modules of your application.

This is made possible with Micronaut's bean framework.  New beans are easily added in the modules.
Add-on functional behavior are also possible using Micronaut's ability to define multiple
beans for a specific feature.  For example, each module can provide custom fields  on the core
module domains and GUIs by implementing a bean with the AddOnFieldsInterface.  The framework will
use these add-on fields as if they are part of the core module.

An example extension module for the OrderService is shown below:

//workaround for https://github.com/asciidoctor/asciidoctor-pdf/issues/271  and IDEA plugin dir issue
:imagesdir: {imagesdir-build}
ifeval::[{env}==idea]
:imagesdir-build: .asciidoctor
:imagesdir: .asciidoctor
endif::[]


.Extension Example
[plantuml,"OrderExtensionFlow",align="center"]
----
@startuml
actor user #red
user -> GUI: release
GUI -> OrderController: release()
participant "Order\nController" as OrderController
participant "Order\nService" as OrderService
OrderController -> OrderService: release()
participant "Module1OrderExt\nImpl of OrderReleasedInterface" as Module1OrderRelease
OrderService -> Module1OrderRelease: orderReleased()

@enduml
----

//end workaround for https://github.com/asciidoctor/asciidoctor-pdf/issues/271
:imagesdir: {imagesdir-src}


In this example, a core `OrderService.release()` method will call all registered
beans that implement the _OrderReleasedInterface_.  This interface has the method
`orderReleased()`, which notifies the Module (Module1) that an order is released.

These extension methods can perform database actions and even rollback the transaction as
needed.
