=== efButtonGroup

ifeval::["{backend}" != "pdf"]

[inline-toc]#<<ef-button-group-parameters>>#
[inline-toc]#<<Button Group Examples>>#

endif::[]


The link:guide.html#efbuttongroup[efButtonGroup^] icon:share-square-o[role="link-blue"] marker
is used to build a horizontal group of buttons with reasonable spacing.

For an overview, see link:guide.html#efbuttongroup[efButtonGroup^] icon:share-square-o[role="link-blue"].
For more details, see the groovydoc
link:groovydoc/org/simplemes/eframe/web/ui/webix/freemarker/ButtonGroupMarker.html[ButtonGroupMarker^]
icon:share-square-o[role="link-blue"].

This `efButtonGroup` marker can only be used with the <<efButton>> marker.



[[ef-button-group-parameters]]
==== Parameters/Body

The main parameters/body supported are:

.Parameters
[cols="1,6"]
|===
|Argument|Description

| *(body)*| The button contents. Only <<efButton>> markers are allowed.

|===



==== Button Group Examples

===== Simple Button Group

This example provides a simple change password form with 'change' and cancel buttons in
group.

[source,html]
.Example - Update Password
----
<script>
function changeFormSubmit() {  // <.>
  ef.submitForm('formName', '/user/changePassword'); // <.>
};
</script>

<@efForm id="changeForm">
  <@efField field="User.userName" value="joe"/>
  <@efField field="User.password" id="passwordOld" required="true" fieldType="password"/>
  <@efField field="User.password" id="passwordNew" required="true" fieldType="password"/>
  <@efField field="User.password" id="passwordConfirm" required="true" fieldType="password"/>
  <@efButtonGroup>
    <@efButton label="changePassword.label" click="changeFormSubmit()"/>
    <@efButton label="cancel.label" click="cancel();"/>
  </@efButtonGroup>
<@/efForm>
----
<.> The function to submit a form.  See <<efForm>> for more details on how to submit
    a non-standard form.






