=== efDefinitionList

ifeval::["{backend}" != "pdf"]

[inline-toc]#<<ef-definition-list-parameters>>#
[inline-toc]#<<ef-definition-list-requirements>>#

endif::[]



The link:guide.html#efDefinitionList[efDefinitionList^] icon:share-square-o[role="link-blue"] marker
is used to build a definition list page with one or more columns of data.
By default, the row values are found by a controller `list()` method using the json format.

For an overview, see link:guide.html#efDefinitionList[efDefinitionList^] icon:share-square-o[role="link-blue"].
See the groovydoc
link:groovydoc/org/simplemes/eframe/web/ui/webix/freemarker/ListMarker.html[ListMarker^]
icon:share-square-o[role="link-blue"] for additional details.


See <<guide.adoc#markers,Markers>> for common features of markers such as Pagination, Filtering
and Sorting. See <<guide.adoc#controllers,Controllers>> for details on helper classes that
can provide the `list()` method logic for you.

This marker relies on the common
link:groovydoc/org/simplemes/eframe/web/ui/webix/widget/ListWidget.html[ListWidget^]
icon:share-square-o[role="link-blue"] to implement most of the list features.



[source,html]
.efDefinitionList Example - Display a List of Orders
----
<@efDefinitionList columns="order,product,qtyToBuild,qtyDone,dateCompleted"/>
----



[[ef-definition-list-parameters]]
==== Parameters/Body

The main parameters/body supported are:

.Parameters
[cols="1,6"]
|===
|Argument|Description

|*(body)*    |Ignored.
| *columns*  | A comma-delimited list of columns to display
              (*Default:* The list from the domain's <<fieldOrder>>).
|*height*    | The height of the definition list (*Default:* '74%').
|*paddingX*  | The width of extra horizontal padding (*e.g.:* '74%' or '20em').
|*pageSize*  | The number of rows to show in a single page (*Default:* 10).

|===



This marker also supports most of the
link:groovydoc/org/simplemes/eframe/web/ui/webix/widget/ListWidget.html[ListWidget^]
icon:share-square-o[role="link-blue"] options to control the list display,
This includes default widths, specific links needed, etc.

NOTE: This marker assumes the controller serving up this page is the same used for the
      edit/create/show/delete actions.


[[ef-definition-list-requirements]]
==== Requirements

* The controller must implement a standard `list()` method that supports *json* format
  and structures the output with two top-level elements:
** `total_count` - The total number of rows available (integer).
** `data` - The actual list data (an array of each row's values).
* One or more key fields are defined in your domain class. See
  link:guide.html#domains[Domains^] icon:share-square-o[role="link-blue"].
* The columns have standard labels defined in _messages.properties_.
  See link:guide.html#internationalization[Internationalization^] icon:share-square-o[role="link-blue"].
* The main domain class (if found) has a standard label defined in _messages.properties_.
* The domain classes for child and foreign key references have
  link:guide.html#key-fields[Key Fields^] icon:share-square-o[role="link-blue"]
  defined for the top-level domain object.

NOTE: Any sub-object references in the list of columns will be ignored (not displayed).  This includes
column references such as _flexType.fields_.




