=== efField

ifeval::["{backend}" != "pdf"]

[inline-toc]#<<ef-field-parameters>>#
[inline-toc]#<<Field Examples>>#
[inline-toc]#<<Inline Grid>>#

endif::[]


The link:guide.html#effield[efField^] icon:share-square-o[role="link-blue"] marker
is used to build a field suitable for submitting to the server.
This field marker currently must be used inside of an <<efForm>> marker.

For an overview, see link:guide.html#effield[efField^] icon:share-square-o[role="link-blue"].
For more details, see the groovydoc
link:groovydoc/org/simplemes/eframe/web/ui/webix/freemarker/FieldMarker.html[FieldMarker^]
icon:share-square-o[role="link-blue"] or
link:groovydoc/org/simplemes/eframe/web/ui/webix/widget/TextFieldWidget.html[TextFieldWidget^]
icon:share-square-o[role="link-blue"].


NOTE: If this field is used inside of a standard edit/create/show definition page, then
      you must used the 'after' option below.

[[ef-field-parameters]]
==== Parameters/Body

The main parameters/body supported are:

.Parameters
[cols="1,6"]
|===
|Argument|Description

| *(body)*| If given, then this is placed to the right of the field  Supports <<efButton>>.
| *id*    | The ID/Name of the field.  Must be set to support submitting from the <<efForm>>.
| *field* | The field to display.  Can contain the domain class's short name as a model
            (e.g. _'Order.qty'_). *(Required)*
| *label* | The label for the field. Looked up in the .properties file, if possible.
            If blank (""), then the label will not be displayed. (*Default:* `fieldName`+'.label')
| *required* | If 'true', then the field is flagged as required (*Default:* 'false')
| *type*  | The input field type (e.g. _'password'_ or _'password-no-auto'_).
            _'password-no-auto'_ will prevent the browser from auto-completing the password.
            This is useful when the admin user is creating User records.
| *value* | The initial value for the field.  Ignored if *modelName* is given.
| *modelName* | The name of the element in the display model that holds the value object.
                This is typically used with
                link:guide.html#configurable-types[Configurable Types^] icon:share-square-o[role="link-blue"]
                such as
                link:guide.html#flex-types[Flex Types^] icon:share-square-o[role="link-blue"].
                See the example <<FlexType Field with efField>>.
| *_combo@readOnly* | Special case setting for
                      link:guide.html#configurable-types[Configurable Types^] icon:share-square-o[role="link-blue"]
                      combo-box.  This prevents
                      changes to the setting, but allows the user to enter values for the
                      configurable fields themselves (e.g. 'returnDate' for the RMA example
                      <<FlexType Field with efField>>).
| *width* | The display width of the field.  This overrides the normal display width, which is
            based on the max field length.  Width can be a number (characters), em units ('20em')
            or percent ('15%'). (*Default:* Field's maxLength).
| *maxLength* | The max input field size of the field.  The input field is limited to this
                many characters. This only applies to non-domain
                fields.  *Ignored* for Domain fields.  
                (*Default:* 40 for non-domain fields).
| *after* | The field name to display this after.  Use only inside of edit/create/show fields.
| *onChange* | Javascript to execute when the field changes (on field exit).
               This javascript has two variables available (`newValue`, `oldValue`).
| *readOnly* | If 'true', then this field will be a read-only field.
                (*Default:* false).
|*css* | The css class(es) to add to the field.  Multiple classes are supported, using space as
         a delimiter.
|*attributes* | Any additional HTML attributes to add to the text field element.  Formatted as
                standard Javascript object elements (e.g. 'autocomplete:"username",type:"text"')

|===



////
* `autofocus` - If 'true' or '', then requests focus on the field upon display.  Only one field will receive focus.
* `maxLength` - The maximum length of the input value.  Overrides the domain definition (if any).
                Only applies to simple text fields.
* `fieldContainer` - Overrides the HTML field container class used for this field.  Supported by most fields.
                     (*Default:* _'field-container'_)
* `values` - This defines the list of valid values that the input text field should allow.  This will perform
             auto-completion on the list.  This should be a list of Strings.

===== *Attributes: Text Fields Only*

** `autoComplete` - If 'true', then this field will allow auto-complete, using calls to the server to
                   present the user with possible solutions.  Must be used with a text field
                   and the field must contain the domain that the field belongs to (e.g. _'WorkCenter.workCenter'_).
                   The field should be the key field for the domain object and the associated controller
                   must have the standard <<guide.adoc#list-support,list handler>>.

===== *Attributes: Links and List of Links Only (Inline Grids)*
* `columns` - The list of columns to display in the inline grid. Defaults to the fields listed in the domain's
              <<fieldOrder>> variable.
* `summary` - Allows you to specify the summary text for a sub-list of domain classes.  This is shown as a collapsible
              list of child records with a summary.  You can override the default summary with this entry.
              See <<ef-edit>>) for an example.
* `inlineGrid` - If 'true', uses an inline grid for the child list.  See below.
* `showMainConfigTypeField` - If 'false', then the configurable type main field is shown.  This is the main drop-down
                              field that allows the user to choose a configurable type.
                              See <<guide.adoc#configurable-types,Configurable Types>> for
                              details. (*Default:* 'true')
* `__**column**__Default` - This attribute contains the javascript logic used to default a given `__**column**__` for the
                            inline grid.  See <<ef-edit>>.

NOTE: This marker supports use of the marker body content.  The body content will be written to the page just after
      the input field.  This is supported on the following fields: text, number, boolean, date, date/time
      and selection (combo-boxes).
////




This marker also supports most of the common features mentioned in
link:guide.html#markers-and-options[Markers and Options^] icon:share-square-o[role="link-blue"].
This includes labels and sizes.

NOTE: This marker supports the <<Inline Grid>>.


==== Field Examples

ifeval::["{backend}" != "pdf"]

[inline-toc]#<<Change Password Example>>#
[inline-toc]#<<Add Field to Definition Page>>#
[inline-toc]#<<FlexType Field with efField>>#

endif::[]



===== Change Password Example

This example provides a simple change password form with a 'change' button.

[source,html]
.Example - Update Password
----
<@efForm id="changeForm">
  <@efField field="User.userName" value="joe"/>
  <@efField field="User.password" id="passwordOld" required="true" fieldType="password"/>
  <@efField field="User.password" id="passwordNew" required="true" fieldType="password"/>
  <@efField field="User.password" id="passwordConfirm" required="true" fieldType="password"/>
  <@efButton id="change" label="changePassword.label" click="changeFormSubmit()"/>
<@/efForm>
----

===== Add Field to Definition Page

This example shows how to add two fields to the create user page.  These allow the entry of a
user password with confirmation.

[source,html]
.Example - Add Fields to Create Page
----
<@efForm id="create">
  <@efCreate xyz="PDQ"/>
  <@efField field="User.password" id="password1" type="password" afterField="roles"/>
  <@efField field="User.password" id="password2" type="password" afterField="password1"/>
<@/efForm>
----


===== FlexType Field with efField

This example shows how to use a
link:guide.html#flex-types[Flex Type^] icon:share-square-o[role="link-blue"] field in a GUI.
This is one of the framework's
link:guide.html#configurable-types[Configurable Types^] icon:share-square-o[role="link-blue"].

When the user changes the selected flex type, the input fields change and allows the user to
enter different data. The data is stored in the custom field holder for the object.

[source,html]
.Example - FlexType Field with efField with Configurable Types - GUI
----
<@efForm id="logRMA">
  <@efField field="RMA.rmaType" id="rmaType" modelName="rmaDataModel"/>  // <.>
<@/efForm>
----
<.> This expects the object to hold the values in the (`rmaDataModel`) in the model.  This
    is normally set by the controller (see below).

The controller can set the value in the model using this logic:

[source,groovy]
.Example - FlexType Field with efField with Configurable Types - Controller
----
StandardModelAndView logRMADialog(HttpRequest request, @Nullable Principal principal) {
  def view = "rma/logRMADialog"
  def modelAndView = new StandardModelAndView(view, principal, this)

     . . .

  def defaultRMA = new RMA(rmaType: flexType) // <.>
  defaultRMA.setRmaTypeValue('returnDate', new Date())
  
  modelAndView['rmaDataModel'] = defaultRMA   // <.>

  return modelAndView
}
----
<.> An RMA object is used as the default values for the displayed field.
    The field values can be set too.
<.> The `rmaDataModel` is set using the given object, with a default value (`flexType`).
    The custom field values can also be set in the custom field holder (as marked by the
    _@ExtensibleFieldHolder_ annotation).




