
=== efPreloadMessages

The `efPreloadMessages` marker is used to pre-load localized messages and labels into the javascript
library for later use. This avoids a slow server-request to get the message text when needed on the
client.


==== Parameters/Body

The main parameters/body supported are:

.Parameters
[cols="1,6"]
|===
|Argument|Description

|*codes*| The list of message keys to pre-load on the page.  This is a comma-delimited list of
          keys from the _messages.properties_ file.  *(Required)*

|===

==== Examples

In this example, a simple dialog is displayed with the Ok and Cancel buttons.

The _messages.properties_ has these entries:

[source,groovy]
----
cancel.label=Cancel
ok.label=Ok
----

The HBS page would use the marker `efPreloadMessages` to pre-load the messages for javascript:

[source,html]
----
<@efPreloadMessages codes="ok.label,cancel.label"/>

<script>
  ef.displayDialog({body: 'Some text', buttons: [{label: 'ok.label'},{label: 'cancel.label'}] });
  . . .
</script>
----

The actual lookup takes place with this kind of javascript inside of the <<displayDialog>>
function:

[source,javascript]
----
  var label = ef.lookup('ok.label');
  . . .
----


The example below shows how many messages can be used in one `<@efPreloadMessages>` marker in a more readable format:

[source,html]
.Multiple Codes Example
----
<@efPreloadMessages
    codes="panel.content.label,default.updated.message,dashboard.label,
           dashboard.editor.menu.addHorizontalSplitter.label,
           dashboard.editor.menu.addVerticalSplitter.label,
           dashboard.editor.menu.removePanel.label,
           dashboard.editor.menu.addPanelAfter.label,
           dashboard.editor.menu.addPanelBefore.label,
           error.114.message,error.116.message,error.117.message"
/>
----

In the above examples, the white spaces are ignored.







