
==== Undo

Dashboards provide a simple framework to let the user undo previous actions.  This works with
undo actions that are simple POST of a JSON payload to some server.  A limited number of undo
actions are recorded and the dashboard can have a special button configured to perform the undo.
There is no re-do feature.

To make Undo work with your dashboard <<Dashboard Activities>>, you need to follow some simple rules:

. The API method should take a single POGO as input.
. The API method should return a single or a List of POGOs that implement the
  link:groovydoc/org/simplemes/eframe/web/undo/UndoableInterface.html[UndoableInterface^]
  icon:share-square-o[role="link-blue"].
. The response POGO should provide the
  link:groovydoc/org/simplemes/eframe/web/undo/UndoActionInterface.html[UndoActionInterface^]
  icon:share-square-o[role="link-blue"] needed to undo the previous user request.
. The Undo Action(s) should provide the correct URI and JSON payload to actually undo the action.
. The undo action POGO should be convertible to/from JSON.  See <<json-by-key>> for dealing
  with domain object references.

If you follow these rules, then the dashboard will 'play' them back to undo the action.  The
actions will be submitted to the server in separate requests.

For example, a start action might have this code in the controller/service:

[source,groovy]
.Example - Undoable Start Action
----
List<StartResponse> start(StartRequest request) {     // <.>
  List res = []

  . . .

  res << new StartResponse(order: order, lsn: lsn, qty: qty)   // <.>


  return res
}

----
<.> The service method uses POGOs to operate on.
<.> The _StartResponse_ constructor will generate the URI and JSON needed to undo this 'Start' action.


The POGOs involved in this undo are:

[source,groovy]
.POGOs for Undoable Start Action
----
class StartRequest {
  @JSONByKey
  Order order

  BigDecimal qty = 1.0
}


class StartResponse implements UndoableInterface {

  @JSONByKey
  Order order

  . . .

  List<UndoActionInterface> getUndoActions() {
    def msg = GlobalUtils.lookup('reversedStart.message', order, qty)            //  <.>
    return [new StartUndoAction(order: order, lsn: lsn, qty: qty, infoMsg: msg)] //  <.>
  }

}


class StartUndoAction implements UndoActionInterface {
  . . .

  String getUri() {                         // <.>
    return '/work/undoStart?format=json'
  }

  String getJson() {                        // <.>
    return """ {
      "startRequest": {
        "order": "${order.order}",
        "lsn": "${lsn?.lsn}",
        "qty": qty
      }
    }
    """
  }

  String getInfoMsg() {                     // <.>
    return null
  }

  List<Map> getSuccessEvents() {            // <.>
    return [type: 'ORDER_LSN_STATUS_CHANGED', order: order]
  }

}

----
<.> Defines an optional info message for the undo, when it the undo action is performed.
<.> Provides the undo actions needed to reverse the start.
<.> The _StartUndoAction_ provides the URI and JSON content.
<.> The JSON for the undo POST request.
<.> Provides an optional info message to be displayed after the undo is performed.
    The uri might also provide a standard message response too.
<.> Optional dashboard events to publish after the undo action is performed.
    Typically used to refresh the display.


To make all of this work, you will need a dashboard activity that knows how to handle these undo
action responses.  This is usually done with the standard
link:reference.html#postactivity[postActivity^] icon:share-square-o[role="link-blue"]
dashboard method.  This method detects an undoActions list in the response and registers them
with the dashboard.


