
== Introduction

ifeval::["{backend}" != "pdf"]
[inline-toc]#<<Dependencies>>#
endif::[]


This module provides assembly related functions to the link:{mes-core-path}/guide.html#[Core SimpleMES^]
icon:share-square-o[role="link-blue"] application.  If this module is used with the deployed application,
then users may define Bills of Material (<<product-component-guide>>) and setup <<work-center,WorkCenters>>
to perform assembly when manufacturing products.

This MES is built on the link:{eframe-path}/guide.html#[Enterprise Framework^] icon:share-square-o[role="link-blue"].
Many of the features described here are fully documented by that plugin.


=== Dependencies

This plugin module requires the link:{mes-core-path}/guide.html#[Core SimpleMES^]
icon:share-square-o[role="link-blue"], which in turn requires a number of other plugins, such as the
link:{eframe-path}/guide.html#[Enterprise Framework^] icon:share-square-o[role="link-blue"].

The only dependency you have to include in your _build.gradle_ file is the core module:

[source,groovy]
.Example Gradle Dependency
----
dependencies {

  . . .

  compile "org.simplemes.plugins:mes-core:+"

}
----


This will add any required plugins to your application.


=== Packages

This module works with the core MES module, which is located under the package _org.simplemes.mes_.
To avoid conflicts with other modules, the assembly module is located under the package
_org.simplemes.mes.assy_.

The basic package layout is:

//workaround for https://github.com/asciidoctor/asciidoctor-pdf/issues/271
:imagesdir: {imagesdir-build}

.Assembly Package
[ditaa,"packages"]
----
  +---------------+
  |org        c4CF|
  +---------------+
    +---------------+
    |simplemes  c4CF|
    +---------------+
      +---------------+
      |frame      c6D6|
      +---------------+
      |mes        c6D6|
      +---------------+
        +---------------+
        |assy       cYEL|
        +---------------+
          +---------------+
          |floor      cYEL|
          +---------------+
          |product    cYEL|
          +---------------+

----

//end workaround for https://github.com/asciidoctor/asciidoctor-pdf/issues/271
:imagesdir: {imagesdir-src}

All classes provided by this Assembly module will be under the _org.simplemes.mes.assy_ package.
The packages under this package will mirror the mes core structure (e.g. shop floor extensions will be
in the _floor_ sub-package.  Product extensions will be in the _org.simplemes.mes.assy.product_ package.



=== Module Features

The sections below will give an overview of the main features provided by this module.  The specific
details will be covered in detail in the <<reference.adoc#,reference>> document.
