
== API

ifeval::["{backend}" != "pdf"]

[inline-toc]#<<Stable API>>#
[inline-toc]#<<REST>>#
[inline-toc]#<<Services>>#

endif::[]



The link:groovydoc/index.html[Groovy API^] for the SimpleMES contains details on all fields and methods for most
objects/services.

The API in SimpleMES is based on Groovy/GORM Domain objects and Services.  These are accessed like normal Java/Groovy
classes.  Refer to the http://gorm.grails.org//[GORM^] documentation for general access to the Domain
objects and Services.

The mechanics of accessing the API via HTTP is covered in more detail in the
<<guide.adoc#enterprise-framework,Enterprise Framework>>.


=== Stable API

Key services in SimpleMES are considered 'Stable APIs' icon:balance-scale[role="green"].
This means the SimpleMES developers will make every effort to retain backward
compatibility with these services.  This does not mean that there will be no changes to these APIs.
It means that most of the changes will not affect older clients who use these APIs.
Typically, later releases will add new, optional fields to the requests.
The returned objects may have new fields added or some existing fields may become optional.
There is always a chance that a breaking change will be needed, but this will rarely happen.

These Stable APIs are flagged in the Doc pages with the note: *Stable API* icon:balance-scale[role="green"].

NOTE: Your code should try to use these Stable APIs and the domain objects whenever possible.
      This will improve the life of your code.


=== REST

These services are frequently exposed via HTTP with a REST (Representational state transfer) approach.
All actions are performed using HTTP requests with specific URLs and content.

==== Order/LNS GET APIs

A common type of API is the normal REST GET method.  This is used get information about various objects in
the system.  It is used frequently to get data on Orders or LSNs.  When used in places like the OrderController,
the URL can be used with an LSN, order.  It can be the ID (numeric) or the order/LSN name (primary key value).
For example, the `determineQtyStates()` method can be called for an order using the name:

*http:* `GET`

*url:* `/order/determineQtyStates/M1001`

[source,json]
.JSON Get Results
----
{
  "id":1000000001308000,
  "product":"PRODUCT_XYZ",
  "title":"Standard 27\" Bicycle"
}
----

This type of method uses a standard resolution precedence:

. LSN - ID (numeric)
. Order - ID  (numeric)
. LSN - Name
. Order - Name



==== CRUD

In general, Create, Read, Update, Delete (CRUD) actions are handled by REST-style URLs and actions on the object's controller
page.  For example, to read a _Product_, the client will perform an HTTP GET on the URL:

    /product/crud/BIKE27

This will return the JSON formatted data for the product _BIKE27_:

[source,json]
.JSON Get Results
----
{
  "id":1000000001308000,
  "product":"PRODUCT_XYZ",
  "title":"Standard 27\" Bicycle"
}
----

=== Services

Most Non-CRUD actions are accessed via the Services in SimpleMES.  These services are normal
Micronaut-style singleton services and provide most of the complex features in SimpleMES.
The built-in GUIs in SimpleMES always access the the business functions via these Services or the Controller/Domain
classes.

These Services always have a corresponding controller to allow HTTP access to these Services.  For example, the
`WorkService.start()` method has a controller at the URI `/work/api/start`.  This controller URI expects JSON content
that matches the method's input parameter (`StartRequest` in this case).


These requests follow the general REST approach, but primarily use the HTTP POST verb.  These APIs also do not use the
HTTP URL to identify the objects being processed in most cases.  The HTTP request content defaults to JSON format and
it will contain the objects to be processed.  The URL does not reference the object being affected since multiple
objects may be involved.

These types of API calls are always implemented as a normal Micronaut Service.  The details of the Service are
fully documented in the link:groovydoc/index.html[Groovy API^] docs for the Service itself.  There is a controller
associated with the service and provides the REST-style HTTP access.  Internal programs running within the SimpleMES
application server should use the service directly.  The HTTP API is only intended for access from external clients
(GUIs, machines, etc).

These services always end with 'Service'.  For example, `WorkService`, `OrderService`, etc.

An example of this service is the link:groovydoc/org/simplemes/mes/demand/WorkService.html[WorkService^] `start()` method.
To perform a start action on an Order, the following request is used:

*http:* `POST`

*url:* `/work/start`

[source,json]
.Example POST
----
{
  "order":"100023",
  "qty":10.0
}
----





