
=== Extension Points


ifeval::["{backend}" != "pdf"]

[inline-toc]#<<Extension Point Design>>#
[inline-toc]#<<ExtensionPoint Annotation>>#
[inline-toc]#<<ExtensionPoint Supported Scenarios>>#
[inline-toc]#<<Extension Point Documentation>>#

endif::[]

Frequently, you will need to extend core methods with logic that applies to specific additions
and modules.  The framework provides support for extension points.  These are methods
in the core code that are marked as allowing extension by other modules.  These extension
are discovered as Micronaut beans and support execution before or after the core method.

Originally, the flexible Groovy meta-class ability to modify the was used for method extensions.
This was great, but caused issues with many of the annotations used by Micronaut (e.g. @Transactional).




==== Extension Point Design

Extension points methods are marked with the _@ExtensionPoint_ annotation.  This inserts code
before the method logic and at return points.  This extra code executes custom methods that
are defined as Micronaut beans. This is handled by the
link:groovydoc/org/simplemes/eframe/custom/ExtensionPointHelper.html[ExtensionPointHelper^]
icon:share-square-o[role="link-blue"] methods to execute any matching beans.

A basic example with two custom beans is shown below:


//workaround for https://github.com/asciidoctor/asciidoctor-pdf/issues/271  and IDEA plugin dir issue
:imagesdir: {imagesdir-build}
ifeval::[{env}==idea]
:imagesdir-build: .asciidoctor
:imagesdir: .asciidoctor
endif::[]

.Custom Field Design
[ditaa,"extensionPointDesign"]
----
    +-----------------------------+   +----------------------------------+
    |Order.release(releaseRequest)|   | Bean1.preRelease(releaseRequest) |
    |                             +-+-+                                  |
    |                             | | |                                  |
    |                         cCCC| | |                              c4CF|
    +-----------------------------+ | +----------------------------------+
                                    |
                                    |
                                    | +---------------------------------------------+
                                    | | Bean2.postRelease(response, releaseRequest) |
                                    +-+                                             |
                                      |                                             |
                                      |                                         c6D6|
                                      +---------------------------------------------+

----

//end workaround for https://github.com/asciidoctor/asciidoctor-pdf/issues/271
:imagesdir: {imagesdir-src}

The core `release()` method is marked as an _@ExtensionPoint_.  There are two additions
that provide _Bean1_ and _Bean2_.  These beans extend the release method.  _Bean1_ is executed as
a pre method and _Bean2_ is a post method.  The post method may alter the response from the
core method, if needed.


===== ExtensionPoint Annotation

You, as the application developer, must mark your methods as extension points.
A simple service class might look like this:

[source,groovy]
.Example - Extension Point Usage
----

@Singleton
class OrderService {

  @ExtensionPoint(ReleasePoint, comment = "The Order releae() method.") // <.>
  ReleaseResponse release(ReleaseRequest request) {  // <.>
    . . .

    return new ReleaseResponse(...)   // <.>
  }
}
----
<.> The extension point uses a _ReleasePoint_ (interface) to define the pre/post method
    signature.  This must match the `release()` method's signature. All beans that implement this
    interface will be executed for all calls to the core `release()` method.
    The annotation also includes an optional comment that is used for the <<ExtensionPoint Documentation>>
    file as noted below.
<.> The method accepts a POGO argument.
<.> The method returns a POGO.

The _ReleasePoint_ interface is used to flag which beans will be executed for each call to
the core `release()` method.

[source,groovy]
.Example - Extension Point Interface
----
interface ReleasePoint {
  void preRelease(ReleaseRequest request)  // <.>

  ReleaseResponse postRelease(ReleaseResponse response, ReleaseRequest request)  // <.>
  
}
----
<.> The `preRelease()` method is passed the input(s) that are later passed to the core method.
<.> The `postRelease()` method is passed the response from the core method and can alter the
    returned value (if not null).

Finally, other modules can provide beans with these methods to alter the core logic.

[source,groovy]
.Example - Extension Point - Custom Methods
----
@Singleton
class OrderService implements ReleasePoint {

  void preRelease(ReleaseRequest request) {  // <.>
    request.order.qtyToRelease = 1.2
    . . .
  }
}
----
<.> The `preRelease()` method does some extra processing on each `release()` method execution.

===== ExtensionPoint Supported Scenarios

Due to the nature of the AST transformation logic, the _@ExtensionPoint_ annotation is
written to handle specific structures in the core methods.  These cases are tested and supported:


[source,groovy]
.Example - Extension Point - Supported Scenarios
----
@ExtensionPoint(ReleasePoint)
ReleaseResponse release1(ReleaseRequest request) {
  . . .
  return new ReleaseResponse(...)   // <.>
}

@ExtensionPoint(ReleasePoint)
ReleaseResponse release2(ReleaseRequest request) {
  . . .
  if () {  // <.>
    return new ReleaseResponse(...)
  } else {
    return new ReleaseResponse(...)
  }
}

@ExtensionPoint(ReleasePoint)
ReleaseResponse release2(ReleaseRequest request) {
  . . .
  if (...) {  // <.>
    return new ReleaseResponse(...)
  } else if (...) {
    return new ReleaseResponse(...)
  }
}
----
<.> Simple return at the end of the method.
<.> If/Else with return at the end of each block.
<.> If/ElseIf with return at the end of each block.

Other cases may be supported some day.

NOTE: A return statement is required in the method marked with _@ExtensionPoint_.


===== Extension Point Documentation

The modules will each need to document what extension points are available.  To make this easier,
the <<ExtensionPoint Annotation>> creates an _.adoc_ file with all of the extensions listed.
This file is _'build/generated/extensions.adoc'_.  This file can be included in your
ASCII doctor files like any other include file.  The result will look like this:

include::../../../../../../build/generated/extensions.adoc[]


NOTE: This example above is from the extension points in the framework sample code.  These are
not real extension points.

This file is generated when the Groovy classes are compiled.  It is also removed by a _clean_
action.  
The `comment` option on the _@ExtensionPoint_ annotation is used to generate the comment for each
extension point in this file.








