=== Archive Configuration

ifeval::["{backend}" != "pdf"]

[inline-toc]#<<Periodic Archive Tasks>>#

[inline-toc-header]#application.yml Options#
[inline-toc]#<<Automatic Verification of JSON>>#
[inline-toc]#<<Archive Logging>>#
[inline-toc]#<<Archiver to Use>>#
[inline-toc]#<<File Archiver Options>>#

endif::[]




Archiving needs some basic configuration to perform your archive tasks periodically.
You can also use the programmatic API to trigger the archive/unarchive under other conditions.


==== Periodic Archive Tasks

TBD

Most archiving is done automatically when records reach a specific age.  For example,
the link:{mes-core-path}/guide.html[MES Core^] icon:share-square[role="link-blue"]
Production Log records are archived after they reach a user-configurable age.
This is done by a background task that is configured in the <<Background Tasks>>
domain object.
The MES Core module configures a background task record, which the user can edit to
adjust the archive window and other options.

When creating an archive task, you can define what elements are needed to control the archiving.
For example, the MES production log archiving has two main options: age (days) and batch size.
This helps reduce the load on the system when archiving large numbers of records.  The batch size
makes sure that only one JSON file is created for a large number of those small records.

Typically, you add records to the default archive task table with an initial data load
domain class in your module:

[source,groovy]
.Example Initial Data Load
----
class InitialData {

  static mapWith = "none"   // <1>

  static initialDataLoad() {
    if (!BackgroundTask.findByTask('PROD_LOG_ARCHIVE')) {   // <2>
      def handler = new SampleBackgroundTaskHandler(ageDays: 180, batchSize: 500)  // <3> <4>
      def task = new BackgroundTask(task: 'PROD_LOG_ARCHIVE', backgroundTaskHandler: handler)
      task.backgroundTaskHandlerData = handler.data
      task.runInterval = TimeIntervalEnum.DAYS_1  // <5>
      task.save()

      log.warn("Loaded test data BackgroundTask: PROD_LOG_ARCHIVE")
    }
}
----
<1> Marks this domain as non-persistent.  It just supports the `initialDataLoad()` method.
<2> Checks to see if the task exists already.
<3> Your task should implement the
    link:groovydoc/org/simplemes/eframe/system/BackgroundTaskInterface.html[BackgroundTaskInterface^]
    icon:share-square-o[role="link-blue"].
<4> The defaults are set to archive records after 180 days, with a batch/file size of 500.
<5> This task is run once per day.


NOTE: The execution run interval is approximate.  It is only checked every 5 minutes, so
      more frequent execution is not supported.
      


==== Automatic Verification of JSON

The archiver will delete your domain objects after successfully writing the archive.
By default, the file will be verified.  If you wish to turn this off, then set this
_application.yml_ option:

[source,yaml]
.application.yml
----
eframe.archive.verify: false // <1>
----
<1> Disables verification of the JSON file.  Enabled by default.

This is a simple verification. In the case of JSON file archives, it verifies that the file
contains valid JSON, but it does not actually restore the object(s).  There may be other reasons
that the object(s) can't be restored.


==== Archive Logging

By default, all top-level archived records are logged to the
link:groovydoc/org/simplemes/eframe/archive/ArchiveLog.html[ArchiveLog^] icon:share-square-o[role="link-blue"]
domain class (database).
This provides a link to the actual archive file for later recovery.  You can disable this logging with the option:

[source,yaml]
.application.yml
----
eframe.archive.log: false  // <1>
----
<1> Disables the creation of the ArchiveLog records.

It is also possible to log to the server logs using the normal Logback logging mechanism using standard <<Logging>> mechanism
for the class _org.simplemes.eframe.archive.FileArchiver_

==== Archiver to Use

The default archiver is the <<File Archiver>>, which has its own configuration options.

You can provide your own archiver(s).
If you wish to use a custom archiver, use this option to point to you custom class:

[source,yaml]
.application.yml
----
eframe.archive.archiver: org.sample.custom.Archiver
----


