
=== ResolveService

ifeval::["{backend}" != "pdf"]

[inline-toc]#<<basic-scenarios-resolve-service>>#
[inline-toc]#<<resolveProductionRequest()>>#
[inline-toc]#<<resolveWorkable()>>#

endif::[]



The link:groovydoc/org/simplemes/mes/demand/service/ResolveService.html[ResolveService^]
icon:share-square-o[role="link-blue"] is used to find the right
objects/records to process on the shop floor.
This service allows you to find the right order/LSN when given limited information.  This means
you can try to start work on an order without knowing the specific operation to start.



NOTE: Most SimpleMES production service methods will call the `ResolveService.resolveProductionRequest()` method at
      the start of the action. This will fill in the missing fields in the request.  You normally won't need to call
      this method yourself.

[[basic-scenarios-resolve-service]]
==== Basic Scenarios

Many common scenarios involve trying to start work on orders with limited information.  This happens frequently with
automated machines on the shop floor.  The machines can read a barcode as the product enters the machine, but the
machine has no real knowledge of SimpleMES data or what the barcode really means.  It could be an order or an LSN.

To help with these cases, the Resolve service gives you methods to find the right records in SimpleMES to process.
In most cases, the caller uses the Resolve service to determine the records for you.   There may be times
when you need to use this resolving logic yourself.  The Resolve service can be used to 'fill in' the missing data
in many of the services requests.

For example, the <<work-service-start>> method uses a
link:groovydoc/org/simplemes/mes/demand/StartRequest.html[StartRequest^] icon:share-square-o[role="link-blue"].
The `resolveProductionRequest()` method will
automatically fill in any missing information.  You do not need to call the `resolveProductionRequest()` yourself in
most cases.

The supported scenarios are:


.Supported Resolve Scenarios
[cols="1,4", width=75%]
|===
|Scenario | Description

| *Barcode Only*| Only a generic barcode or user input string is provided.
                  The `resolveProductionRequest()` method will try to interpret this as an LSN
                  first, then as an Order.
| *Order Only*| Only an Order is provided.  The `resolveProductionRequest()` method will attempt to
                find the appropriate LSN and operation to process.
| *LSN Only*| Only an LSN is provided.  The `resolveProductionRequest()` method will attempt to find
              the appropriate Order and operation to process.
| *LSN+Order*| Both an Order and LSN are provided.  The `resolveProductionRequest()` method will
               attempt to find the appropriate operation to process.
|=== 

In all of these scenarios, the operation sequence and work center can be provided too.  If not provided, the service
will attempt to find the right operation to process (if any).  In some cases, the work center may also help narrow
down the list of possible choices.

==== Not Enough Information

*TBD: Add notes on missing data exceptions *

See the MissingDataException in the <<Enterprise Framework>> documentation.


==== resolveProductionRequest()

The `resolveProductionRequest()` method is used to fill in any missing information in most production requests.
It will use the information already in the request and narrow down to a specific object to process.

For example, order _M001_ has a routing with 3 operations: 1,2,3.  A `start()` request with only the
_barcode='M001'_ can be used to start the order at the current operation.  This means the `resolveProductionRequest)`
will find the proper order and the operation with a quantity in queue.

This method operates on production request POGOs that have the following fields:

.Important Fields - resolveProductionRequest
[cols="1,4", width=75%]
|===
|Field | Description

| *barcode*| A generic barcode or user input that can be an order or LSN.
| *order*| The <<order>> to be processed.
| *lsn*| The <<lsn>> to be processed.
| *qty*| The number of pieces to be processed.
| *operationSequence*| The sequence of the operation (step) the order/LSN is to be processed at.
| *workCenter*| The <<WorkCenter>> this work is being performed at.
|===

All of these fields are individually optional, but you must provide enough information for the action to be performed.
In some cases, a barcode alone will be enough to handle the action.  There is also an option on this
`resolveProductionRequest)` method to indicate if preference should be given to entities with a quantity in queue or
quantity in work.  For example, the `start()` method prefers to operate on quantities in queue.

The service will attempt to fill in the missing information using the following rules to fill in the missing information:


[cols=".^2,6", width=90%]
.Precedence for resolveProductionRequest()
|===
|Field | Precedence

|*Order*
a|

. If an LSN is given, then use the LSN's order.
. If barcode is given, then use that if there is only one order with the same barcode.

|*LSN*
a|

. If barcode is given, then use that if there is only one LSN with the same barcode.
. If Order is given, then use first LSN with the quantity in queue (or work).

|*Qty*
a|

. Use the current quantity in queue or in work, based on the preference parameter.

|*Operation Sequence*
a|

. Use the first operation with a quantity in queue or in work, based on the preference parameter.

|*Work Center*
a|

. If an operation is known, then use the work center from the routing operation.

|===


==== resolveWorkable()

The `resolveWorkable()` to find the right level to process a given order and/or LSN.  This is based on the
Product settings and the current state of this order.  This finds where the in work, in queue and other quantities are
handled for these cases.

This method operates on a link:groovydoc/org/simplemes/mes/demand/ResolveWorkableRequest.html[ResolveWorkableRequest^]
icon:share-square-o[role="link-blue"]
POGO that have the following fields:

.Important Fields - resolveWorkable
[cols="1,4", width=75%]
|===
|Field | Description

| *order*| The <<order>> to be processed.
| *lsn*| The <<lsn>> to be processed.
| *qty*| The number of pieces to be processed.
| *operationSequence*| The sequence of the operation (step) the order/LSN is to be processed at.
|===

All of these fields are individually optional, but you must provide enough information to find the workable unit
(LSN or order).

==== fixLSN()

This `fixLSN()` method is used to make sure the given object's order and LSN are consistent.
A common use is when receiving a request POGO with the LSN and optional order.  This looks
something like this:

[source,groovy]
.Example - Request POGO with Order and LSN
----
class CompleteRequest {
  @JSONByKey
  Order order

  @JSONByKey
  LSN lsn
}
----

You will then de-serialize the given JSON:

[source,json]
.Example - LSN JSON Request
----
{
  "order": "M1001",
  "lsn": "SN2001"
}
----

The normal JSON de-serialization (using the framework _@JSONByKey_) will find the first LSN that
matches _'SN2001'_.  This works great until you have duplicate serial number for another order.
The de-serialization might find the wrong LSN.

To handle this, we have the `fixLSN()` method:

[source,groovy]
.Example - fixLSN()
----

def completeRequest = new CompleteRequest(...)
resolveService.fixLSN(completeRequest)  // <.>

----
<.> Verifies that LSN/Order are consistent.  Will also populate Order if null.

This method takes anu object with `order` and `lsn` fields that are domain object references.
This method will throw an exception if the order/lsn combination is nor correct and the right
LSN can't be found.


