
=== WorkListService

The
link:reference.html#worklistservice[WorkListService^] icon:share-square-o[role="link-blue"]
is used to find work that is available (in queue) or in work.  This list can be restricted to work
in a work center or global.  This can show Orders and/or LSNs.

This service's methods are exposed by the
link:groovydoc/org/simplemes/mes/demand/controller/WorkListController.html[WorkListController^]
icon:share-square[role="link-blue"].  This controller supports the request/response POGOs
in JSON format.

==== findWork()

This is the primary method in this services.  It finds work that is in queue or in work with
various filter criteria.
This method returns a list of Orders/LSNs that match the criteria.  The list is
row-limited with the normal offset and max settings.  This response also includes the
total number of rows available, for support of paging.

This method performs 4 queries to find all types of work needed:

* Orders with no routing.
* Orders with a routing.
* LSNs with no routing.
* LSNs with a routing.

Most customers will use one of these combinations, but the MES will not limit you to just one.  This means
all four queries will be executed and combined.

NOTE: This method is part of the <<Stable API>> icon:balance-scale[role="green"].

===== Request and Response

This method takes a request object
link:groovydoc/org/simplemes/mes/demand/FindWorkRequest.html[FindWorkRequest^] icon:share-square[role="link-blue"]
and returns the response
link:groovydoc/org/simplemes/mes/demand/FindWorkResponse.html[FindWorkResponse^] icon:share-square[role="link-blue"].

