
=== WorkService

ifeval::["{backend}" != "pdf"]

[inline-toc]#<<Common Work Service Features>>#
[inline-toc]#<<work-service-start,start()>>#
[inline-toc]#<<work-service-complete,complete()>>#

endif::[]



The
link:reference.html#workservice[WorkService^] icon:share-square-o[role="link-blue"]
is used to start and complete work on
some portion of a product on the shop floor.  This contains most of the business logic that
controls and tracks these production operator actions.

==== Common Work Service Features

Most of the production work service methods use a similar format for the request POGOs:

.Important Fields - Common WorkService Fields
[cols="1,4", width=75%]
|===
|Field | Description

| *barcode*| A generic barcode or user input that can be an order or LSN.
| *order*| The <<order>> to be processed.
| *lsn*| The <<lsn>> to be processed.
| *qty*| The number of pieces to be processed.
| *operationSequence*| The sequence of the operation (step) the order/LSN is to be processed at.
| *workCenter*| The <<WorkCenter>> this work is being performed at.
|=== 

All of these fields are individually optional, but you must provided enough information for the action to be performed.
In some cases, a barcode alone will be enough to handle the action.  The Work service will attempt to fill in the missing
information using the <<ResolveService>>.  You normally don't need to use the Resolve Service directly, but
it is available for your use.  The guide will give you some idea of the logic used to resolve to specific values
in most requests.

The actual data required to perform the action depends on the configuration of your data.  If you have no routings,
then an `operationSequence` is not needed.  If you do not use LSNs, then no LSN is needed.  In many cases, SimpleMES
can guess what you wish operate on, even if you do not provide all of the information.

A typical scenario is that you have a semi-unique barcode string to start work on, but you do not have the specific LSN,
order or operation sequence to process.  SimpleMES uses the `ResolveService` to narrow this down to a specific Workable
object to process. In the case of multiple operations on a routing, SimpleMES will try to use the operation where the
quantity is in queue for a `start()` action.

Most Work Service methods will automatically call the `ResolveService.resolveProductionRequest()` method at the start
of the action.  This will fill in the missing fields in the request.

Some of the key business logic for these Work Service methods is implemented in the
link:groovydoc/org/simplemes/mes/demand/WorkStateTrait.html[WorkStateTrait^] icon:share-square-o[role="link-blue"].
This includes the manipulation of the qty's and dates in the workable object.


[[work-service-start,WorkService.start()]]
==== start()

The link:reference.html#work-service-start[Start^] icon:share-square-o[role="link-blue"]
method is used to begin work on an order or LSN.   This can be the entire order, one LSN or just a portion.
The work is performed at an optional work center and is logged to the action log.

The link:groovydoc/org/simplemes/mes/demand/StartRequest.html[StartRequest^]
icon:share-square-o[role="link-blue"] object is the main argument for the
`start()`.  This is a simple POGO that you must populate before you perform the start.
This method returns the order/LSN that was started.

The `start()` finds the appropriate
link:groovydoc/org/simplemes/mes/demand/WorkableInterface.html[Workable^] icon:share-square-o[role="link-blue"]
that matches the start request's inputs (e.g. an Order or sub-element that can be started).  The Work service then
calls the `startQty()` on that Workable.  This then validates that the Qty can be started.

If everything passes the validation, then the WorkService will log the start via the ActionLog.
There is a corresponding `reverseStart()` method to "un-start" the work.

NOTE: This method is part of the <<Stable API>> icon:balance-scale[role="link-blue"].


[[work-service-complete,WorkService.complete()]]
==== complete()

The `complete()` method is used to finish work on an order or LSN.   This can be the entire order,
one LSN or just a portion.  The work is performed at an optional work center and is logged to the action log
and <<ProductionLog>>.

This method returns the order/LSN that was completed.

NOTE: This method is part of the <<Stable API>> icon:balance-scale[role="link-blue"].

The `complete()` finds the appropriate
link:groovydoc/org/simplemes/mes/demand/WorkableInterface.html[Workable^] icon:share-square-o[role="link-blue"]
that matches the request's inputs (e.g. an Order or sub-element that can be completed).  The Work service then
calls the `completeQty()` on that Workable.  This then validates that the Qty can be completed.

If everything passes the validation, then the WorkService will log the start via the ActionLog.


