
=== Roles

The roles created automatically by the MES Core module provide the basic security roles for the
entire suite of MES link:{mes-path}/guide.html#modules[Modules^] icon:share-square-o[role="link-blue"].
You can add additional roles, but the core controllers will only enforce
security using the core roles.
If these roles are deleted from the database, then they will be re-created on the next startup.

The roles provided by the core module are:

* <<SUPERVISOR>> - The shop floor line supervisor tasks.  Include releasing and managing work on
                 the shop floor.
* <<ENGINEER>> - Designs products and shop floor processes. Includes defining Work Centers
               and related objects.
* <<OPERATOR>> - Performs most shop floor production, but can't configure the shop floor or
               affect production outside of the local area.
* <<LEAD>> - A 'super' operator that does setup or works as a lead over a group of operators.


NOTE: The _admin_ user will be given these roles on startup, but only if the record version
      is less than 5.  This allows the default _admin_ user to be given roles by modules,
      but lets you remove them later if needed.

Some of the pages available to each role is shown below (not an full list):

==== (No Role or Anonymous)

* Login Pages
* Overall System Status Pages.


==== ADMIN

* Overall administrator over the entire system.  This role does not automatically give permission
  over other roles below.  You will need to given your admin-type users each role needed.

==== SUPERVISOR

Controls overall shop floor actions and manages demand flow on the floor.

* Defines Orders.

==== ENGINEER

Designs products and shop floor processes.

* Defines Work Centers.
* Defines Products.
* Defines Routings.

==== OPERATOR

Performs most shop floor production, but can't configure the shop floor or
affect production outside of the local area.

* Operator Dashboard.
* Process work (start/complete/etc).

==== LEAD

A 'super' operator that does setup or works as a lead over a group of operators.

* Work Center Setup.





=== Controller Security

By default all controller methods must be secured.  This means adding the _@Secured_ annotation
to your controllers:

[source,groovy]
----
import io.micronaut.security.annotation.Secured

@Secured('SUPERVISOR')
@Transactional
class OrderController {

  def release() {
    . . .
  }
}
----

The role chosen can be any of the defined roles.  Individual methods can be secured too.

See
link:{eframe-path}/guide.html#controller-testing[Controller Testing^] icon:share-square-o[role="link-blue"]
for use of the _ControllerTester_ to test security on your controllers (recommended for all controllers).



