
=== WorkService

ifeval::["{backend}" != "pdf"]

[inline-toc]#<<work-service-start,start()>>#
[inline-toc]#<<work-service-complete,complete()>>#

endif::[]



The link:groovydoc/org/simplemes/mes/demand/service/WorkService.html[WorkService^]
icon:share-square[role="link-blue"] is used start/complete that is available.

This service's methods are exposed by the
link:groovydoc/org/simplemes/mes/demand/controller/WorkController.html[WorkController^]
icon:share-square[role="link-blue"].  This controller supports the request/response POGOs
in JSON format.


[[work-service-start,WorkService.start()]]
==== start()

.start(<<StartRequest>>) returns List< <<StartResponse>> >

The link:guide.html#work-service-start[start()^] icon:share-square-o[role="link-blue"]
method is used to begin work on an order or LSN.   This can be the entire order, one LSN or just a portion.
The work is performed at an optional work center and is logged to the action log.

The <<StartRequest>> object is the main argument for the
`start()`.  This is a simple POGO that you must populate before you perform the start.
This method returns a list of the <<StartResponse>> objects with the results of the start action.

NOTE: This method is part of the <<Stable API>> icon:balance-scale[role="link-blue"].


The basic flow for this `start()` method uses these key objects and methods.  These methods can be
important extension points (see link:guide.html#enterprise-framework[Enterprise Framework^] icon:share-square-o[role="link-blue"]
for details).


//workaround for https://github.com/asciidoctor/asciidoctor-pdf/issues/271
:imagesdir: {imagesdir-build}

[ditaa,"workServiceStartFlow"]
----

+------------------+      +---------------------+
|   WorkService    |----->| ResolveService cGRE |
|     start() cGRE |      |  resolveWorkable()  |
+------------------+      +---------------------+
    |   | Calls the workable's start() method
    |   |       +------------+    +-----------------+
    |   +------>| Order cGRE |--->| Order cGRE      |
    |   |       |  startQty()|    |  validateStart()|
    |   |       +------------+    +-----------------+
    |   |
    |   |       +------------+    +-----------------+
    |   +------>| LSN   cGRE |--->| LSN   cGRE      |
    |   |       |  startQty()|    |  validateStart()|
    |   |       +------------+    +-----------------+
    |   |
    |   |       +--------------------+    +--------------------+
    |   +------>| OrderOperState cGRE|--->| OrderOperState cGRE|
    |           |  startQty()        |    |  validateStart()   |
    |           +--------------------+    +--------------------+
    |
    v
  +------------------+
  | ActionLog cCCC   |
  |    log()         |
  +------------------+

----

//end workaround for https://github.com/asciidoctor/asciidoctor-pdf/issues/271
:imagesdir: {imagesdir-src}

The `start()` finds the appropriate
link:groovydoc/org/simplemes/mes/demand/WorkableInterface.html[Workable^] icon:share-square-o[role="link-blue"]
that matches the start request's inputs (e.g. an Order or sub-element that can be started).  The Work service then
calls the `startQty()` on that Workable.  This then validates that the Qty can be started.

If everything passes the validation, then the WorkService will log the start via the ActionLog.
There is a corresponding `reverseStart()` method to "un-start" the work.

See link:groovydoc/org/simplemes/mes/demand/WorkStateTrait.html[WorkStateTrait^] icon:share-square-o[role="link-blue"]
for common qty/date manipulation logic that applies to all supported complete scenarios (e.g.
order, LSN and routing variations).


==== StartRequest

The fields defined for the link:groovydoc/org/simplemes/mes/demand/StartRequest.html[StartRequest^]
icon:share-square[role="link-blue"] include:


.Important Fields - StartRequest
[cols="1,4", width=75%]
|===
|Field | Description

| *barcode*| A generic barcode or user input that can be an order or LSN.
| *order*| The <<order>> to be processed.
| *lsn*| The <<lsn>> to be processed.
| *qty*| The number of pieces to be processed.
| *operationSequence*| The sequence of the operation (step) the order/LSN is to be processed at.
| *workCenter*| The <<WorkCenter>> this work is being performed at.
|===


==== StartResponse

The fields defined for the link:groovydoc/org/simplemes/mes/demand/StartResponse.html[StartResponse^]
icon:share-square[role="link-blue"] include:


.Important Fields - StartResponse
[cols="1,4", width=75%]
|===
|Field | Description

| *order*| The <<order>> processed.
| *lsn*| The <<lsn>> processed.
| *qty*| The number of pieces to be processed.
| *operationSequence*| The sequence of the operation (step) the order/LSN was processed at.
| *undoActions*| The list of actions needed to undo the start.
|===



[[work-service-complete,WorkService.complete()]]
==== complete()

.complete(<<CompleteRequest>>) returns List< <<CompleteResponse>> >

The link:guide.html#work-service-complete[complete()^] icon:share-square-o[role="link-blue"]
is used to finish work on an order or LSN.   This can be the entire order,
one LSN or just a portion.  The work is performed at an optional work center and is logged to
the action log and <<ProductionLog>>.

The <<CompleteRequest>> object is the main argument for the
`complete()`.  This is a simple POGO that you must populate before you perform the complete.
This method returns a list of <<CompleteResponse>> objects with the results of the complete action.

NOTE: This method is part of the <<Stable API>> icon:balance-scale[role="link-blue"].


The basic flow for this `complete()` method uses these key objects and methods.  These methods can be
important extension points (see link:guide.html#enterprise-framework[Enterprise Framework^] icon:share-square-o[role="link-blue"]
for details).

//workaround for https://github.com/asciidoctor/asciidoctor-pdf/issues/271
:imagesdir: {imagesdir-build}

[ditaa,"workServiceCompleteFlow"]
----

+------------------+      +---------------------+
|   WorkService    |----->| ResolveService cGRE |
|   complete() cGRE|      |  resolveWorkable()  |
+------------------+      +---------------------+
    |   | Calls the workable's complete() method
    |   |       +---------------+    +-------------------+
    |   +------>| Order cGRE    |--->| Order cGRE        |
    |   |       |  completeQty()|    | validateComplete()|
    |   |       +---------------+    +-------------------+
    |   |
    |   |       +---------------+    +--------------------+
    |   +------>| LSN   cGRE    |--->| LSN   cGRE         |
    |   |       |  completeQty()|    |  validateComplete()|
    |   |       +---------------+    +--------------------+
    |   |
    |   |       +--------------------+    +--------------------+
    |   +------>| OrderOperState cGRE|--->| OrderOperState cGRE|
    |           |  completeQty()     |    |  validateComplete()|
    |           +--------------------+    +--------------------+
    |
    v
  +------------------+
  | ActionLog cCCC   |
  |    log()         |
  +------------------+

  +--------------------------+    +-------------------+
  | ProductionLogService cCCC|--->| ProductionLog cCCC|
  |     log()                |    |     log()         |
  +--------------------------+    +-------------------+

----

//end workaround for https://github.com/asciidoctor/asciidoctor-pdf/issues/271
:imagesdir: {imagesdir-src}

The `complete()` finds the appropriate
link:groovydoc/org/simplemes/mes/demand/WorkableInterface.html[Workable^] icon:share-square-o[role="link-blue"]
that matches the request's inputs (e.g. an Order or sub-element that can be completed).  The Work service then
calls the `completeQty()` on that Workable.  This then validates that the Qty can be completed.

If everything passes the validation, then the WorkService will log the complete via the ActionLog
and <<ProductionLog>>.

See link:groovydoc/org/simplemes/mes/demand/WorkStateTrait.html[WorkStateTrait^] icon:share-square-o[role="link-blue"]
for common qty/date manipulation logic that applies to all supported complete scenarios (e.g.
order, LSN and routing variations).

==== CompleteRequest

The link:groovydoc/org/simplemes/mes/demand/CompleteRequest.html[CompleteRequest^]
icon:share-square-o[role="link-blue"] object is the main argument for the
`complete()`.  This is a simple POGO that you must populate before you perform the complete.


.Important Fields - CompleteRequest
[cols="1,4", width=75%]
|===
|Field | Description

| *barcode*| A generic barcode or user input that can be an order or LSN.
| *order*| The <<order>> to be processed.
| *lsn*| The <<lsn>> to be processed.
| *qty*| The number of pieces to be processed.
| *operationSequence*| The sequence of the operation (step) the order/LSN is to be processed at.
| *workCenter*| The <<WorkCenter>> this work is being performed at.
|===



==== CompleteResponse

The fields defined for the link:groovydoc/org/simplemes/mes/demand/CompleteResponse.html[CompleteResponse^]
icon:share-square[role="link-blue"] include:


.Important Fields - CompleteResponse
[cols="1,4", width=75%]
|===
|Field | Description

| *order*| The <<order>> processed.
| *lsn*| The <<lsn>> processed.
| *qty*| The number of pieces to be processed.
| *operationSequence*| The sequence of the operation (step) the order/LSN was processed at.
| *done*| If true, then the completed unit is done (no more processing planned).
| *undoActions*| The list of actions needed to undo the complete.
|===

