
=== WorkListService

The link:groovydoc/org/simplemes/mes/demand/service/WorkListService.html[WorkListService^]
icon:share-square[role="link-blue"] is used
to find work that is available (in queue) or in work.  This list can be restricted to work
in a work center or global.  This can show Orders and/or LSNs.

This service's methods are exposed by the
link:groovydoc/org/simplemes/mes/demand/controller/WorkListController.html[WorkListController^]
icon:share-square[role="link-blue"].  This controller supports the request/response POGOs
in JSON format.


==== findWork()

.findWork(<<FindWorkRequest>>) returns <<FindWorkResponse>> 

This is the primary method in this services.  It finds work that is in queue or in work with
various filter criteria.
This method returns a list of Orders/LSNs that match the criteria.  The list is
row-limited with the normal offset and max settings.  This response also includes the
total number of rows available, for support of paging.

This method performs 4 queries to find all types of work needed:

* Orders with no routing.
* Orders with a routing.
* LSNs with no routing.
* LSNs with a routing.

Most customers will use one of these combinations, but the MES will not limit you to just one.  This means
all four queries will be executed and combined.

NOTE: This method is part of the <<Stable API>> icon:balance-scale[role="link-blue"].


==== FindWorkRequest

The fields defined for the link:groovydoc/org/simplemes/mes/demand/FindWorkRequest.html[FindWorkRequest^]
icon:share-square[role="link-blue"] include:


.Important Fields - FindWorkRequest
[cols="1,4",width=75%]
|===
|Field | Description

| *workCenter*| The work center to filter the results by.  Only work in this work center will be displayed (*Optional*).
| *findInWork*| If true, then the `findWork()` method should return objects that are in work. (*Default:* true)
| *findInQueue*| If true, then the `findWork()` method should return objects that are in queue. (*Default:* true)
| *max*| The maximum number of rows to return (*Default:* 10).  See <<max-rows-work-list-service>>.
| *offset*| The row to start the results sets from (*Default:* 0).
|===

==== FindWorkResponse

The fields defined for this link:groovydoc/org/simplemes/mes/demand/FindWorkResponse.html[FindWorkResponse^]
icon:share-square[role="link-blue"] include:


.Important Fields - FindWorkResponse
[cols="1,4",width=75%]
|===
|Field | Description

| *totalAvailable*| The total number of rows available that matches the search criteria. (*int*).
| *list*| The list of details rows found that match the search criteria.
          This detail represents a single unit in queue or in work.  This can be an order and/or LSN.
          (*List* of <<FindWorkResponseDetail>>).
|===

==== FindWorkResponseDetail

The fields defined for this
link:groovydoc/org/simplemes/mes/demand/FindWorkResponseDetail.html[FindWorkResponseDetail^]
icon:share-square[role="link-blue"] include:


.Important Fields - FindWorkResponseDetail
[cols="1,4",width=75%]
|===
|Field | Description

| *order*| The order that is in work or queue (*<<Order>>*).
| *lsn*| The LSN that is in work or queue (*<<lsn>>*).
| *operationSequence*| The operation this qty is at  (0 means not at an operation) (*int*).
| *qtyInQueue*| The qty in queue (*BigDecimal*).
| *qtyInWork*| The qty in queue work (*BigDecimal*).
| *workCenter*| The work center the unit is in (*<<WorkCenter>>*).
| *inWork*| True if the unit is in work (*boolean*).
| *inQueue*| True if the unit is in queue (*boolean*).
|===

[[max-rows-work-list-service]]
===== Max Rows and Offset

Each of the 4 queries can return the max number of rows specified in the request (e.g. 10 rows each).
The service will combine these results into one list that may be up to 4 times larger than the
max rows setting.  This is rare since most customer don't use all 4 types of tracking levels (Orders/LSN/routing).

The offset will be used to support paging.

The max value has an absolute maximum as defined in link:{eframe-path}/guide.html#row-limits[Row Limits^]
icon:share-square[role="link-blue"] (typically 100).
