
=== WorkCenterAssyService

The link:groovydoc/org/simplemes/mes/assy/floor/WorkCenterAssyService.html[WorkCenterAssyService^]
icon:share-square-o[role="link-blue"]
is used to setup and maintain the assembly state of a Work Center in the <<WorkCenterComponent>> domain.
This service provides features that compliment the core Work Center Service, but does not add
and method extensions to the core service.
See link:{mes-core-path}/guide.html#services[MES Core Services^] icon:share-square-o[role="link-blue"]
for details on the core Work Center service.

The service methods are exposed using the
link:groovydoc/org/simplemes/mes/assy/floor/WorkCenterAssyController.html[WorkCenterAssyController^].
icon:share-square-o[role="link-blue"]
These controller methods generally match the inputs and outputs of the services.  The only
difference is the values are passed as JSON strings.

The controller does not expose the normal CRUD (Create, Read, Update and Delete) methods that are common
with domain objects.  The methods provide a way to maintain all component records, but preserves
the long-term history of the component setup records.


[[work-center-assy-add-component,WorkCenterAssyService.addComponent()]]
==== addComponent()

This method adds a component to a given location for use in the Work Center for assembly.
If a component is already loaded at the current location, then this method will add this component
to the location. See <<replaceComponent()>> for a method to replace the component.

The link:groovydoc/org/simplemes/mes/assy/floor/AddComponentRequest.html[AddComponentRequest^]
object is the main argument for the `addComponent()`.  This is a simple POGO that you must populate
before you call the method.

[cols="1,4", width=75%]
|===
|Field | Description

| `workCenter`| The work center to add the component to (*Required*).
| `component`| The component <<guide.adoc#product,Product>> to be added to the work center (*Required*).
| `location`| The location in the work center that the component is added to (*Default: '@'*).
| `qty`| The number of pieces loaded.  This is currently used for reference (*Optional*).
| `assemblyData`| The FlexType used to define the assembly data for this component.  See
                  link:{eframe-path}/guide.html#flex-types[Flex Types^] icon:share-square-o[role="link-blue"]
                  for details (*Optional*).
|===

This method returns the WorkCenterComponent created for this component.


[[work-center-assy-add-component-example]]
==== JSON Example

To add a component using JSON via the controller, use this request _POST_ request:

*uri:* `/workCenterAssy/addComponent`

The JSON content passed to the controller contain the component to add:

[source,JSON]
.JSON Add Component
----
<addComponentRequest>
  <workCenter>ASSEMBLY STATION 3</workCenter>
  <component>WING NUT 27</component>   // <1>
  <location>BIN 27</location>
  <qty>100.0</qty>
  <assemblyData>                     // <2>
    <flexType>LOT</flexType>
    <category>ASSEMBLY</category>
  </assemblyData>

  <assemblyDataValues>  // <3>
    <vendor>ACME</vendor>
    <lot>L12312016-001</lot>
  </assemblyDataValues>
</addComponentRequest>
----
<1> The component is a reference to a product domain record.
<2> `assemblyData` is a Flex Type.  This must come before the field values.
<3> The LOT assembly flex type allows input of `vendor` and `lot` values.


