/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.simplemes.eframe.reports;


/**
 * Report utils for use with the Report Engine.  This is a stub for use inside of the Report Engine Designer Studio.
 * It is provided as part of the java8-supp library.  The method results are not identical to real run-time
 * library used at run-time.
 */
public class ReportUtils {
  /**
   * Formats the extensible fields from the json field in a format suitable for web pages.
   * <p>
   * <b>Note</b>: If a flexTypeUuid is not given, then the field ID's will be used instead of the labels.
   *
   * @param fieldJson The fields (as a JSON string).
   * @param flexTypeUuid The UUID of the Flex Type for this set of fields.
   * @param flexTypeName The same of the flex type field (e.g. 'assemblyDataType').
   * @param highlightFieldNames If true, then the field name is highlighted (with HTML <b>bold</b> elements)..
   * @param maxLength The max length of the values to display.
   * @return The formatted values.
   */
  public static String formatFields(String fieldJson, String flexTypeUuid, String flexTypeName, Boolean highlightFieldNames, Integer maxLength) {
    if (fieldJson==null) {
      return "";
    }

    String s = fieldJson.replace(flexTypeName+"_","");
    s = s.replace('"',' ');

    return s;
  }

}
