
[[eframe-ajax]]
=== ajax

.ajax(method,uri, ajaxData, success)

This Javascript function sends an Ajax request to the server at the given `uri`.
The results are passed to the `success` function you provide. The `ajaxData`
are converted to JSON and sent as the body of the request.
This function is part of the <<eframe-js>> library.

.Parameters
[cols="1,1,5"]
|===
|Parameter|Type|Description

|*method*       |string| The method for the request ('GET', 'POST', 'PUT' or 'DELETE') (*Required*).
|*uri*          |string| The URI to send the request to (*Required*).
|*ajaxData*     |map or String| The body of the request (as JSON) sent to the server (*Optional*).
                                Can be a JSON string or a javascript object.
|*success*      |function| This is called when the request succeeds (*Optional*).
|*options*      |object| Additional objects for the request (*Optional*).
|===

The `options` is a Javascript object that can contain these options:

* *divID* - The Message div ID to display any error messages.


[source,javascript]
.Example
----
var ajaxData = {};                 // <.>
ajaxData.event = "ColumnResized";
ajaxData.pageURI = '/the/page';
ajaxData.element = 'aGrid';
ajaxData.column = 'userName';
ajaxData.newSize = 12.5;

ef.ajax("POST", "/userPreference/guiStateChanged", ajaxData,
  function (responseText) {  // <.>
     var data = JSON.parse(responseText);
     console.log(data);
     . . .
  }
);
----
<.> The body of the Ajax request is a javascript plain object (a map).
<.> Function called when the Ajax succeeds, passing the HTTP response body to the function as a string.


Server-side errors are displayed in the standard error
link:guide.html#message-display[location^] icon:share-square-o[role="link-blue"].
