
[[eframe-get]]
=== get

.get(uri, arguments, success)

This Javascript function performs an Ajax GET request to the server at the given `uri`.
The results are passed to the `success` function you provide. The `arguments` are added to the
URI for the request. This function is part of the <<eframe-js>> library.


NOTE: This get call sets the `'Cache-Control'` on the request to _'no-cache'_ to prevent
      caching of the data.

.Parameters
[cols="1,1,5"]
|===
|Parameter|Type|Description

|*uri*          |string| The URI to send the request to (*Required*).
|*arguments*    |map| The arguments to add as request parameters to the URI (*Optional*).
|*success*      |function| This is called when the request succeeds (*Optional*).
|===


[source,javascript]
.Example
----
var args = {pageURI: uri, preferenceType: 'DialogPreference'};  // <.>
ef.get("/userPreference/findPreferences", args,
  function (responseText) {  // <.>
     var data = JSON.parse(responseText);
     console.log(data);
     . . .
  }
);
----
<.> Arguments added to the URI for the request.
<.> Function called when the GET succeeds, passing the HTTP response body to the function.


Server-side errors are displayed in the standard error
link:guide.html#message-display[location^] icon:share-square-o[role="link-blue"].
