
[[eframe-lookup]]
=== lookup

.lookup(key, arguments)

This Javascript function looks up text from the preloaded message cache generated by the
<<efPreloadMessages>>. This function supports the simple Java-style replaceable parameters
in the messages. This function is part of the <<eframe-js>> library.


The `arguments` are optional and can be a single value, multiple values or an array.


NOTE: This function depends on <<efPreloadMessages>> usage on the page. That marker will load
      the messages for the browser's locale.


.Parameters
[cols="1,6"]
|===
|Argument|Description

|*key*| The lookup key (e.g. 'ok.label')  (*Required*).
|*(arguments)*|Optional values to use with simple parameter replacement (Java-style, but only supports {0}, {1}, ...

|===




==== Example

In this example, a dialog needs some labels:

[source,groovy]
.messages.properties
----
cancel.label=Cancel
ok.label=Ok

dialog.title=Edit {0}
----

The dialog.ftl code would use

[source,html]
.dialog.ftl
----
<@efPreloadMessages codes="ok.label,cancel.label,dialog.title"/> // <.>

----
<.> The marker <<efPreloadMessages>> makes the localized strings available to the javascript logic.


[source,javascript]
.Javascript Use
----
  var msg = ef.lookup('dialog.title','M1020445');  // <.>
----
<.> This will set msg to the value 'Panel A' (in the browser's current locale).


