
=== postAjaxForm

.postAjaxForm(formOrData, uri, otherData, success)

This Javascript function posts a toolkit form as an Ajax POST request to the server at the given
`uri`. The results are passed to the `success` function you provide.  Additional values
can be passed to the server if needed.
The values are converted to JSON and sent as the body of the request.
This function is part of the <<eframe-js>> library.

NOTE: This function submits the request in a background HTTP request to the server.
      It does not refresh the page or use the normal HTML form submit logic.

.Parameters
[cols="1,1,5"]
|===
|Parameter|Type|Description

|*formOrData*   |string or object| The toolkit form ID that holds the fields to POST (*Required*).
                         Can also be a Javascript object (map) with the data to send.
                         This is usually the form specified in the <<efForm>> marker.
|*uri*          |string| The URI to send the request to (*Required*).
|*otherData*    |map| Additional values to send with the post request (*Optional*).
|*success*      |function| This is called when the request succeeds (*Optional*).
|*options*      |map| Additional options for the request (*Optional*).
                      See <<eframe-post,post>> for details.
|===


[source,html]
.Example - Simple Dashboard Activity Form Submit
----
<script>
  <#assign panel = "${params._panel}"/>
  <#assign variable = "${params._variable}"/>
  ${variable}.log = function () {  // <.>
    ef.postAjaxForm('logFailure','/dashboard/logFailure',null,
      function(response) {  // <.>
        dashboard.finished('${panel}');
        ef.displayMessage({info: 'Logged Failure RM1001 for M1007'});
      });
  };
</script>
<@efForm id="logFailure" dashboard=true>       // <.>
  <@efField field="rma" value="RMA1001" width=20/>
  <@efField field="product" value="CM3056857"/>
  <@efButtonGroup>
    <@efButton label="Log Failure" click="${variable}.log();"/>
    <@efButton label="cancel.label" click="dashboard.finished('${panel}')"/>
  </@efButtonGroup>
</@efForm>
----
<.> The `log()` function is called when the user presses the 'Log Failure' button.
    This will post the field inputs to a specific URL.
<.> The success function is called with the response from the server.  This example
    closes the activity and displays a success message.
<.> Defines the form to submit.  Has two fields and two buttons.


Server-side errors are displayed in the standard error location
link:guide.html#message-display[location^] icon:share-square-o[role="link-blue"].


See <<postActivity>> for a dashboard-oriented way to simplify for submission from a dashboard
activity.