
=== GUI Development Setup

ifeval::["{backend}" != "pdf"]
[inline-toc]#<<GUI Setup - New Client Module>>#
[inline-toc]#<<GUI Setup - Existing Client Module>>#
[inline-toc]#<<GUI Setup - Common Setup>>#
[inline-toc]#<<GUI Setup - IDEA>>#
[inline-toc]#<<GUI Setup - Build Eframe Library>>#
[inline-toc]#<<Client Module Version Dependencies>>#

endif::[]


If you have cloned the GIT repository for an existing client sub-module, then follow the
<<GUI Setup - Existing Client Module>> instructions.  For new client sub-modules,
follow the <<GUI Setup - New Client Module>> instructions.

Some important notes about client development:

* _npm_ will install most modules in the sub-folder (_node_modules_).  This tends to be
  a huge directory.  You will want to make sure it is in the git
  <<IDEA and the Client Folder,exclude>> file.
* Each client sub-module will use its own set of modules/versions.  These will be
  packaged for each module separately.
* Some packages are installed globally.  This means they are not in the (_node_modules_)
  folder.  You can see which ones are global with the command _npm list -g --depth=0_  .



==== GUI Setup - Install Node and npm

Install https://nodejs.org/en/[node and npm^].  This provides the npm tool, which is
used to install all of the javascript modules such as Vue and related modules.

==== GUI Setup - New Client Module

Creating a new client module is somewhat complex.  The easiest solution is to copy the
_eframe/src/templates/client/sample_ folder to a new client folder in your module.
It should be copied to the _module/src/client/module_ folder (replace _module_ with your
ne module's name).

[source,script]
.New Client Sub-Module Creation - Linux Commands
----
  cd src/client
  mkdir quality <.>
  cd quality
  cp -r ../../../../templates/client/sample .  <.>
----
<.> Creates a sub-module named _'quality'_.  Use the sub-module name for your new client
    sub-module.
<.> Use the correct source path for the eframe templates folder here.
    Linux command shown.  Use drag/drop on Windows.




===== Edit Copied Files

Some of the files created above will need to be changed for your new client module.
The notes below assume the new client module name is _'quality'_.
Use your module name instead.

NOTE: While editing in Intellij, you will receive requests to run 'npm install'.  Ignore
      these requests until you have finished editing the files below.

* _package.json_ - Need to change the top-level name/version.  You may need to
  adjust versions to match the current eframe _package.json_ file.
* _vue.config.js_ - Change the '_/client/sample_' path to _'/client/sample'_.
* _vue.config.js_ - Change the '_GUIPage_' section to the name of your page(s).
* _gradle.properties_ - Set the `clientModules`=quality

The _gradle.properties_ file should have an element like this:

[source,groovy]
.Adding clientModules to gradle.properties
----
clientModules=quality <.>
----
<.> The list of client modules to init/build.  This can be a comma-delimited list for multiple
    modules.

See <<Entry Page Structure>> for more details on how the client pages are defined.


===== Run npm Init

Next, you will need to initialize the npm module system with this gradle option or
let Intellij run it for you when prompted.  The gradle commands are:

[source,script]
.New Client Sub-Module Creation - Linux Commands
----
  cd quality <.>
  ./gradlew npmInit
  ./gradlew copyEframeLib
----
<.> The new client modiel created above.



==== GUI Setup - New Client Module without Template

Creating a new client module without the template is a complex task.  Don't attempt this
without a good reason.

[source,script]
.Client First Time Setup
----
  cd src/client
  npm install -g @vue/cli <.>
  vue create moduleName <.>
  cd moduleName
  npm install vue@next --save <.>
  npm install primevue --save  <.>
  npm install primeicons --save
  npm install primeflex --save
  npm install vue-i18n@next --save
  npm install axios vue-axios --save
  npm install vuex@next --save
  npm install in-memoriam --save
  npm install compression-webpack-plugin@6.0.5 --save-dev
  npm install webpack-bundle-analyzer --save <.>

----
<.> Installs the command line tool as a global utility.
    *This only needs to be done once for a given development system.*
    This provides the _vue_ command used next.
<.> Select the Vue3 option if prompted.
    Creates a new module folder with an empty project structure.
    The _moduleName_ should match the module name used for the server-side.  See
    <<IDEA and the Client Folder>> if you see the error that vue.ps1 is disabled (on windows
    powershell).
<.> Should install latest Vue 3.x.
<.> The rest of the locally installed modules for use in your client module.
<.> Analysis tool for exploring your package assets for production.



To run your client project, you can run the local development server that was
created by the _vue create_ command above:

[source,script]
.Run Empty Client Module
----
  cd quality
  npm run serve
----

This runs the template client for testing purposes.  You will replace most of the
template html, javascript and Vue files for your module.


==== GUI Setup - Existing Client Module

Once you have cloned the GIT repository, you will need to run these Gradle tasks:

* (once) *npmInit* or *npmInitAll* - Runs the _npm install_ command in the client module(s).
  This downloads the npm libraries used by the client.

* (after updates) *npmBuild* or *npmBuildAll* - Runs the _npm build_ command in the
  client module(s). This builds the production assets.  Typically, this is run after
  client module code changes.

* (after updates) *copyEframeLib* or *copyEframeLibAll* - Copies the current <<eframe-lib>>
  files to your module.   This is needed whenever the source for the <<eframe-lib>>
  changes.



==== GUI Setup - Common Setup

These setup actions apply to new and existing installations.

===== Powershell on Windows

Many Vue/npm commands are shipped as powershell commands (*.ps1).  By default, these are
restricted in powershell.  You will get an error like this:

[source,script]
.Client First Time Setup
----
vue --version <.>


vue : File ..\vue.ps1 cannot be loaded because running scripts is disabled on this
system. For more information, see about_Execution_Policies at https:/go.microsoft.com/...
At line:1 char:1
+ vue --version
+ ~~~
    + CategoryInfo          : SecurityError: (:) [], PSSecurityException
    + FullyQualifiedErrorId : UnauthorizedAccess
----
<.> Command to print current version of vue in the client folder.  Will fail on
    systems with Windows Powershell.

To avoid this, you should add _.cmd_ to the end of the command:

[source,script]
.Client First Time Setup
----
  vue.cmd --version
----

You could also just remove the _.ps1_ file from the global npm folder (_C:\Users\XYZ\AppData\Roaming\npm_)
or enable execution of .ps1 files are described by Microsoft.


===== GIT Exclude File

Node/npm has a lot of files copied to your development folder.  These should be excluded
from the IDEA and GIT since they are generated files or open source libraries.
This means you should have these lines in your project's GIT exclude file:


[source,script]
..git/info/exclude
----
/eframe/src/main/resources/client/         <.>
/eframe/src/client/eframe/node_modules/    <.>
/eframe/src/client/sample/src/eframe-lib/  <.>
----
<.> The production files created by the `npmBuildLib` task.
<.> The client module's dependencies (huge).
<.> The copied <<eframe-lib>> source for support code for each client module.




==== GUI Setup - IDEA

The IDEA setup for npm development is fairly simple.  There are two basic run
configurations.

.Localhost (Dev)

The first is to run the development server as localhost:8081.  This lets you change your
client code and the server will update with those changes without restarting.


[cols="1,1,6"]
|===
|Setting|Value|Description

| *type*| npm| The task is created from the npm template (Add New Configuration).
| *package.json*| package.json| The package-json for the client module.
| *command*| run|
| *scripts*| serve| Starts the dev server with hot-updates for your changes.

|===


.Build

The second is the task to build the production assets for the client pages.
You will run this and then start/restart the micronaut application server to test
your client in a live server.  This will build the assets and store them in the
_src/main/resources/client_ so the development server will have access to them for use
in the live server.

[cols="1,3,6"]
|===
|Setting|Value|Description

| *type*| npm| The task is created from the npm template (Add New Configuration).
| *package.json*| package.json| The package-json for the client module.
| *command*| run|
| *scripts*| build| Builds the production assets for a live micronaut server.
| *arguments*| -- --dest ../../main/resources/client/eframe| This is where the assets
                                          will be created.
                                          This folder is the normal resource folder so that
                                          IDEA will copy them for use in the running development
                                          server.  (The *arguments* starts with two hyphens).

|===

NOTE: Intellij doesn't always copy the _main/resources/client/_ files to the _out_
      folder after a re-build.  We found that a Gradle 'Reload all Gradle Projects' in the
      Gradle window works.  After the reload, you will need to restart the localhost
      process.

===== Excluding the Client Folder from Searches

Since the client assets are copied to the _main/resources/client_ folder, the contents
will show up by default in the IDEA searches.  This is inconvenient. In the IDEA
Project Structure dialog (module _eframe/main_) you can 'exclude' the
_resources/client/eframe_ folder.  (Replace _eframe_ with the client sub-module name).





===== IDEA and the Client Folder

.node_modules

After installing these packages, the IDEA _Commit_ tab will contain thousands of files
from the _node_modules_ folder.  You should exclude this folder.  Select the folder
in the _Project_ tab and choose the _Git_ -> _.git/info/exclude_ option to exclude these
from the Git logic.

This will add it to the _.git/info/exclude_ folder.




==== Client Module Version Dependencies

npm uses two files for version control:

* _package-lock.json_ - The main module version listing for all modules.
  This includes the exact version installed for all modules.
  This file supercedes the _package.json_ when the _npm install_ command is used.
* _package.json_ - The top-level modules used.  Contains the general versions for the
  modules.  This is usually something like '^3.0.7' which means any 3.x version.

The _package.json_ and _package-lock.json_ files are updated when you install a new
module as we did above with the tasks in <<GUI Setup - New Client Module>>.

When building the client modules on other systems from the git source, we use the command
_npm install_.  This installs all of the dependencies specified in the _package-lock.json_
file.  This uses the exact version from the _package-lock.json_ file.  The version from
the _package.json_ is not used for this scenario.

NOTE: The _package-lock.json_ is the primary source of the versioning for npm.
      Unfortunately, this is independent of the _build.gradle_ files.

