
=== GUI Development

ifeval::["{backend}" != "pdf"]
[inline-toc]#<<GUI Module Structure>>#
[inline-toc]#<<GUI Development Tasks>>#

endif::[]

The GUI development environment is somewhat complex due to the hybrid nature.
We use Groovy/Java on the server-side and Vue on the client-side.
This forces us to develop the client-side GUIs in isolation from the server-side.
The client is then served up by the server-side.


==== GUI Module Structure

The basic structure for the modular application will look
something like this:



//workaround for https://github.com/asciidoctor/asciidoctor-pdf/issues/271
:imagesdir: {imagesdir-build}

[ditaa,"clientModulesExample"]
----
+-------------+---------+-------------+---------+
| App Module A| Client  | App Module B| Client  |
|             |         |             |         |
|       c33B  |    c33B |        cYEL |    cYEL |
+-------------+---------+----------+--+---------+
|      Application Core Module     |  Client    |
|                             cGRE |       cGRE |
+--------------------------------+-+------------+
|         Enterprise Framework     |  Client    |
|                                  |            |
+----------------------------------+------------+

----

//end workaround for https://github.com/asciidoctor/asciidoctor-pdf/issues/271
:imagesdir: {imagesdir-src}

Each module can supply a client one or more sub-modules with the assets needed for
the clients.  These client sub-modules will be built using the npm processes typically
used for Vue applications.




The application pages will be organized like this during the production deployment:



//workaround for https://github.com/asciidoctor/asciidoctor-pdf/issues/271
:imagesdir: {imagesdir-build}

[plantuml,"clientPages",align="center"]
.Production Deployment - URL Locations
----
@startuml

node client as "<b>/client"

node eframe as "<b>/eframe"
file flexType [
  <b>/flexType
  --
  FlexType.vue
  flexType.js
]

file logging [
  <b>/logging
  --
  Logging.vue
  logging.js
]

file search [
  <b>/search
  --
  Search.vue
  search.js
]


node mesCore as "<b>/mes-core"
file order [
  <b>/order
  --
  Order.vue
  order.js
]

file orderDashboard [
  <b>/orderDashboard
  --
  OrderDashboard.vue
  orderDashboard.js
  --
  WorkList.vue
  WorkCenterSelection.vue
]

file assyReport [
  <b>/assyReport
  --
  AssyReport.vue
  assyReport.js
]

node mesAssy as "<b>/mes-assy"
file assyDashboard [
  <b>/assyDashboard
  --
  AssyDashboard.vue
  assyDashboard.js
  --
  AssemblyList.vue
  WorkList.vue - <b>mes-core
]

client -- eframe
client -- mesCore
client -- mesAssy
eframe -- flexType
eframe -- logging
eframe -- search

mesCore -- order
mesCore -- orderDashboard

mesAssy -- assyReport
mesAssy -- assyDashboard


@enduml
----

//end workaround for https://github.com/asciidoctor/asciidoctor-pdf/issues/271
:imagesdir: {imagesdir-src}


==== GUI Development Tasks

GUI development involves working with the client sub-module and then moving it to the
production server for deployment.  The basic flow is:

. <<Create Client Page>> - Create/edit the client-side components code.
  This includes .vue and .js file changes.  The developer can use the _npm run server_
  task to allow hot-updates to the running client-side application while they make
  changes.

. _Build the assets_ - Use the _npm run build_ to create the assets.

. _Deploy the client_ - Use the Gradle task _deployClient_ to deploy the client assets
  to the Groovy server.  The server is then restarted.  This makes the compiled
  assets available within a running application server.

. _Build .jar_ - When ready to publish the module, the run-time .jar file is built
  and the assets are included in the .jar file.  This is done by the Gradle
  task _publishToMavenLocal_ task.
   
===== Create Client Page

The client page defines a single endpoint (URL) for the application.  For example,
the CRUD page for the Flex Type records is at '/client/eframe/flexType'.  It is made
up of these elements:

flexType.js - uses PageApp
FlexTypeCrud.vue - Uses CrudTable element



//workaround for https://github.com/asciidoctor/asciidoctor-pdf/issues/271
:imagesdir: {imagesdir-build}

[plantuml,"clientElements",align="center"]
.Client Elements
----
@startuml

node url as "url: <b>/client/eframe/flexType"

file flexType.js  [
  <b>flexType.js
  --
  app = PageApp.createApp(FlexType)
  app.mount('#app')
]

file flexType.vue  [
  <b>flexType.vue
  --
<template>
  <StandardHeader/>
    <<b>CrudTable :value="flexTypes"
               :totalRecords="totalRecords"
               :loading="loading"
               @page="onPage($event)">
   </CrudTable>
</template>]


url -- flexType.js
url -- flexType.vue 



@enduml
----

//end workaround for https://github.com/asciidoctor/asciidoctor-pdf/issues/271
:imagesdir: {imagesdir-src}

The _.js_ file is fairly simple.  Most of the common logic is provided by the PageApp:

[source,javascript]
.Example - page.js
----
/**
 * Basic CRUD page for a single object.
 */

import FlexType from '@/components/eframe/custom/flexType/FlexTypeCrud.vue'
import PageApp from '@/components/eframe/web/PageApp'
import '@/assets/styles/global.css'


const app = PageApp.createApp(FlexType)  // <.>
app.mount('#app')                        // <.>

----
<.> Uses standard features such as Toast, Axios and <<GUI I18n>> support.
<.> Mounts the FlexType crud table in the standard page using the _'app'_ HTML ID.

The _.vue_ file for most Crud pages is also fairly simple.
This uses the CrudTable component:

[source,javascript]
.Example - FlexTypeCrud.vue
----
/**
 * Basic CRUD component for a single object.
 */
<template>
  <CrudTable :columns="columns" :service="service"/>  // <.>
</template>

<script>

import CrudTable from '@/components/eframe/web/CrudTable';
import FlexTypeService from '@/components/eframe/custom/flexType/FlexTypeService'

export default {
  components: {
    CrudTable
  },
  data() {
    return {
      columns: [                                                // <.>
        {field: 'flexType', header: this.$t('label.flexType')},
        {field: 'category', header: this.$t('label.category')},
        {field: 'title', header: this.$t('label.title')},
        {field: 'fieldSummary', header: this.$t('label.fields')},
      ],
      service: FlexTypeService                                  // <.>
    }
  },
}

</script>
----
<.> Defines the standard CRUD page with a header.  The `columns` and `service` values
    are required.
<.> The columns displayed are listed.
<.> The service that implements the `list()` and other CRUD-related methods.
    See <<GUI - CRUD Requirements>> for details.



