
=== GUI I18n

All GUIs must be localized.  The client sub-module supports multiple locales, with varying
support for languages.  The fallback language (English) is fully supported.
All text used on all display elements should be localized.

To support this localization, the client side of the framework supports locale files
for each supported language.  For example, the English file will look something like this:

[source,javascript]
.Locale JS File - en.js
----
export default {
  getLocale() {  // <.>
    return 'en'
  },
  getMessages() {  // <.>
    return {
      label: {     // <.>
        category: 'Category',
        fields: 'Fields',
        flexType: 'Flex Type',
        title: 'Title',
        searchStatusGreen: 'Green',
      }
    }
  }
}
----
<.> Provides the locale (language only supported).
<.> Provides the localized text.
<.> The basic types include (e.g. 'label', 'title', etc.)


These are used in components with the following syntax:

[source,javascript]
.Example - Locale Usage in Vue File
----
<template>
  <Button>{{ $t('label.flexType')  }}</Button>   // <.>
</template>


export default {
  methods: {
    getLabel() {
      return this.$t('label.flexType')}  // <.>
    },
  }
}
----
<.> Use the 'mustache' syntax in the template/HTML section.  The localized text can't
    be used as the content of an attribute.
<.> Use the global _$t()_ syntax within Javascript.


CAUTION: The 'mustache' syntax can't be used in an HTML attribute.  For example this won't
      work:  _<Button label="{{ $t('label.flexType')  }}"/>_.  You will need to
      place the text outside of the attributes as done above or
      use the text as a data element with binding (e.g. _:label="$t('label.cancel')"_).

==== Lookup in GUI Tests

The link:groovydoc/org/simplemes/eframe/test/BaseGUISpecification.html[BaseGUISpecification^] icon:share-square-o[role="link-blue"]
tests will need to verify that labels are looked up correctly from the _en/de.js_ files.
This is done with the utility
link:groovydoc/org/simplemes/eframe/test/WebClientLookup.html[WebClientLookup^] icon:share-square-o[role="link-blue"].
The _WebClientLookup_ class parses the _en/de.js_ file(s) and uses the values from the .js
files for the lookup.

This avoids two mechanisms for localization (.js and .properties).

