
=== GUI Requirements

ifeval::["{backend}" != "pdf"]
[inline-toc]#<<GUI - CRUD Service Requirements>>#

endif::[]

The GUI development environment requires some server and client-side objects
to make the pieces all work together.



==== GUI - CRUD Requirements

To use the helper objects on the client-side, you will need to implement some special
objects.  For example, a Service is needed that will access the CRUD actions on the object
being maintained.


==== GUI - CRUD Service Requirements

The CRUD helper objects require a Service that implements common features for your
object.  This includes methods such as `list()`.

[source,javascript]
.Example - FlexTypeService
----
export default {
  list(options, successFunction) {  // <.>
    const url = '/flexType/list'    // <.>

    window.$page.vue.axios.get(url, {params: options}).then((response) => {  // <.>
      if (successFunction) {
        successFunction(response.data)
      }
    }).catch((error) => {
      window.$page.handleError(error, url)
    })
  },
}
----
<.> The service `list()` method.  See <<Client Service Requirements>> for details.
<.> The server-side URI for this list() method.  This is usually provided by
    the <<BaseCrudController>> class.
<.> The actual call to the `list` URI on the server.  Executed asynchronously.


===== Client Service Requirements

[[client-service-list-parameters]]
====== list() Parameters

The parameters for the list are:

.Parameters
[cols="1,1,6"]
|===
2+|Argument/Option|Description

2+| *options*    | A javascript object with the supported options listed here (*Required*).
|| *count*    | The number of records (page size).
|| *start*    | The first record in the page.
|| *search*   | The search filter (optional).
|| *sort[fieldName]=asc*|  Defines sorting on the given field name with (asc)ending or
                          (des)cending.
2+| *successFunction* | The function called when the list returns values.
                      The object passed to this function is result of the
                      list() request (converted from JSON).  Values include:
                      `total_count` and `data` (the records) (*Required*).

|===


