== GUIs

ifeval::["{backend}" != "pdf"]
[inline-toc]#<<GUI Philosophy and Decisions>>#
[inline-toc]#<<GUI Toolkit>>#
[inline-toc]#<<GUI Pages>>#
[inline-toc]#<<GUI Page Fragments and Dialogs>>#
[inline-toc]#<<GUI Layout>>#
[inline-toc]#<<GUI Configuration>>#
[inline-toc]#<<Definition Pages>>#
[inline-toc]#<<GUI Field Types>>#
[inline-toc]#<<Standard Keys>>#
[inline-toc]#<<Task Menu>>#
[inline-toc]#<<Javascript Libraries>>#
[inline-toc]#<<GUI State Persistence>>#
[inline-toc]#<<GUI Testing>>#
[inline-toc]#<<GUI Guidelines>>#
[inline-toc]#<<Controller Method for Page Display>>#

[inline-toc]#<<Dashboards>>#
[inline-toc]#<<Reports>>#
[inline-toc]#<<markers,Markers (Freemarker Directives)>>#

endif::[]


Standardized GUIs are a key part of the user experience in enterprise applications.
Customers expect your GUIs to work the same way across the entire application.  To keep the
GUIs consistent, the framework provides a set of common GUI markers (HTML-like directives) that
generate the consistent HTML elements.

There are 4 main approaches to GUI implementation:

* Standard GUIs (<<Definition Pages>>, etc).
* Optimized GUIs for User Scenarios
* Configurable <<Dashboards>>
* Hybrid

The standard GUIs are created using some very coarse <<Markers>> such as
<<efShow>> to create most of the standard GUI.
These are designed to be easy to create and are easy to use for simple user scenarios.
These support the basic CRUD actions for most simple domain classes and provides a mechanism for
maintaining complex domain class structures. These GUIs follow the standard  controller/view
approach and use normal controllers.
One key restriction: each view is used to maintain only one top-level domain object.

When using these standard GUIs for complex domain structures, the user experience may
not be optimal.  You may need to create optimized GUIs that meet specific needs.  These are usually
made up of specific field elements in the right order.  You also probably have specific controller
logic to handle these GUIs.

Another option is to use a hybrid of both approaches.  This relies on the ability to use some of
the standard framework markers (e.g. <<efEdit>>) in your custom pages that submit to a custom
controller.

A last option is to use configurable <<Dashboards>> to display more information in panels for your users.

The framework provides a number of Freemarker markers (directives) that help you quickly define
professional GUIs for a number of scenarios. This includes the low-level elements such as
<<efField>> and higher-level markers that define
much of a <<Definition Pages>>.  There are also markers for configurable <<dashboards>> too.

If you use the standard markers and GUIs, then your users will get these features with very little effort on your part:

* Definition GUIs
** <<efShow>>
** <<efCreate>>
** <<efEdit>>
** <<efDefinitionList>>
*** Sortable
*** Searchable
*** Configurable Column Sizes
* <<Field Extensions>>
* <<GUI State Persistence,User Preference Persistence>>

include::guiOther/guiPhilosophy.adoc[]

include::guiOther/guiToolkit.adoc[]

include::guiOther/pages.adoc[]

include::guiOther/pageFragments.adoc[]

include::guiOther/guiLayout.adoc[]

include::guiConfiguration.adoc[]

include::guiOther/definitionPages.adoc[]

include::guiOther/guiFieldTypes.adoc[]

include::standardKeys.adoc[]

include::taskMenu.adoc[]

include::javascript/javascriptOverview.adoc[]

include::guiOther/guiState.adoc[]

include::dashboards/dashboards.adoc[]

include::reports/reports.adoc[]

include::markers.adoc[]








