[[order-assembled-component]]
=== OrderAssembledComponent

An link:groovydoc/org/simplemes/mes/assy/demand/OrderAssembledComponent.html[OrderAssembledComponent^]
icon:share-square-o[role="link-blue"]
defines a single component assembled into an order (and optionally an LSN).
This includes a 'location' mechanism to track where the component was loaded from on the work center setup.
This location can be a bin, shelf or automated feeder location.
See <<guide.adoc#order-assembled-component-guide,Order Assembled Component>> for an overview of this class.

This object records the long-term component history, so there are no real primary keys for the
record.  No records are deleted from this table (except during order archive or other order delete scenarios).
A unique sequence is assigned to each record added.

This element informally belongs to the MES Core <<guide.adoc#order,Order>>
parent.  Since the Order is in another module, the normal child relationship notation can't be used.
Instead, this addition provides a delete check before allowing the work center to be deleted.
It also provides an archive mechanism to keep the component history data long term.

The component's history is tracked using assembly data (e.g. the supplier, lot code, date code, etc)
provided by the operators.  This assembly data is stored in a
<<{eframe-path}/guide.adoc#flexible-fields,Flexible Field>> based on the `assemblyData` Flex Type.
This means the actual assembly data is stored in XML in the field `assemblyDataValues`.
This allows the GUIs to collect configurable data from your operators without forcing any database
or other customizations.

==== Fields

The important fields defined for this object include:


[cols="1,4",width=75%]
|===
|Field | Description

| `orderId`     | This is the order ID this component is assembled on (*Required*).  This is automatically set by the module.
|  `lsn`        | This is the Lot/Serial (LSN) within the order that this component was assembled onto (*Optional*).
| `sequence`    | A unique sequence for this record.  This is assigned automatically.
| `bomSequence` | The sequence from the BOM component requirement (e.g. from ProductComponent) (*Default:* 0).
| `component`   | This is the <<guide.adoc#product,Product>> for the component (*Required*).
| `location`    | The location name.  This is the location the component was loaded from during assembly (*Default:* '@')
| `qty`         | The number of pieces assembled (*Default:* 1.0).
| `assemblyData`    | The <<{eframe-path}/guide.adoc#flexible-fields,Flexible Field>> used to define
                  the assembly data for this component.
                  The actual data is stored in a field `assemblyDataValues` in XML format.
| `userName`    | The user who assembled this component (User ID).  Determined from the request/session.
| `workCenter`  | The work center the component was assembled in (*Optional*).
| `state`       | The current state of this component (can be removed)  (*Default:* ASSEMBLED).
                  See link:groovydoc/org/simplemes/mes/assy/demand/AssembledComponentStateEnum.html[AssembledComponentStateEnum^]
                  icon:share-square-o[role="link-blue"]
|
|===

==== Archiving

This object is archived when the parent order is archived.
