
=== Scan Assy Service

The link:reference.html#scan-assy-service[ScanAssyService^] icon:share-square-o[role="link-blue"]
supports scanning of assembly information in the link:{mes-core-path}/guide.html#scan-dashboard[Scan Dashboard^]
icon:share-square-o[role="link-blue"].
This service adds extensions to the core `ScanService.scan()` method to identify component barcodes
as scanned by the operator.  These scans will provide almost all of the information needed to assemble components.


See link:{mes-core-path}/guide.html#services[MES Core Services^] icon:share-square-o[role="link-blue"]
for details on the core service.

The scan service methods are not exposed by any controller in this module.  The module relies on the
core scan controller to provide access.  This module does provide data entry activities for component assembly
and the related controller.

The easiest component barcode for the operator to work with is the formatted barcode that contains
the component and the lot/serial number to assemble.  This is typically used to assemble purchased products
with muli-part barcodes labels.

Using the simplest internal format, an example barcode looks like this:

  ^PRD^WHEEL-27^VND^ACME_WHEELS^LOT^200171023

This will assemble the component _WHEEL-27_ from the vendor _ACME_WHEELS_ with the lot code
_200171023_.  When scanned with a current order/LSN in the scan dashboard, this module will auto assemble the
component into the order.

This example uses the simple internal format for multi-part barcodes.
For supported barcode formats, see link:{mes-core-path}/guide.html#barcode-formats[Barcode Formats^]
icon:share-square-o[role="link-blue"].

See <<reference.adoc#barcode-prefixes,Barcode Prefixes>> for details on encoding multi-part
barcodes for assembly-related data.


NOTE: This assumes the a Flex Type that requires a vendor and lot code is defined for the _WHEEL-27_ product.
