
=== load

.load(pageMap)

This Javascript function loads one or more activities into a <<guide.adoc#dashboards,Dashboard>> panel.  This is
the main way an activity is started.
Any existing activity is notified with the _'unload'_ event and the new activity's page is displayed.
The dashboard supports displaying multiple activities in a single panel.  The later activities will
wait for the previous activity to finish before loading the next one.
This function is provided in the _dashboard.js_ library.

NOTE: This function is normally used by the dashboard itself.  Your activities will rarely need to use this function.



The parameters supported by the function are:

[cols=".^1,1,5"]
|=== 
|Parameter|Type|Description

.2+|pageMap|Object (map)| Displays a single page in a single panel.  See below for map key names.
|Single or Array of Objects (maps)| Displays a different pages in a different panels.
                          See below for map key names.
|=== 

The `pageMap` can contain a javascript object (map) with these elements for mixed messages:

* `url` - The URI/URL for the activity page to be displayed.   (*Required*)
* `panel` - The panel (name) where the activity is to be displayed. (*Required* - String).


[source,groovy]
.load() Examples
----
// Load a single page in this single panel
dashboard.load({page: 'controller/activityA', panel: 'A'});

// Load 2 pages in one panel and another in a second panel (C).
// activityB waits until activityA is done.
dashboard.load([{url: 'controller/activityA', panel: 'A'},
                {url: 'controller/activityB', panel: 'A'},
                {url: 'controller/activityC', panel: 'C'}]);

----




