
=== Work Center Assembly Service

The <<reference.adoc#workcenterassyservice,Work Center Assembly Service>>
is used to setup and maintain the assembly state of a Work Center.
This service provides features that compliment the core Work Center Service, but does not add
and method extensions to the core service.
See link:{mes-core-path}/guide.html#services[MES Core Services^] icon:share-square-o[role="link-blue"]
for details on the core service.

The service methods are exposed using the
link:groovydoc/org/simplemes/mes/assy/floor/WorkCenterAssyController.html[WorkCenterAssyController^].
These controller methods generally match the inputs and outputs of the services.  The only
difference is they values are passed as XML/JSON strings.

The important service methods are:

* <<reference.adoc#work-center-assy-add-component,addComponent()>> - Adds a component to the work center for assembly purposes.
* <<reference.adoc#work-center-assy-remove-component,removeComponent()>> - Removes a single component from the work center setup.
* <<reference.adoc#work-center-assy-remove-all-component,removeAllComponents()>> - Removes all current components from the work center setup.


[[work-center-assy-add-component-example]]
==== XML Example - addComponent()

To add a component using XML via the controller, use this request _POST_ request:

*uri:* `/workCenterAssy/addComponent`

The XML content passed to the controller contain the component to add:

[source,xml]
.XML Add Component
----
<addComponentRequest>
  <workCenter>ASSEMBLY STATION 3</workCenter>
  <component>WING NUT 27</component>   // <1>
  <location>BIN 27</location>
  <qty>100.0</qty>
  <assemblyData>                     // <2>
    <flexType>LOT</flexType>
    <category>ASSEMBLY</category>
  </assemblyData>

  <assemblyDataValues>  // <3>
    <vendor>ACME</vendor>
    <lot>L12312016-001</lot>
  </assemblyDataValues>
</addComponentRequest>
----
<1> The component is a reference to a product domain record.
<2> `assemblyData` is a Flex Type.  This must come before the field values.
<3> The LOT assembly flex type allows input of `vendor` and `lot` values.


