

=== Application.main()

Micronaut requires an _Application_ class that has a `main()` method to start the application
server.  This enterprise framework has some logic that must be executed before the
`Micronaut.run()` method is called.

For example, the framework stores all date/times in the database with the UTC timezone.
This is done in your `Application.main()` using the
link:groovydoc/org/simplemes/eframe/application/StartupHandler.html[StartupHandler^]
icon:share-square-o[role="link-blue"]:

[source,groovy]
.Application.groovy
----
@CompileStatic
class Application {
  static void main(String[] args) {
    StartupHandler.preStart()  // <1>
    def applicationContext = Micronaut.run(. . .)  // <2>
     . . .
  }
}
----
<1> The preStart logic is run.  This includes setting the default timezone for the JVM to UTC.
<2> The normal Micronaut startup is executed.

This preStartup method is also called in the setup logic for the
link:groovydoc/org/simplemes/eframe/test/BaseSpecification.html[BaseSpecification^]
icon:share-square-o[role="link-blue"] class.


See <<Dates and Timezones>> for details on how timezones are handled.


