
=== Configuration

Micronaut and this framework have many configuration options defined at the application level.
Your application needs to use a number of these settings to take full advantage of the
enterprise framework.


==== application.yml

ifeval::["{backend}" != "pdf"]
[inline-toc]#<<efBootstrap.yml>>#
[inline-toc]#<<build-gradle>>#
endif::[]



The _application.yml_ file controls many of the features of your application.
To avoid issues with the framework, you should use these settings:


===== efBootstrap.yml

// TODO: Move this to application.yml?
The Micronaut startup triggers specific startup logic at various times.  in order to avoid slow
classpath scanning on startup, we require that each framework module has an _efBootstrap.yml_ file.
THis file provides the features needed by the module, such as <<Encoded Types>> and custom fields.



[source,yaml]
.efBootstrap.yml
----

eframe:
  additions: [org.simplemes.eframe.custom.InternalAddition] // <.>

----
<.> A list of addition classes for this module.  EFrame has one internal addition, used to test
    discovery of additions.  It also provides the core <<Encoded Types>>.


==== build.gradle

See <<dependencies>> for details on the changes needed in _build.gradle_ for required plugins.

