
[[domain-controller-or-service]]
=== Domain, Controller or Service?

This section describes the standard approach to breaking up your application logic between
domains, controllers and services within an enterprise application.  This framework doesn't
force you to use a specific approach, but many of the features will be much easier to use
if you follow these guidelines.

The basic responsibilities are:

* *Domain* - Persistence and integrity within the domain and its children.
* *Controller* - API Access from external callers and internal web pages.
* *Service* - Business logic and database transaction control.

The basic interaction between the 3 main classes is shown below for the two most common scenarios:

//workaround for https://github.com/asciidoctor/asciidoctor-pdf/issues/271  and IDEA plugin dir issue
:imagesdir: {imagesdir-build}
ifeval::[{env}==idea]
:imagesdir-build: .asciidoctor
:imagesdir: .asciidoctor
endif::[]

.Domain, Controller and Service Interaction Example
[ditaa,"domainControllerServiceInteraction"]
----
    +---------------+         |          +-------------+
    | REST Client   |  CRUD   |          | Controller  |
    |           cF93+---------+--------->| {io}    c6D6|
    +---------------+         |          +---------+---+
                              |                    |
                              |               /----+-------\
                              |               |   Domain   |
                              |               |        c4CF|
                              |               \--------+---/
                              |                        |       +----------+
                              |                        +------>|          |
                              |                                | Database |
                              |                                |       {s}|
                              |                                +----------+
                              |                                      ^
    +---------------+         |       +-------------+                |
    | REST Client   |  API    |       | Controller  |                |
    |           cF93+---------+------>|{io}     c6D6|                |
    +---------------+         |       +---------+---+                |
                              |                 |                    |
                              |            +----+-------+            |
                              |            |   Service  |            |
                              |            |        cCCC|            |
                              |            +-------+----+            |
                              |                    |                 |
                              |               /----+-------\         |
                              |               |   Domain   +---------+
                              |               |        c4CF|
                              |               \------------/
                              |
                      Client  |  Server
----

//end workaround for https://github.com/asciidoctor/asciidoctor-pdf/issues/271
:imagesdir: {imagesdir-src}

The CRUD (Create, Read, Update and Delete) actions of domain objects does not involve services.
GORM provides a good implementation of these functions.
This framework adds some glue to make the pieces work better together.

When you have non-CRUD requests, there is usually some business logic and transaction control needed.
In many scenarios, multiple top-level domains are used by the business logic.  For these reasons,
we typically put this business logic into a service.  This service is accessed by the client through
the controller to enforce security.  This service then typically works with one or more domain
classes which update the database, usually in a single database transaction.

See <<other-actions-api>> for an example of how the framework makes these actions simpler.

==== What about Domain Validation?

Validation within a domain object and its children is generally handled by the domain class.
This is done to always ensure data integrity of all domain objects.  If the validation spans
multiple top-level domains, then we generally handle this in a service.  One domain should
not know very much about the details of another top-level domain.



