
=== Field Definitions

This framework operates on a centralized field definition for the domain objects.  This includes
defining the core fields and custom fields for that domain.  This framework allows these features:

* Use of core/custom fields in standard definition <<GUIs>>.
* Binding of these fields to complex domain objects, including child records.
* Saving/retrieving values from storage (e.g. from text files for archive purposes).
* JSON access from REST clients.

The basic object structures for these field definitions looks like this:

//workaround for https://github.com/asciidoctor/asciidoctor-pdf/issues/271  and IDEA plugin dir issue
:imagesdir: {imagesdir-build}
ifeval::[{env}==idea]
:imagesdir-build: .asciidoctor
:imagesdir: .asciidoctor
endif::[]

.Field Definitions
[ditaa,"fieldDefinitions"]
----
    +-------------------+
    | FieldDefinitions  |
    |     clazz         |
    |     fields        |
    |               c6D6|
    +--------------+----+
                   |
                   |
                   v 1..N
           +-------------------+
           | FieldDefinition   |
           |      name         |
           |      type     c4CF|
           |      fieldFormat  |
           +-------------------+
                          |
                          |
                          v 1..N
                 +-------------------+
                 |FieldFormat        |
                 |    format(locale) |
                 |    parse(locale)  |
                 |    encode()       |
                 |    decode()   cCCC|
                 +-------------------+

----

//end workaround for https://github.com/asciidoctor/asciidoctor-pdf/issues/271
:imagesdir: {imagesdir-src}

The _FieldDefinitions_ contains the fields for a given object.  These are cached in the groovy
meta class for the object.   In this _FieldDefinitions_  is a list of FieldDefinition objects
which have specific names, types and a _FieldFormatEnum_ element that controls how the value
is convert to/from strings for internal and for GUI use.

These field definitions are accessed like this:

[source,groovy]
.Example for FieldDefinitions
----
def fields = DomainUtils.getFields(Order)

for (fieldDef in fieldDefs) {     // <1>
   . . .
}

----
<1> Access all fields with a simple loop (non-closure).  Also supports the `.each() {}` operator.



