
[[eframe-toolkit-ph]]
=== ph

.ph(height)

This Javascript function converts the given height into the number pixels for the given percentage
or em number. Percentages (e.g. '20%') are converted to pixels as the percentage of the browser
window content height.

This function is part of the <<eframe_toolkit-js>> library.

.Parameters
[cols=".^1,1,5"]
|===
|Parameter|Type|Description

|msg|String or Number| The percentage or number of 'em' units to use for the pixel calculation.
                       An integer without a suffix (e.g. '%' or 'em') is used as-is,
                       which mean pixels.

|===

NOTE: Using 'em' units means using the font-size *2.

[source,javascript]
.Examples
----

var height1 = tk.ph('20%');
var height2 = tk.ph('10em');

----

[[eframe-toolkit-pw]]
=== pw

.pw(width)

This Javascript function converts the given width into the number pixels for the given percentage
or em number. Percentages (e.g. '20%') are converted to pixels as the percentage of the browser
window content width.

This function is part of the <<eframe_toolkit-js>> library.

.Parameters
[cols=".^1,1,5"]
|===
|Parameter|Type|Description

|msg|String or Number| The percentage or number of 'em' units to use for the pixel calculation.
                       An integer without a suffix (e.g. '%' or 'em') is used as-is,
                       which mean pixels.

|===

NOTE: Using 'em' units means using the font-size.


[source,javascript]
.Examples
----

var width1 = tk.pw('20%');
var width2 = tk.pw('10em');

----
