
=== refreshList

.refreshList(listID,args)

This Javascript function refreshes a list, using the current query data and preserving the
current selection (if possible).  If the row data displayed contains a field 'id', then this
function will attempt to restore the user's row selection after the refresh.

This function is typically used pages with the <<efList>>.
This function is part of the <<eframe_toolkit-js>> library.

The arguments are:

[cols=".^1,1,5"]
|===
|Parameter|Type|Description

|*listID*|String| The list's ID (*Required*).
|*arg*|Object| Any arguments to set on the URL for the refresh (*Optional*).
|*finished*|function| A function that is called after the data is loaded (*Optional*).
                     Arguments: `listID`, `data`, `http_request`.  The `data` argument
                     is the parsed JSON response for the given page.
|===


[source,html]
.Example - refreshList()
----
<@efForm id="list">
  <@efList id="theList" columns="order,product,qtyInQueue,qtyInWork,workCenter"
           uri="/order/findWork" model="sample.pogo.FindWorkResponse"/>
<@/efForm>
function workListRefresh() {
  tk.refreshList("theList");
}

----


This example defines a function that will refresh the list when called.



