
== Introduction

ifeval::["{backend}" != "pdf"]

[inline-toc]#<<Stable API>>#
[inline-toc]#<<Dependencies>>#
[inline-toc]#<<Enterprise Framework>>#
[inline-toc]#<<Programming Standards>>#

endif::[]



http://docs.simplemes.org/mes/latest/[SimpleMES^] is THE open source Manufacturing Execution System (http://www.mesa.org/en/modelstrategicinitiatives/MESAModel.asp[MES^]).  The goal of this open source project is to simplify
the complex and time-consuming task of implementing a traditional MES.  The main features are:

* Almost no setup is required.
* Easy configuration.
* Easy customization.

SimpleMES can be used with or without an ERP system.  You can start without an ERP system and later configure
the MES to work with an ERP system.  It is possible to mix ERP and non-ERP orders and other features as you
need.

For a detailed explanation of the many options and features, see the
link:reference.html[Reference^] icon:share-square-o[role="link-blue"].
The link:groovydoc/index.html[Groovy API^] icon:share-square-o[role="link-blue"]
for the SimpleMES contains details on all fields and methods for most
objects/services.

This MES is built on the
link:{eframe-path}/guide.html#[Enterprise Framework^] icon:share-square[role="link-blue"].
Many of the features described
here are fully documented by that plugin.


=== Stable API

Key services in SimpleMES are considered 'Stable APIs' icon:balance-scale[role="green"].
This means the SimpleMES developers will make every effort to retain backward
compatibility with these services.  This does not mean that there will be no changes to these APIs.
It means that most of the changes will not affect older clients who use these APIs.
Typically, later releases will add new, optional fields to the requests.
The returned objects may have new fields added or some existing fields may become optional.
There is always a chance that a breaking change will be needed, but this will rarely happen.

These Stable APIs are flagged in the Doc pages with the note: *Stable API* icon:balance-scale[role="green"].

NOTE: Your code should try to use these Stable APIs and the domain objects whenever possible.
      This will improve the life of your code.



=== Dependencies

This plugin/application requires a number of plugins to work.  Most of these are required
by the <<Enterprise Framework>>:

* <<Enterprise Framework>>

You do not have to include these in your _build.gradle_ file.  The Enterprise Framework depends on
these modules and Gradle will include them in your application.

NOTE: If you include these in your _build.gradle_ file, then you must make sure the versions are
      consistent with the versions this framework requires. The specific versions needed are listed in the
      plugin's _build.gradle_ file.

==== Enterprise Framework

The link:{eframe-path}/guide.html#[Enterprise Framework^] icon:share-square[role="link-blue"]
plugin is a special dependency.  This plugin was developed
in conjunction with this MES application.  The framework provides much of the 'enterprise' level
functionality such as customization, standard GUIs and API support.


==== Programming Standards

This module conforms to the
link:{eframe-path}/guide.html#programming-standards[Enterprise Framework^] icon:share-square[role="link-blue"]
coding standards.

