
=== API Testing

Complex enterprise applications have many API entry points to test.
Much of the API testing can be done by calling your controller methods directly from the
test code.  But you DO need to verify that these methods work in a real HTTP server environment.
That testing should focus on handling of the inputs from the request and formatting the response.

You should not test every business scenario in an API test.  The API tests mainly are used to
verify that the controller is mapped with the correct URI and inputs/outputs.
Your unit test (non-API test) should test the fringe cases and all business logic/paths.

This framework makes it easier to test the APIs by using the base specification
link:groovydoc/org/simplemes/eframe/test/BaseAPISpecification.html[BaseAPISpecification^]
icon:share-square-o[role="link-blue"].
This class provides some key features for testing real HTTP requests:

* `login()` - Logs a user in for later API/REST test calls.
* `sendRequest()` - Sends a request to the server via HTTP.

These provide the ability to login to a running test  server (embedded) and send requests
to the server.

==== BaseAPISpecification


[source,groovy]
.Example API Testing
----
class UserPreferenceControllerAPISpec extends BaseAPISpecification {

  def "verify that findPreference works with real HTTP requests"() {
    given: 'a dialog state is saved'
    UserPreference.withTransaction {
      PreferenceHolder preference = PreferenceHolder.find {
        page '/app/test'
        user SecurityUtils.API_TEST_USER
        element '_dialogX'
      }
      def dialogPreference = new DialogPreference(width: 23.4, height: 24.5, left: 25.6, top: 26.7)
      preference.setPreference(dialogPreference).save()
    }

    when: 'the request is made for a logged in user'
    login()
    def res = sendRequest(uri: '/userPreference/findPreferences?pageURI=/app/test&element=_dialogX') // <1>

    and: 'the response contains the right data'
    . . .
  }
}
----
<1> The request is sent and the response should be Ok (200).

The `sendRequest()` method has several options.  See the Javadoc for
link:groovydoc/org/simplemes/eframe/test/BaseAPISpecification.html[BaseAPISpecification^]
icon:share-square-o[role="link-blue"] for details.



==== API Security Testing

All APIs are accessed via a controller.  Each controller should have security defined for each
public method.  The <<Controller Test Helper>> provides a simple way to verify that each method
has the right declarative security annotation (_@Secured_).

In general, you should not need to test these annotations in your controller API testing.
