
==== Assemble Component Dialog

*uri:* `/orderAssy/assembleComponentDialog`

This dialog page displays the data entry fields needed for a single component assembly.
It is not a general purpose dashboard activity.
This dialog triggered from the <<Assembly Activity>>.


This activity publishes these events:

* <<ORDER_COMPONENT_STATUS_CHANGED>> - Published when the component is assembled.

===== Supported Input Parameters

This dialog page requires some input parameters via the URL for the dashboard.
The supported values include:

* `order` -  The order to assemble a component for. (*Required*)
* `lsn` -  The lsn to assemble a component for (*Optional*).
* `component` - The component to display the dialog for (`component` or `bomSequence` is *Required*).
* `bomSequence` - The OrderBOMComponent record's sequence for the component to assemble.
                  If missing or 0, then a non-BOM component is assembled
                  (`component` or `bomSequence` is *Required*).
* `assemblyDataType` - The link:guide.html#flex-type[Flex Type^] icon:share-square-o[role="link-blue"] that
                   defines the data fields to collect from the user
                   (*Default:* Assembly Data Type from the BOM component).
                   This is the FlexType's UUID.
