

[[assembly-activity]]
==== Assembly Activity

*uri:* `/orderAssy/assemblyActivity`

This assembly activity displays the components required for the selection (order or LSN).
This shows the list of required components along with their current assembly status (fully
assembled, etc).

This activity is designed to work in the
link:{mes-core-path}/guide.html#scan-dashboard[Scan Dashboard^] icon:share-square-o[role="link-blue"]
and with a standard
link:{mes-core-path}/guide.html#dashboard-work-center-selection[Work Center Selection^] icon:share-square-o[role="link-blue"]
activity.

This activity responds to these events:

* ORDER_LSN_STATUS_CHANGED - This activity refreshes the component list.
* ORDER_LSN_CHANGED - This activity refreshes the component list.
* <<ORDER_COMPONENT_STATUS_CHANGED>> - This activity refreshes the component list.
* <<DISPLAY_ASSEMBLE_DIALOG>> - This activity displays the data entry dialog <<Assemble Component Dialog>>
                                to collect the assembly data for one component.

===== Supported Input Parameters

This activity supports some input parameters via the URL for the dashboard.
The supported values include:

* `order` -  The order to display the assembly state for. If not given, then no data is displayed.
* `lsn` -  The lsn to display the assembly state for.


