

=== Scan Events

The scan events are triggered by the scan processing in the MES Core
link:{mes-core-path}/guide.html#scan-service[ScanService^] icon:share-square-o[role="link-blue"].
A scan event is used to tell the client to execute a specific client-side action due to some processing on
the server.  This includes events such as pressing a button in the GUI, refreshing due to status changes and
to indicate what order/LSN was scanned.

These events are created as a ScanAction and then are automatically published as an event in the scan dashboard.
See link:{eframe-path}/guide.html#dashboard-events[Dashboard Events^] icon:share-square-o[role="link-blue"]
for details.

==== ORDER_COMPONENT_STATUS_CHANGED

This scan action/event indicates that a component was assembled into or removed from an order/LSN.
This is generally triggered by a scan of an encoded component for the current order/LSN in the scan dashboard.

This corresponds to server-side action
link:groovydoc/org/simplemes/mes/assy/system/AssembledComponentAction.html[AssembledComponentAction^]
icon:share-square-o[role="link-blue"].

===== Event Properties

The main properties of this scan event are:

* `type` - _ORDER_COMPONENT_STATUS_CHANGED_
* `order` - The order the component was assembled into/removed from.
* `lsn` - The LSN the component was assembled into/removed from (optional).
* `component` - The component that was assembled/removed.
* `bomSequence` - The component's bom sequence that was assembled/removed (optional).

==== DISPLAY_ASSEMBLE_DIALOG

This scan action/event indicates that a the assembled component dialog should be displayed for
a specific order/LSN and component.  This is generally done for components that have some `assemblyData` to be
entered.
This is generally triggered by a scan of a component for the current order/LSN in the scan dashboard.
This event usually displays the <<Assemble Component Dialog>>.

This corresponds to server-side action
link:groovydoc/org/simplemes/mes/assy/system/DisplayAssembleDialogAction.html[DisplayAssembleDialogAction^]
icon:share-square-o[role="link-blue"].

===== Event Properties

The main properties of this scan event are:

* `type` - _DISPLAY_ASSEMBLE_DIALOG_
* `order` - The order the component to assemble into.
* `lsn` - The LSN the component to assemble into (optional).
* `component` - The component that should be assembled.
* `bomSequence` - The component's bom sequence (optional).
* `assemblyData` - The Flex Type used to collect the data.  This is the flex type's primary key.

