
=== Product

A link:groovydoc/org/simplemes/mes/product/domain/Product.html[Product^]
icon:share-square-o[role="link-blue"] is a part or object
that is produced on your shop floor or purchased from external sources.  This is sometimes
known as a part number or model number.  This product
defines the optional <<Routing>> needed to produce the product.

Products can be imported, exported, changed and deleted using the standard SimpleMES REST <<API>>.

See link:guide.html#product[Product^] icon:share-square-o[role="link-blue"]
for an overview.

==== Fields

.Important Fields - Product
[cols="1,4",width=75%]
|=== 
|Field | Description

| *product*| The Product name.(*key field*)
| *title*| The title (short description) of the product.
| *lsnTrackingOption* | Defines if <<lsn,LSNs>> are used with the product.  Affects how
                        orders can use LSNs.
| *lsnSequence* | The LSN sequence to use.  If not specified, then LSNs will not be created
                  for the order on creation.  If not defined, then no LSNs will be
                  automatically created for orders.
| *lotSize* | The lot size (size of child LSN if LSNs are used).
| *operations* | The list of operations, if this Product needs a Product-level routing.
| *masterRouting* | Defines a shared master routing to be used to produce this product.
                    This is ignored if the Product-level `operations` are defined.
|
|=== 





