
=== Routing

ifeval::["{backend}" != "pdf"]

[inline-toc]#<<Product Routing>>#
[inline-toc]#<<Master Routing>>#
[inline-toc]#<<Order Routing>>#
[inline-toc]#<<routing-fields>>#
[inline-toc]#<<OperationTrait>>#

endif::[]

All routings in SimpleMES have some common characteristics.  They have a list
of operations and support some common methods
See link:groovydoc/org/simplemes/mes/product/RoutingTrait.html[RoutingTrait^]
icon:share-square-o[role="link-blue"] for details.

These operations can be simple actions such as ASSEMBLE or TEST. They may also
be a composite operation that is made up of several actions that are not tracked
individually within SimpleMES.

Some examples operations are:

* 10 - Assemble
* 20 - Paint
* 30 - Pack
* 40 - Test

The routing may be a master routing that can be used on multiple products or it may
be specific to a single product. This decision is made when defining the product.

Routings can be imported, exported, changed and deleted using the standard SimpleMES REST <<API>>.
The specific routing for a product can be imported as part of the product import.

==== Master Routing

The _MasterRouting_ is a pre-defined routing that is used for more than one Product.  These
have a `routing` key field and a `title` field.  These master routings are maintained in the
Master Routing definition GUIs.

==== Product Routing

The _Product_ has a list of operations and implements the RoutingTrait. It is used for the
single product.

==== Order Routing

The _Order_ has a copy of the list of operations from the Master or product routings.


[[routing-fields]]
==== Fields

The most important fields include:

.Important Fields - Routing
[cols="1,4",width=75%]
|===
|Field | Description

| *routing*| The routing name (*key field, MasterRouting Only*).
| *title*| The title (short description) of the routing (*MasterRouting Only*).
| *operations* | The list of sorted operations for this routing.  See <<OperationTrait>> below.
|=== 


==== OperationTrait

A link:groovydoc/org/simplemes/mes/product/OperationTrait.html[OperationTrait^]
icon:share-square-o[role="link-blue"] is a single operation needed to manufacture a
<<Product>>.
These operations can be simple actions such as ASSEMBLE or TEST. They may also be a
composite operation that is made up of several actions that are not tracked within
SimpleMES.

The primary key for the operation is the `sequence` (an integer).  The `title` is used
mainly for display purposes.


.Important Fields - RoutingOperation
[cols="1,4",width=75%]
|===
|Field | Description

| *sequence* | The sequence the operation should be performed in (*key field*, integer).
| *title*    | The title (short description) of this operation.  This is usually visible to the production operator.
|===




