
=== LSN

An LSN (Lot/Serial) a single order.

This link:{mes-core-path}/guide.html#lsn[LSN^] icon:share-square-o[role="link-blue"]
is provided by the core MES module.

=== Order

A single order from a customer to produce a quantity of a product.
This is sometimes known as a job or shop order.

This link:{mes-core-path}/guide.html#order[Order^] icon:share-square-o[role="link-blue"]
is provided by the core MES module.

=== Product

A Product is a part or object that is produced on your shop floor or purchased from external sources.
This is sometimes known as a part number or model number.

This link:{mes-core-path}/guide.html#product[Product^] icon:share-square-o[role="link-blue"]
is provided by the core MES module.

This module adds the <<product-component-guide>> child list to the Product domain to track the required components
for a product.


=== Routing

A Routing is a sequence of operations needed to manufacture a <<Product>>.
These operations can be simple actions such as _ASSEMBLE_ or _TEST_. They may also be a composite operation
that is made up of several actions that are not tracked within SimpleMES.

This module adds a new flag to the RouterOperations to control when automatic assembly is done on
processed Orders or LSNs:

  `assemblyMode` - The auto assembly mode to be used for this operation.

This is am link:groovydoc/org/simplemes/mes/assy/AssemblyModeEnum.html[AssemblyModeEnum^]
icon:share-square-o[role="link-blue"].


When the `assemblyMode` is set to anything other than _NONE_, the `start()` or `complete()` methods will
automatically assemble the appropriate components from the work center's components into the order or LSN.



=== Work Center

A Work Center is a machine or location where a manufacturing operation is performed.
It can also refer to the people at a location where the operation is performed.

This assembly module provides additions to the core
link:{mes-core-path}/guide.html#workcenter[Work Center^] icon:share-square-o[role="link-blue"] domain and services.

This assembly module provides:

* Assembly Setup
* Support for <<work-center-component-guide,component>> locations (e.g. bins, hoppers or other storage location).
* <<work-center-component-guide,Work Center Component>> Replenishment

=== Flex Type

Provides user-defined data types. The framework supports these user-defined fields directly using
link:{eframe-path}/guide.html#flex-types[Flex Types^] icon:share-square-o[role="link-blue"].

The user-defined field values are stored in a large string column in the database as JSON.

