
=== LSN

An
link:groovydoc/org/simplemes/mes/demand/domain/LSN.html[LSN^] icon:share-square-o[role="link-blue"]
(Lot/Serial Number) is a lightweight element of an <<Order>>. This is the finest level of
tracking possible in SimpleMES. An LSN has a quantity and a status.  A quantity of 1.0 means this
is a a serial number. The default quantity for an LSN is defined at the <<Product>> level.

See link:guide.html#lsn[LSN^] icon:share-square-o[role="link-blue"] for an overview.

Tracking within SimpleMES is performed mainly at the order level, but
it is possible to track at finer levels as needed.  You may track work at these levels,
interchangeably:

* Order Only
* Order and LSN
* LSN Only

LSNs may be assigned at order release time or later as needed.  LSNs may be globally unique or can
be unique within a given Product.  SimpleMES will attempt to find the appropriate LSN and
some GUIs will prompt the user if multiples are found.  In most cases, you may also use an
optional quantity when processing work on the shop floor.

The <<WorkService>> is used to determine what levels an order/LSN can be processed
at.  The basic `start()` and `complete()` actions are defined within this service.

`LSNs` can't be imported on their own.  They can be imported, exported, changed and deleted as
part of the `Order`. You will use the normal SimpleMES <<API>> for this.

==== Fields

The fields defined for this object include:


.Important LSN Fields
[cols="1,4",width=75%]
|=== 
|Field | Description

| *order*| The order the LSN belongs to.(*key field*)
| *lsn*| The lot/serial number's name.  During creation, if the `lsn` is not given, then the appropriate <<LSNSequence>> is used to generate the name.(*key field*)
| *status*| The LSN's overall status.  Other fields determine the finer-grained status at
            various stages or processing.  See
            link:guide.html#status[Status^] icon:share-square-o[role="link-blue"] for an overview.
| *qty*| The basic build quantity for the LSN.  This is the number of pieces to be built.
| *qtyInQueue*| The quantity in queue waiting to be processed.
| *qtyInWork*| The quantity currently in work (being processed).
| *qtyDone*| The quantity that has been completed for this LSN.
|===


NOTE: Because this LSN has a combination primary key of `order` + `lsn`, the API calls using
      JSON need
      to be a little more complex.  For example:

[source,json]
.JSON LSN Request
----
{
  "order":"M1001",
  "lsn":"SN2001"
}
----

If the `lsn` (_SN2001_ above) is unique, then you can leave off the `order` element.






