
=== GUI Layout

ifeval::["{backend}" != "pdf"]

[inline-toc]#<<Absolute Sizes>>#
[inline-toc]#<<Page Options>>#

endif::[]



A clean simple layout is a must for enterprise applications.   It is also important that the
GUIs display correctly on a number of size devices.  One key part of this 'look and feel' is
a flexible layout approach.

This enterprise framework uses a third-party <<GUI Toolkit>> to display the GUIs.  This toolkit
provides the basic layout mechanism, using the 'layout' view with a few consistent values.

To understand layout issues, this section will use the standardized layout:


//workaround for https://github.com/asciidoctor/asciidoctor-pdf/issues/271  and IDEA plugin dir issue
:imagesdir: {imagesdir-build}
ifeval::[{env}==idea]
:imagesdir-build: .asciidoctor
:imagesdir: .asciidoctor
endif::[]

.GUI Layout
[ditaa,"guiLayout"]
----

+----------------------------------------------------------+
|                       Header  c47C                       |
+----------------------------------------------------------+

 +--------------------------------------------------------+
 |                       Messages                         |
 |                       Key Fields                       |
 +--------------------------------------------------------+
                   (Optional Tab Bar)
 +--------------------------------------------------------+
 |                     Data Fields                        |
 |                                                        |
 |                                                        |
 |                                                        |
 |                                                        |
 |                                                        |
 |                                                        |
 |                                                        |
 |                                                        |
 |                                            cCDF        |
 +--------------------------------------------------------+

----

//end workaround for https://github.com/asciidoctor/asciidoctor-pdf/issues/271
:imagesdir: {imagesdir-src}

The 'header' section is the <<Standard Header>> and contains links to the home page and to logout.

The 'messages and key fields' section show any error/info/warning messages.  See <<Message Display>>
for details.

The 'data fields' section content will depend on the page being displayed.  In most definition GUIs,
this will contain the input fields and optionally a Tab Bar if there are too many fields for one
page.  These data fields are usually organized as shown below:

//workaround for https://github.com/asciidoctor/asciidoctor-pdf/issues/271  and IDEA plugin dir issue
:imagesdir: {imagesdir-build}
ifeval::[{env}==idea]
:imagesdir-build: .asciidoctor
:imagesdir: .asciidoctor
endif::[]


.Data Field Layout
[ditaa,"guiDataFieldLayout"]
----

                        +---------------------------------+
                Label1  |Text Field               cCDF    |
                        +---------------------------------+

                        +-----------------------+
                Label2  |Drop Down      cCDF    |
                        +-----------------------+

                        +-------------------------------------+
                        |                                     |
                Label3  |Text Area                    cCDF    |
                        |                                     |
                        +-------------------------------------+

   |         20%      | |              70%                    |
   +------------------+ +-------------------------------------+

----

//end workaround for https://github.com/asciidoctor/asciidoctor-pdf/issues/271
:imagesdir: {imagesdir-src}

The labels will be in a column that takes up 20% of the width.  The field values will take
up 70% of the rest of the page.

This layout allows the page to grow and for the large fields (e.g. text area) to expand on
larger devices.

NOTE: These sizes (20%, etc) are evaluated when the page is displayed.  If you resize the browser
      then you may need to refresh the page to get expanded fields/grids.



==== Absolute Sizes

This <<GUI Toolkit>> does an excellent job, so long as you work with absolute sizes.
Of course, this causes problems when a page is displayed on various devices.  To avoid this problem,
the enterprise framework uses a percent size for key elements and then converts the percentage
to pixels.  This absolute pixel size is based on the current screen size.

This allows the underlying widgets to use a width/height like this:


[source,javascript]
.Examples Percent Sizing
----

{view: "text", id: "${id}", width: tk.pw('20%') . . .},  // <.>

----
<.> The `tk.pw()` function returns the given percent of the screen width in pixels.


==== Page Options

Another way to avoid hard-coding absolute pixel sizes is to use Page Options from the
<<eframe-js>> library.  This allows javascript to set an option for the page.
Widgets on the page can then use these options for their layout needs.

This will allow features such as a page-specific label width (see <<efShow>>).
This marker right-aligns all of the labels on the left side
of the <<definition-pages,show page>>.  By default, this label area is 20% of the window width.
Sometimes, labels are too long to fit.  To fix this, you can specify a label width for that page:

[source,html]
.efShow - Label Width
----
<@efShow labelWidth="25%"/>
----

The <<efShow>> generates the javascript to set the option to '25%':

[source,javascript]
.Set Page Option - Generated Code
----
ef.setPageOption('labelWidth','25%');
----

When the text field is rendered, the label width is set to this page-specific value:

[source,javascript]
.Using Page Option - TextFieldWidget
----
 . . .

 {view: "label", label: "Order *", align: "right",   // <.>
  width: tk.pw(ef.getPageOption('labelWidth','20%')) // <.>
 }

 . . .

----
<.> Other toolkit-specific options for the label.
<.> Use the page option, with a fallback to '20%'.  This is then converted to pixels
    for the actual display width.





