
=== GUI Philosophy and Decisions

Since GUIs are so important to your application's success, we made some key decisions
on how to define the GUIs and how they work with the server-side.
These decisions are based on some simple GUI philosophies:

* <<Limiting Logic on the Client>>
* <<Use Normal HTML Form Submit Approach>>
* <<Limit High-frequency Client/Server Interaction>>

None of these decisions are perfect.  They all involve trade-offs.  We tried to make sure
the end result is a smooth operating application, even in slow environments.
There are scenarios where the framework supports a more interactive approach such
as <<Dashboards>>.

You can do things differently if you prefer.  It just means the framework won't be helping
as much as it could. 

==== Limiting Logic on the Client

Javascript is a less-structured language than Groovy/Java.    This means the chance of errors
is greater with the client-side code than with the server-side.  It is also more difficult
to write tests for the javascript code.  To accurately test it, you would need to run the tests
in the same engine as the browser uses.  This is certainly possible, but it adds complexity
to the application.

The only certain way to test the client side code is in a browser with GUI-level testing.  This is
the slowest and most fragile kind of testing.  To reduce this GUI testing, we try to keep the logic
on the client to a minimum.

So the goal is to only put logic in the javascript code when absolutely necessary.

==== Use Normal HTML Form Submit Approach

It was also possible to use a single-page application style of design for the <<Definition Pages>>.
This would send a 'save' via Ajax to the server and then display the results.
This would be acceptable from the user's perspective, but would force some extra logic
in the client code.  This means more javascript to develop/test.

For example, the client side would have to convert to/from locale-specific formats.
The Jackson/JSON Rest API needs dates and numbers in a locale-neutral
format.  This means more javascript (GUI) tests to verify the formats are handled correctly.

Instead, we chose to submit the data like a normal HTML form with the fields in the locale-specific
state (as the user entered them).  Then, the server-side would be responsible for converting
them to internal Java values (e.g. Date).  The server-side would then re-direct the page to the
success page (show) or failure page (re-display with validation errors highlighted).

This is much easier to unit test on the server.  Client-side testing has some browser-specific
issues that can usually be ignored in these scenarios.

==== Limit High-frequency Client/Server Interaction

We also wanted to make sure that your application would work over slower network connections.
This means your users may have to wait for the page to display, but they won't have to wait between
each keystroke or mouse click.

This means avoiding a lot small server requests that the user must wait on.  In particular, we
don't ever want to send a request after each field exit (on normal pages).

With good caching on the browser, most pages can be displayed with one or two requests to the server.


