
== Controllers

ifeval::["{backend}" != "pdf"]

[inline-toc]#<<Controller Names>>#
[inline-toc]#<<Controller Method Names>>#
[inline-toc]#<<Controller Security>>#
[inline-toc]#<<Controller Base Classes>>#
[inline-toc]#<<controller-logging,Logging>>#
[inline-toc]#<<Controller Task Menus>>#
[inline-toc]#<<Standard Domain Model and Markers>>#

endif::[]

Your controller classes have a few requirements to be easily used by various pieces of the
framework. Your controller classes should be in proper packages, but that is not required.
See <<controller-testing>> for details on testing.

=== Controller Names

Your controller class provide the main access to your application for GUIs and JSON access.
In general, you should follow the normal Micronaut standard: domainName plus  _'Controller'_.
For example, the domain class _Order_ should
have a corresponding controller named _OrderController_.

=== Controller Method Names

To make the application and framework simpler, the framework assumes some specific naming
conventions.  This is part of the 'coding by conventions' that we try to apply to the
framework.  It makes your application-level code simpler.

====  Controller name, URI and View path are the same

The controller name is the same as the page.  For example, controller Order has these views:

  views/order/index.ftl
  views/order/show.ftl
   . . .

In the controller, you have these methods:

[source,groovy]
----
@Secured("ADMIN")
@Controller("/order")
class OrderController {

  @Get("/")
  StandardModelAndView index(@Nullable Principal principal)  // <.>

  @Get("/show/{i}")
  StandardModelAndView show(String i, @Nullable Principal principal)  // <.>

}
----
<.> Usually provided by <<BaseCrudController>>.
<.> Usually provided by <<BaseCrudController>>.

This allows some underlying code (such as <<BaseCrudController>>) to handle a lot of the basic
features of the show and index pages.  This reduces the amount of code you have to write.


=== Controller Security

See <<security,Security>> for details on securing your controllers.  By default all controller
methods must be secured.  See <<controller-testing>> for details on testing these security
requirements.

NOTE: To enable access, all controller methods should have a _Principal_ argument:

[source,groovy]
----
@Secured("ADMIN")
@Controller("/path")
class AController {

  @Get("/list")
  Map list(HttpRequest request, @Nullable Principal principal) {
    . . .
  }
}
----

If the _Principal_ argument is not an argument to your methods, then you will get an access denied
response (*HTTP Status 403-Forbidden*).

=== Controller Base Classes

Most of your controllers that support CRUD and API access can use common implementations of those
functions.  For example, a CRUD controller can implement the
link:groovydoc/org/simplemes/eframe/controller/BaseCrudController.html[BaseCrudController^]
icon:share-square-o[role="link-blue"].  This will provide common methods for CRUD actions
that the standard <<GUIs>> will use.  This will reduce your code considerably.

You can override these methods with your own implementation.

Your controller will define the HTTP path your controller handles and the overall security
requirements for methods:

[source,groovy]
----
@Secured("ADMIN")    // <1>
@Controller("/user") // <2>
class UserController extends BaseCrudController {
  . . .
}
----
<1> All methods require the _ADMIN_ role.
<2> This controller handles request on the _/user_ path (e.g. _/user/list_).


The common controller base classes include:

* <<BaseController>> - Provides standard error handler.
* <<BaseCrudController>> - Provides standard CRUD actions.
* <<BaseCrudRestController>> - Provides standard REST/JSON API actions.

=== BaseCrudController

ifeval::["{backend}" != "pdf"]

[inline-toc]#<<domainClass>>#
[inline-toc]#<<getView Method>>#
[inline-toc]#<<bindEvent Method>>#
[inline-toc]#<<Delete Actions>>#

endif::[]



The link:groovydoc/org/simplemes/eframe/controller/BaseCrudController.html[BaseCrudController^]
icon:share-square-o[role="link-blue"] base class provides many of the common controller methods
used in standard CRUD pages. This includes methods like _list(), create(), edit()_ etc.

GUI <<Markers>> such as <<efList>> rely on methods in this base class to display data for the domain.

==== BaseCrudController Options

The _BaseCrudController_ has a few optional fields/methods you can use to adjust the behavior
of the standard methods.  For example, you can specify a different domain class than the default name.

===== domainClass

Sometimes, you will need to associate a controller with a different domain class than the default
name.  You can do this with the static field:

[source,groovy]
.Example Domain Class Override
----
@Controller("/somePath")
class SomeController extends BaseCrudController {

   static domainClass = Order

}
----
This affects the <<BaseCrudController>>.


Also, you should implement a number of methods as described in <<Repository Requirements>>.

===== getView Method

The view page file names are usually derived from the controller's domain class.
The default behavior may be wrong for your situation.  You can override the `getView()`
method in your controller class to use any path needed.  Keep in mind that the view system
adds _'views/'_ to the view to find the real view path.


[source,groovy]
.Example View Path Override
----
@Controller("/somePath")
class SomeController extends BaseCrudController {

  String getView(String methodName) {
    return "someOtherPath/forViews/$methodName"  // <1>
  }

}
----
<1> An alternate path is generated, using the basic method name.

===== bindEvent Method

If you use the <<BaseCrudController>>, then you may need to do additional binding of HTTP parameters
to the domain object upon save.  When the `editPost/createPost` methods are called, then they
will call your `bindEvent()` method to do the additional binding/validations.

You can also trigger a validation error as shown below.  This example shows how a user's password
can be changed by entering the value twice in a GUI (`_pwNew` and `_pwConfirm` fields).
This `bindEvent()` method makes sure the two values are the same.


[source,groovy]
.Example - bindEvent() - Password Confirm Validation
----
void bindEvent(Object record, Object params) {
  if (params._pwNew) {
    if (params._pwNew != params._pwConfirm) {   // <.>
      throw new Exception(...)
    } else {
      record.password = params._pwNew  // <.>
    }
  }
}
----
<.> Compares the new password and the confirmation password.  If different, then an error
    is triggered.
<.> If valid, then the password is stored in the User record for later encryption upon save.


===== Delete Actions

The <<BaseCrudController>> and <<BaseCrudRestController>> `delete()` methods will delete the given
domain record and all of its children.  This method
will also delete any related records that are not true child records.  This uses the same
`findRelatedRecords()` mechanism used by <<Archiving Related Records>>.

NOTE: The related records are deleted before the main record is deleted.  This means you have
      take care of referential integrity issues.

=== BaseCrudRestController

The link:groovydoc/org/simplemes/eframe/controller/BaseCrudRestController.html[BaseCrudRestController^]
icon:share-square-o[role="link-blue"] base class provides many of the common controller methods
used in standard CRUD <<Rest API>> methods. This includes the HTTP methods _GET, PUT, POST and DELETE_.

==== Endpoints

The _BaseCrudRestController_ has a the normal Rest-style API endpoints:

* {domain}/crud/uuid *(GET)* - Read a single record by UUID or primary key.
* {domain}/crud (*POST)* - Create single record.
* {domain}/crud/uuid *(PUT)* - Update a single record.
* {domain}/crud/uuid *(DELETE)* - Delete a single record.

The ID-based methods use the URL to define the UUID or primary key for the the record being processed.
See <<Rest API>> for details.


=== BaseController

The link:groovydoc/org/simplemes/eframe/controller/BaseController.html[BaseController^]
icon:share-square-o[role="link-blue"] base class provides the single _error()_ handler method.
This returns an exception in a standard format for display to the user.  This is a local error handler.
Currently, no global error handler is provided for controllers.

The standard error response JSON look like this:

[source,json]
----
{
  message: {
   "level": "error",
   "code": 1003,
   "text": "Order 'M1657334' is not enabled"
  }
}
----

See <<Info/Warning Messages to Clients>> for more details.

=== Controller Task Menus

Controllers are the main way users will access your application from a browser.
The framework provides a way to define <<Task Menus>> from your controller.  These usually
refer to the main (root or index) page of your controller.

Also, you can mark these tasks as a `clientRootActivity`.  This means the the javascript
methods for this page will be able to write log messages using a standardized logger naming
convention.
To support <<Javascript Client Logging>>, you should indicate what pages (URIs) that
a given controller provides.  This is done with the variable `taskMenuItems`:


[source,groovy]
----

@Secured("ADMIN")
@Controller('/order')
class OrderController {

  def taskMenuItems = [new TaskMenuItem(folder: 'demand:50.order:100',
                                        name: 'order',
                                        uri: '/order',
                                        clientRootActivity: true,       // <.>
                                        displayOrder: 101)]

  @Get('/')
  @Produces(MediaType.TEXT_HTML)        // <.>
  String index() {
   . . .
  }

}
----
<.> This URL is the client logger root for this controller.  This means the logger
    _'client.order'_ logger will be used to control the logging level on the client
    for this controller's pages.  (*Default*: is true, so this value is normally not needed).
<.> An index page handler.

You can test your settings in the <<Controller Test Helper>>.  You will need to specify
the details on the Task Menu Item expected in the controller.


==== Standard Domain Model and Markers

This <<BaseCrudController>> stores the domain object being displayed/edited in the standard location
for your .ftl/HTML pages to display.  The domain object is stored in the <<Markers>> context data
as described in <<Markers and Models>> under the domain name (e.g. _'order'_).

If you have your own controller methods that create a StandardModelAndView, then you should make sure
your domain object is stored with this same naming convention.

You can access this in your .ftl/HTML files:


[source,html]
.Use of the Domain Model
----

Order: ${order.order}  // <.>
Qty to Build: ${order.qtyToBuild}
Due Date: ${order.dueDate}

----
<.> The fields from the _Order_ record are displayed in the page.


