
=== Potholes

Micronaut and the other tools are great, but they have some pot holes you need to avoid.
These pot holes are not terribly bad problems, but we have lost some time discovering them and
working around them.  This section is meant to help you avoid some of those pot holes.

==== groovy.lang.Singleton Used

Groovy provides the `groovy.lang.Singleton` annotation without an explicit import.
This annotation is not compatible with the one needed by Micronaut (_javax.inject.Singleton_).
You must explicitly import the correct one:

  import javax.inject.Singleton

If you use the wrong annotation, then your bean will not be created.

NOTE: Intellij will not flag the wrong `@Singleton` annotation.  You will have to manually
      insert the above import statement.

==== Beans Defined in .java Files

Micronaut works well with Java or Groovy source trees.  It gets a little confused when you have
beans (e.g. @Singleton or @Controller) in Java and Groovy in the same module.  This causes
Micronaut to create two _'META-INF/services/io.micronaut.inject.BeanDefinitionReference'_ files.
When the module is used, the run-time logic can't always find the beans from the Java tree.

This usually only affects the contents of the .jar file that your module is distributed as.

This means you should never define beans in the Java source tree if you use Groovy for other
beans. 


==== Sessions Lost Randomly

If you experience logon sessions being lost randomly, then you may have a problem with
your cookie definition.  By default, then path defined for the security session cookie
is the path of the page being displayed.  This means you get a cookie for each page.

NOTE: This does not seem to be a problem for JWT Cookie security that is used by the framework.

When you logout and come back in or browse to other pages, you get multiple cookies.
This confuses the authentication logic and it thinks the page needs authentication
again.  This means you will get logon pages after you have logged on.

To avoid this, make sure your _application.yml_ sets the cookiePath:


[source,yml]
.application.yml - Avoid Session Loss.
----
micronaut:
  application:
    name: eframe
  session:
    http:
      cookiePath: /
----

==== @Transactional Used in Wrong Class

<<Micronaut>> provides support the normal _javax.transaction.Transactional_ annotation.
This works great in bean classes that are processed by Micronaut (e.g. _@Singleton,
@Repository or @Replaces_).  If _@Transactional_ is used in other places then nothing is
added to the method.

To work around this, you can use the withTransaction closure on a domain (see <<Transactions>>).

==== Key (xyz)=(xyz) is still referenced from table "abc".

This is a 'chicken or egg' scenario in some tests that triggers the 'still referenced' errors.
See <<Multiple Record References>> for details.

[source,text]
.Example - Error with Reference Error from Database
----
io.micronaut.data.exceptions.DataAccessException: Error executing SQL UPDATE: ERROR: update or
  delete on table "product" violates foreign key constraint "product_component_component_id_fkey"
  on table "product_component"
    Detail: Key (uuid)=(2e9aecd6-ab7b-4b7b-8281-dd9dec9eae84) is still referenced from table
    "product_component".

----



==== HTTP Requests return Forbidden Status

With the Micronaut security, if a request's URI is not valid for any reason, then the server will
typically return the HTTP _Forbidden_ status.  This happens, even  if the user has permissions for the
URI.

If this happens in a unit test in your IDE, then try rebuilding the the project and re-running the test.

==== Traits and AST

Early attempts to use the really nice Groovy traits instead of base classes failed.   It seems
Groovy does not guarantee the Annotations such as _@Secured_ will work with traits.  This means
we had to place common CRUD/Rest methods in the controller base classes such as
<<BaseCrudController>>.

The symptoms of this problem was inconsistent evaluation of the @_Secured_ annotation in other modules
that resulted in the annoying FORBIDDEN HTTP response.  This seemed to be worse when used in modules that
depended on the framework (e.g. <<{mes-core-path}/guide.adoc#,MES-Core Module>>).
See
http://docs.groovy-lang.org/next/html/documentation/core-traits.html#_compatibility_with_ast_transformations[Groovy Documents]
for details.


==== Geb/Selenium/Webdriver and moveToElement Issues/Messages

Under Firefox (and maybe others), the `moveToElement()` method moves relative to the element's
center. This is noted in an INFO message logged to stdError, but we suppress this in
the default GebConfig.groovy file:

  Logger.getLogger("org.openqa.selenium").setLevel(Level.WARNING)

You can change the logging level as needed.

There may also be other info messages from Selenium/Geb world that are suppressed.

==== Beans not defined for GEB/Spock Tests

When running a GEB/GUI test, the test spec starts an embedded server.  Sometimes, the micronaut
run-time doesn't see the controllers and other beans in your application.  If this happens, make
sure your _build.gradle_ has this dependency:

   compileOnly "io.micronaut:micronaut-inject-groovy"

This is in addition to the standard testCompile entry.  You need both.

One other symptom is in GEB tests, the page is not found. 

==== Dates with Groovy MONTH Syntax

Groovy has a nice array-based syntax for dates such as:

[source,groovy]
.Groovy MONTH Syntax
----
d[YEAR] = 2010
d[MONTH] = NOVEMBER
d[DATE] = 14
----

This is simple and easy to use, but the month values is zero-based (January=0) and the dates are 1-based.  This
inconsistency causes problems.  There are also issues with round trip access to the values that causes troubles.
For example, the code below fails unpredictably:

[source,groovy]
.Groovy MONTH Syntax - Fails
----
import static java.util.Calendar.*

def d = new Date()
d[YEAR] = 2010
d[MONTH] = NOVEMBER
d[DATE] = 14
d[HOUR_OF_DAY] = 13
d[MINUTE] = 24
d[SECOND] = 56
d[MILLISECOND] = 987

assert d[MONTH] == NOVEMBER
----

The failure of this code is dependent on the date that the test is run.  For this reason, we have chosen to avoid this
convenient approach to dates.

==== Constructors with more than One Optional Argument

Groovy provide a nice way to define optional arguments.  This is great, but the automatic class reloading
does not seem to work properly when 2 or more arguments are optional on constructors.  Groovy fails to call the
constructor on class recompilation. Also, 2 optional arguments are a
little confusing, so we avoid that scenario.  Traditional Java method overloading is used in those cases.

[source,groovy]
.Multiple Optional Arguments
----
GridWidget(Class domainClass, Collection list, Map options=null, List<String> columns=null) {
----

To solve this, we moved the `columns` list to the `options` map to eliminate the `columns` argument.


==== GStringTemplateEngine is Slow

When you need to evaluate a Groovy String with specific parameters, the standard way is to use the GStringTemplateEngine.
This is needed when you build the Groovy String from other elements or the user can provide their own string format.

[source,groovy]
.Slow GString Use
----
def parameters = [day: 'Monday', object: ...]
def engine = new groovy.text.GStringTemplateEngine()
def value = engine.createTemplate('${day}').make(parameters).toString()
----

This works and handles almost all cases, but it can be quite slow.  20-30 milliseconds per execution.  Even caching the
`engine` above does not help much.

To solve this, the enterprise framework provides a convenience method (`evaluateGString`) in
link:groovydoc/org/simplemes/eframe/misc/TextUtils.html[TextUtils^] to speed up the execution when possible:

[source,groovy]
.Fast GString Use
----
def parameters = [day: 'Monday', object: ...]
def value = TextUtils.evaluateGString('${day}',parameters)
----

This supports the normal Groovy String syntax such as _"${day} $day ${object.method()}"_.  If the method call format is used,
then the `evaluateGString()` method will use the slower GStringTemplateEngine approach if needed.

NOTE: Use the simple format such as _"$day"_ for speed.


==== @Canonical and @TupleConstructor Issues

We try to avoid these two.  The tuple constructor will create a constructor that frequently overlays the default value
for fields.  For example:

[source,groovy]
.@Canonical Issue
----
@Canonical
class Preference {
  String element
  String name=''
  List details = []
}

def preference = new Preference('ABC')
----

This will create an instance that has _null_ as the name and details element. The framework will avoid this tuple
constructor in most cases.


==== Map.class vs. Map.getClass()

This is a well-known quirk of Groovy.  In general, Groovy allows you to use the shorter _variable.class_ to get the
Class of the variable.  This works for most types of variables, but not for Maps.

When you have a map variable, the map.class returns the entry 'class' from the map.  This means you need to use
 _variable.getClass()_ instead.


==== Stub Compiler issues with .java

*Symptom:*

C:\Users\mph\.IntelliJIdea2016.1\system\compile-server\eframe_3d005332\groovyStubs\eframe_main\java-production\org\simplemes\eframe\custom\SomeClass.java
Error:(10, 8) java: java.lang.Comparable cannot be inherited with different arguments: <> and
<org.simplemes.eframe.custom.SomeClass>

This happens when compiling the Java stubs.  It happens when a true Java class calls
some Groovy code.

*Solution*

Move the Java source files to the Groovy directory.  The groovy compiler can handle them correctly.

*Alternate Solution*

Don't call Groovy code from Java in application code.


==== StackOverflowException and _StackOverflowError_

*Symptom:*

A stack overflow exception is thrown in unit tests and production when validating a
top-level object with a parent reference.  You can also get a _StackOverflowError_ in a unit test
when toString() is used by debugging or other testing mechanisms (e.g. Spock or IDE-based testing).

This can happen under these conditions:

* Both child and parent have `hashCode()` or `toString()` methods.  This can be the _@EqualsAndHashCode_ annotation or a normal method.
* The child uses the parent reference as part of its hash code.
* The parent uses the child reference as part of its hash code.

This can happen if you use the simple _@EqualsAndHashCode_ or _@ToString_:

[source,groovy]
----
@EqualsAndHashCode
@ToString
class Parent {
  String code
  @OneToMany(mappedBy = "parent")
  List<Child> children
  . . .
}


@EqualsAndHashCode
@ToString
class Child {
  @ManyToOne
  Parent parent
  . . .
}

----

This triggers a stack overflow in creating the hash codes since one level references the other.
The default behavior of the _@EqualsAndHashCode_ is to include *all* fields in the hash code calculation.
This causes the recursion and the stack overflow.


The solution is to make sure the parent hash code does not depend on the child's hash code:

[source,groovy]
----

@EqualsAndHashCode(includes=['code'])
@ToString
class Parent {
  String code
  @OneToMany(mappedBy = "parent")
  List<Child> children
  . . .
}

@EqualsAndHashCode(includes=['parent'])  // <1>
@ToString(excludes = ['parent'])
class Child {
  @ManyToOne
  Parent parent
  . . .
}

. . .

----
<1> This needed to make sure no other fields get pulled into the hash code.

NOTE: This can also happen with _@ToString()_.  You may need to add the option _excludes = ['order']_
      to the _@ToString()_ annotation.

==== Cannot set property 'Q' of undefined

When this happens deep in the <<GUI Toolkit>> library, it usually means a syntax error in the Javascript object passed to the toolkit constructor.

[source,javascript]
.Example - Undefined message from Toolkit
----
_B.display = {
  view: 'form', type: 'clean', margin: 0,
  rows: [
    {height: 10},
    ,                   // <.>
    { margin: 8,
      cols: [
        {view: "label", id: "rmaLabel", label: "rma.label", width: tk.pw(ef.getPageOption('labelWidth','20%')) , align: "right"},
        {view: "text", id: "rma", name: "rma", value: "RMA1001"  ,inputWidth: tk.pw("22em"),attributes: {maxlength: 40} }
      ]
    }
  ]
};
----

<.> This extra comma causes problems with the parsing of the object and the toolkit attempts to use an undefined GUI element.
Remove this extra comma to solve the problem.


==== NoSuchMethodException on Repository - Method Really Exists

If you use primitive method arguments (e.g. boolean instead of Boolean), you will probably get
a NoSuchMethodException like this:

  NoSuchMethodException: sample.DashboardConfigRepository$Intercepted.findByCategoryAndDefaultConfig(java.lang.String, java.lang.Boolean)

This happens when you use a primitive type (boolean) as an argument in the repository interface.
If you try to use the domain convenience method (`DashboardConfig.findByCategoryAndDefaultConfig()`),
you will get the exception.  For example:

[source,groovy]
.Example - Primitive Types in Repository Methods
----
interface DashboardConfigRepository extends BaseRepository, CrudRepository<DashboardConfig, UUID> {
  Optional<DashboardConfig> findByCategoryAndDefaultConfig(String category, boolean defaultConfig) // <.>
}

----
<.> A primitive is used.

To fix this, use the object (Boolean) instead of the primitive (boolean).

This is caused by logic in the enterprise framework that delegates static method calls on the domain
to the repository.  If you use the repository method directly, then this is not a problem.

==== Forbidden (403) Response from Controller

When you make an HTTP request to the controller, it returns 403 (Forbidden).  This can
be caused by many reasons:

* No _@Secure_ annotation.
* User does not have the require Role specific in the _@Secured_ annotation.
* Method is not correct (Get vs. Post).
* The controller is not deployed as a bean (e.g. no _@Singleton_ annotation or
  wrong import.  Always use: '_import javax.inject.Singleton_' ).

You can turn on TRACE logging for _io.micronaut.http_ or _io.micronaut.routing_ to help
debug this.  You can also turn on TRACE for _io.micronaut_.


==== Nashorn

Some tests will use the built-in Javascript engine to validate the generated Javascript.
This results in this warning message every time it is used:

----
Warning: Nashorn engine is planned to be removed from a future JDK release
----

To avoid this warning, run your tests with this option:

----
-Dnashorn.args="--no-deprecation-warning"
----
