
[[services-introduction]]
=== Introduction

SimpleMES provides much of the business logic using `services`.  These services use the domain
objects to affect the persistent state of objects.  Most of the complex MES business logic is handled
in the services.

==== Domain Objects and Services

Domain objects are used to store/retrieve properties of the SimpleMES objects.  The domain objects
are responsible for persistence and ensuring data integrity. This includes basic validations, but
does not include cross-object validation except in the cases of child objects.

Services orchestrate various domain objects and other services to provide higher level services.
In general, you should not directly use the domain objects in place of the appropriate service.
For example, if you wish to start a quantity on an order,  you should not use the Order object to
adjust the quantity directly.  You should use the  <<WorkService>> to perform the start work action.
This ensures proper logging, security and validation with all of the appropriate objects.

You can use domain objects directly in a few cases.  In most cases, reading values is acceptable.  Some direct updates
make sense, but do not use direct updates to avoid the business logic in the services.  Some domain methods are exposed
in the service layer. We recommend that you use the service layer method when possible.


==== Service Input Arguments

Most services take one or more POGOs (Plain of Groovy Objects) as input arguments.  These POGOs are simple containers
that hold values used by the service.  A good example is the `start()` method:

[source,groovy]
.Example Service Argument
----
  class StartRequest {
    Order order
    WorkCenter workCenter
    BigDecimal qty
    . . .
  }
----

This `StartRequest` POGO provides the fields needed to perform the start.  Some fields are simple values (e.g. qty) and
others are domain objects themselves. You will use Groovy/GORM features to populate these values.

NOTE: If the POGO contains domain objects, then you will need to make sure you pass them from inside of
      a transaction.  Even if the service method is marked as _@Transactional_, you need to make sure
      the transaction/session is the same for the service method as the code that read the domain object.

==== Example

A short example to start work on an order is shown below:

[source,groovy]
.Example Service Use
----
@Singleton
@Transactional
class AnotherService {

  @Inject
  def workService      // <1>

  StartRequest startRequest = new StartRequest()
  startRequest.order = Order.findByOrder('M0001')
  startRequest.qty = 1.0
  workService.start(startRequest)

  . . .

}
----
<1> Injected automatically by _@javax.inject.Inject_ at run time.

This example uses the <<WorkService>>, which is injected by Micronaut with the annotation.
This code then finds the order using its key value ('M0001') and sets the quantity to start to 1.0.
It then calls the service. The _WorkService_ in this case moves the quantity to in work and logs a
record to the <<ActionLog>>.

If the service fails, then it will throw an exception and the transaction will be rolled back.


==== Transactions

Services follow the normal framework transaction logic.  See <<Enterprise Framework>> for details.


=== Service Extension Points

Many other modules may need to extend core methods with module-specific logic.  We allow this
using the framework's
link:{eframe-path}/guide.html#extension-points[Extension Points^] icon:share-square-o[role="link-blue"]
feature.  The extension points this module supports include:

include::../../../../../../build/generated/extensions.adoc[]


