
== Controllers

The SimpleMES controllers are almost always thin wrappers around one or more <<Services>>.
The argument(s) sent to the service are usually single POGO's, sometimes with references to
domain objects.

See the link:groovydoc/index.html[API Groovydoc^] icon:share-square-o[role="link-blue"]
for details on the methods.  Most are not documented in detail in the User Guide or Reference Guide.


=== Arguments for GET Requests

Most HTTP GET requests use the arguments from the URL parameters.  These allow the client
to make simple request with 0 or more arguments.

=== Arguments for POST/PUT Requests

The body of the HTTP POST/PUT request are converted to these argument POGO's and
are passed to the service method.  This means all body's must conform to the normal
link:{eframe-path}/guide.html#json[JSON formatting rules^] icon:share-square[role="link-blue"]
for the framework.

=== Transactions

Most transactions are initiated by the controller layer.  This is needed since most service methods
work on domain objects.  To properly populate the domain object references, the controller
needs a transaction created for the request.  It is also used to process the response into
JSON in many cases.





