
=== Initial Data Load

ifeval::["{backend}" != "pdf"]

[inline-toc]#<<Domain Method initialDataLoad>>#
[inline-toc]#<<initialDataLoadBefore and initialDataLoadAfter>>#
[inline-toc]#<<Loading from Non-Domains>>#
[inline-toc]#<<Initial Data Loading and Tests>>#

endif::[]




Initial data loading is one of the common setup needs for large applications.  These applications usually have
a number of status codes or numbering sequences that need some sort of initial values.  If you don't have some
reasonable defaults, then your first-time customers may spend hours trying to configure your product.  This will
discourage most normal customers.

==== Domain Method initialDataLoad

To trigger the initial data load on startup, you will need to add a method to your domain class.
This method will be executed on application startup.  The method should check for the existence
of the record before attempting to create it.  You should also minimize the logic to reduce
startup time.  Don't add extensive or slow logic if you can avoid it.

An example is shown below:

[source,groovy]
.Example Initial Data Load
----
static initialDataRecords = ['User': ['admin']]

static Map<String,List<String>> initialDataLoad() {
  if (!findByUserName('admin')) {  // <.>
    def adminUser = new User(userName: 'admin', password: '****', title: 'Admin User').save()
    log.debug('Created initial admin user {}', adminUser)
  }

  return initialDataRecords  // <.>
}
----
<.> Create the admin user, only if it does not exist already.
<.> Always return the records that are provided by the initial data load process, even if
    they already exist.  These values returned will be ignored when checking for
    <<Test Data Pollution>>.  See <<Initial Data Loading and Tests>> for more details.


Keep this `initialDataLoad()` method simple.  Any errors could affect startup, which will frustrate your users.
If you want to avoid this problem, then you can write code to handle exceptions and allow the startup.  In most
cases, this would not be wise. Your application may not run properly without these records.

NOTE: Most applications will allow the users to modify the defaults using normal GUIs or APIs.  It is important that your
`initialDataLoad()` method never alter existing records.  If the user deletes your records, then the record(s) will
probably be re-created on the next application startup.

If you need to load data for domains that are in a module (e.g. new User Roles for the module),
then you probably need to create a dummy initial data load domain class that is not persistent.
We suggest you use the class name _InitialData_. This would look something like this:

[source,groovy]
.Example InitialData Domain Class
----
class InitialData {

  static mapWith = "none" // <1>

  static Map<String,List<String>> initialDataLoad() {
    createRoles()  // <2>
    createDashboards()
    return ...
  }

  static createRoles() {
   . . .
  }
}
----
<1> Makes this domain a non-persistent domain class.
<2> We suggest you use one method for each type of domain loaded for clarity.

The `initialDataLoad()` method in this domain will be called just like normal domain classes.

This initial data loading works in most settings such as integration test, functional test and runtime.  It is not
executed automatically for unit tests, but you can manually call the loader in your `setUp()` method of your unit tests:

[source,groovy]
----
void setUp() {
  // Load the default status codes.
  StatusCode.initialDataLoad()
}
----

==== initialDataLoadBefore and initialDataLoadAfter

The order these initial data records are loaded is sometimes important.  Validation of references to
other records can fail if the records are loaded in the wrong order.  To solve simple precedence
problems, we support simple 'load after' and 'load before' features.

These 'load after' and 'load before' are defined in the domain that needs the precedence.
These are lists that define which other domains should be loaded before or after the domain.
The list can contain full class names (including packages) or the Class object itself.

Below are two examples of their use:


[source,groovy]
.Example - initialDataLoadAfter
----
@Entity
class User {
  static initialDataLoadAfter = [Role]  // <.>
  . . .
}
----
<.> The _User_ domain's initial data should be loaded after the _Role_ domain.


[source,groovy]
.Example - initialDataLoadBefore
----
static initialDataLoadBefore = ['org.simplemes.eframe.security.domain.User']
----

[source,groovy]
.Example - initialDataLoadBefore
----
@Entity
class Role {
  static initialDataLoadBefore = [User]  // <.>
  . . .
}
----
<.> The _Role_ domain's initial data should be loaded before the _User_ domain.


NOTE: If the 'before' and 'after' lists are both specified in one domain, then the before takes
      precedence. You should use only one for clarity.

==== Loading from Non-Domains

Sometimes, a module will need to add records to a core module's database.  This is common with
user <<Roles>>.  To avoid creating dummy domain classes for this, we suggest you use
a feature for <<Addition>>.  See <<Initial Data Loaders and Additions>> for details.

==== Initial Data Loading and Tests

Functional tests that use the embedded test server will use an in-memory database.
This database is active for the entire test suite, so each test needs to clean up it test
data as described in <<Test Data Pollution>>.

The problem is with the data loaded by initial data loaders.  This data should be left alone
since later tests may need it.

For example, a module adds some roles to the database for its security checks.  We don't
want those records to be considered <<Test Data Pollution>>.  This would cause every test
to fail.  We want those records left in the database after every test.

To avoid this, your initial data load method should return a list of values that will be ignored
by the test data pollution check.


[source,groovy]
.Example Initial Data Load - Test Data Pollution
----
static initialDataRecords = ['User': ['admin']] // <.>

static Map<String,List<String>> initialDataLoad() {
  if (!findByUserName('admin')) {  // <.>
    def adminUser = new User(userName: 'admin', password: '****', title: 'Admin User').save()
    log.debug('Created initial admin user {}', adminUser)
  }

  return initialDataRecords  // <.>
}
----
<.> The static list of records created for the 'User' object. The strings here (e.g. 'admin')
    will be the record's `TypeUtils.toShortString(record)`.  This should be safe for most
    scenarios used in tests.  The Map key is the domain class's `simpleName` (e.g. 'User' above).
<.> Create the admin user, only if it does not exist already.
<.> Always return the records that are provided by the initial data load process, even if
    they already exist.  These values returned will be ignored when checking for
    <<Test Data Pollution>>.

This example will create a record for the admin user.  The returned map is used
by link:groovydoc/org/simplemes/eframe/test/BaseSpecification.html[BaseSpecification^]
icon:share-square-o[role="link-blue"] to know which records to ignore for each domain
class.


