==== efTitle

The link:reference.html#eftitle[efTitle^] icon:share-square-o[role="link-blue"]
marker is used to display a standardized title for a given page.  This is common in almost
all pages, so a central way to define it is provided.  You can use your own titles as you see fit,
but this can help reduce the boiler-plate code in your application.
Also, the prevalent use of tabs in most browsers means
title display space is limited.  Titles should place the most important information first
in the title.

For example, the title for a show page for a single order should be something like:

[source,groovy]
.Example Title
----
M1004536 Order - Application Name
----

This places the most important part of the title (the order name 'M1004536') at the beginning of the title.  In a crowded
tabbed panel, this will allow the user to find the tab with the order 'M1004536' quickly.

This example creates a standard 'show' page title.

[source,html]
.Show Page Title
----
<#assign title><@efTitle type='show'/></#assign>  // <.>

<#include "../includes/header.ftl" />
<#include "../includes/definition.ftl" />

<@efForm id="show">
    <@efShow columns='product,title'/>
</@efForm>

----
<.> Fills in the text used by the `views/includes/header.ftl` file for the title.
    The title is based on the record being show (product in the page's model) and
    the basic _show_ type.
