
=== Roles

The roles created automatically by the framework form the basis for your application's roles.
These roles are the ones used by the framework setup and administration pages and are required
for most actions.   If these roles are deleted from the database, then they will be re-created
on the next startup.

The roles provided by the framework are:

* <<ADMIN>> - General Administration actions.
* <<CUSTOMIZER>> -Views/Updates non-GUI customization features.
* <<DESIGNER>> - Views/Updates framework display features (e.g. List columns, Custom Definition features, etc).
* <<MANAGER>> - Views/Updates most framework manager features (User Definition).

NOTE: Each roles do not have built-in hierarchy.  For example, the ADMIN role does not automatically
      give MANAGER roles.   See the 


Some of the pages available to each role is shown below (not an full list):

==== (No Role or Anonymous)

* Login Pages.
* Overall System Status Pages.
* Assets (images, javascript, etc).


==== ADMIN

* Clear Statistics action on Overall System Status Pages.

==== MANAGER

Users with this role manage day-to-day operations of the system.

* User Definition (Create new User, reset password, assign role (permission),  etc)


==== CUSTOMIZER

Users with this role create non-GUI extensions to the system.  These include new fields and
logic that can have far-reaching impact on performance, behavior and data integrity.

* Field Extension Definition
* Flex Type creations

==== DESIGNER

Users with this role can make GUI-level changes to the system.  This generally has a smaller
impact on the system, but still has the potential to impact large number of users but not as
big an impact on data integrity.

* Configure Default list layout
* Configure Custom GUI features (e.g. dashboards, definition GUIs, etc).
* Define named list definitions for other users


==== Combines Role Lists

Frequently, you will want to specify a controller is accessible for multiple roles.  For
example, you might want to allow ADMIN and MANAGER roles.  To make this simpler, some
combine role arrays are defined in the
link:groovydoc/org/simplemes/eframe/security/Roles.html[Roles^] icon:share-square-o[role="link-blue"]
class:

[source,groovy]
.Example ADMIN and MANAGER roles
----
@Secured(Roles.MANAGER_AND_MANAGER)
@Controller("/somePath")
class SomeController extends BaseCrudRestController {

  . . .

}
----








