
=== Security Setup

Setting up security is not too tedious.  By default, a single user _admin_ is created with all
roles available.   The password defaults to _admin_ and must be changed on the first login.

This _admin_ user can be deleted, but should only be deleted after another user record is created.
This user will be created on startup if there are no users in the database.
You should make sure there is at least one user with the _ADMIN_ role in the system.

==== application.yml

Your application's _application.yml_ needs a few entries for security to work as expected:

[source,yaml]
----
  security:
    enabled: true
    endpoints:
      login:
        enabled: true
      logout:
        enabled: true
    session:
      enabled: true
      login-success-target-url: /
      login-failure-target-url: /login/authFailed
    token:
      jwt:
        enabled: true
        bearer:
          enabled: false
        cookie:
          enabled: true
          loginFailureTargetUrl: /login/authFailed
        signatures:
          secret:
            generator:
              secret: someSecretStuffToBeHiddenpleaseChangeThisSecretForANewOne    // <1>
        generator:
          access-token-expiration: 1800  # 30 minutes
    interceptUrlMap:
      - pattern: /assets/**
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /favicon.ico
        httpMethod: GET
        access:
          - isAnonymous()

----
<1> This will be stored in *TBD*.

This configures JWT Security to force all controller requests to be authenticated.
It also allows access to some pages/assets without a login.
(See Roles below for details).

==== Controllers

By default all controller methods must be secured.  This means adding the _@Secured_
annotation to your controllers:

[source,groovy]
----
import org.springframework.security.access.annotation.Secured

@Secured('ADMIN')  // <1>
@Transactional
class MonitorController {

  def index() {
    . . .
  }
}
----
<1> User must have ADMIN role for access to all pages (methods) under this controller.

The role chosen can be any of the defined roles.  Individual methods can be secured too.

