
=== Security Setup

Setting up security is not too tedious.  By default, a single user _admin_ is created with all
roles available.   The password defaults to _admin_ and must be changed on the first login.

This _admin_ user can be deleted, but should only be deleted after another user record is created.
This user will be created on startup if there are no users in the database.
You should make sure there is at least one user with the _ADMIN_ role in the system.

==== application.yml

Your application's _application.yml_ needs a few entries for security to work as expected:

[source,yaml]
----
micronaut:
  application:
    name: ???
  session:
    http:
      cookiePath: /
  security:
    authentication: cookie
    enabled: true
    endpoints:
      login:
        enabled: true
      logout:
        enabled: true
    reject-not-found: false
    redirect:
      forbidden:
        enabled: true
        url: /login/auth
      prior-to-login: true
      unauthorized:
        enabled: true
        url: /login/auth
    token:
      jwt:
        enabled: true
        bearer:
          enabled: false
        cookie:
          enabled: true
          loginFailureTargetUrl: /login/auth?failed=true
        signatures:
          secret:
            generator:
              secret: ${eframe_key}    <.>
        generator:
          access-token-expiration: 1800  # 30 minutes  <.>
    interceptUrlMap:
      - pattern: /assets/**
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /favicon.ico
        httpMethod: GET
        access:
          - isAnonymous()
  server.netty.logLevel: DEBUG
  server.thread-selection: AUTO

---
eframe:
  security:
    jwtRefreshMaxAge: 1209600  <.>

----
<.> This value comes from the environment variable 'eframe_key'.  The JWT encryption
    provider requires a 256 bit or longer key (32+ characters).
    See https://docs.micronaut.io/latest/guide/index.html#_included_propertysource_loaders[Micronaut Configuration]
    for more details.
<.> The access token timeout.  Suggest value between 15-30 minutes.  Too small, and the
    token refresh mechanism will be invoked too often.  Too large and the
    JWT token will be valid for too long.  This means disabling a user account will not
    take effect until the JWT token has expired.  See <<Security Design>> for details
    on these trade-offs.
<.> The expiration time for the refresh token (seconds).  Defaults to 30 days (2592000 seconds).


This configures JWT Security to force all controller requests to be authenticated.
It also allows access to some pages/assets without a login.
(See Roles below for details).

==== Security Setup for Controllers

By default all controller methods must be secured.  See <<Controller Security>> for details.
