
=== Security Setup

Setting up security is not too tedious.  By default, a single user _admin_ is created with all
roles available.   The password defaults to _admin_ and must be changed on the first login.

This _admin_ user can be deleted, but should only be deleted after another user record is created.
This user will be created on startup if there are no users in the database.
You should make sure there is at least one user with the _ADMIN_ role in the system.

==== application.yml

Your application's _application.yml_ needs a few entries for security to work as expected:

[source,yaml]
----
micronaut:
  application:
    name: ???
  session:
    http:
      cookiePath: /
  security:
    authentication: cookie
    enabled: true
    endpoints:
      login:
        enabled: true
      logout:
        enabled: true
    reject-not-found: false
    redirect:
      forbidden:
        enabled: true
        url: /login/auth
      prior-to-login: true
      unauthorized:
        enabled: true
        url: /login/auth
    token:
      jwt:
        enabled: true
        bearer:
          enabled: false
        cookie:
          enabled: true
          loginFailureTargetUrl: /login/auth?failed=true
        signatures:
          secret:
            generator:
              secret: ${eframe_key}    // <.>
        generator:
          access-token-expiration: 1800  # 30 minutes
    interceptUrlMap:
      - pattern: /assets/**
        httpMethod: GET
        access:
          - isAnonymous()
      - pattern: /favicon.ico
        httpMethod: GET
        access:
          - isAnonymous()
  server.netty.logLevel: DEBUG
  server.thread-selection: AUTO

----
<.> This value comes from the environment variable 'eframe_key'.  The JWT encryption
    provider requires a 256 bit or longer key (32+ characters).
    See https://docs.micronaut.io/latest/guide/index.html#_included_propertysource_loaders[Micronaut Configuration]
    for more details.

This configures JWT Security to force all controller requests to be authenticated.
It also allows access to some pages/assets without a login.
(See Roles below for details).

==== Security Setup for Controllers

By default all controller methods must be secured.  See <<Controller Security>> for details.
