
=== Security Design

This enterprise framework needs to support a few key configurable scenarios:

. User browser session timeout of short duration (e.g 30 minutes or less).
. Longer user browser session timeout (14+ days).
. JWT support for security on the <<API>> calls.

To support all of these cases, we chose to use JWT (Json Web Tokens) via browser cookies.
This allows a short JWT lifetime, with a long (configurable) automatic refresh mechanism for
browser-based clients.

One other important point:  Most requests should be authenticated with a stateless
mechanism.  This means the JWT is used to authenticate most requests since 
it does not use the DB or a session state to authenticate the request.  Instead, it
simply checks for validity.

Once the JWT expires (e.g. after 15 minutes), the token refresh is triggered that
checks for a valid refresh token (in the DB) from the original login.  It also checks the
User record in the DB for the user's status.

==== Token Timeouts

With this approach, the timeouts for the JWT and JWT_REFRESH_TOKEN are important.
If the values are too small or too large, then performance may suffer or your exposure
to security lapses may be too large.

See <<Security Setup>> for details on setting these timeouts.


==== Refresh Token Flow

NOTE: This section assumes the access token timeout is set to the default 15 minutes and
      the refresh token timeout is set to the default 24 hours.  These numbers will
      used below without noting that they are the configurable values.
      See <<Security Setup>> for example settings.

The basic refresh flow is:

* Successful login sends access token (_JWT_) and refresh token (_JWT_REFRESH_TOKEN_)
  cookies (15min and 24 hours).
* All requests are checked for expired JWT.  If the JWT is expired, then the
  auto refresh of the token is attempted. The response will include the new JWT.
* If any of these refreshes fail, then the user will be forced to login at the next
  user request to the sever (e.g. on the nest page load or save).


The browser client-side logic requires no changes.  The normal browser cookie
handling logic should cover mode cases.

Any non-browser clients can request a refresh using a process similar to
<<oauth-refresh>> mechanism.


==== Refresh Token Details

Internally, the logic is a little more complex.  There are two Micronaut beans involved
in this:

* link:groovydoc/org/simplemes/eframe/security/AutoRefreshAuthenticationFetcher.html[AutoRefreshAuthenticationFetcher^] icon:share-square-o[role="link-blue"]
 This detects the expired JWT and triggers
  an auto token refresh for the request.  This class stores the new cookies in
  a request attribute for use by the other object.

* link:groovydoc/org/simplemes/eframe/security/AutoRefreshTokenFilter.html[AutoRefreshTokenFilter^] icon:share-square-o[role="link-blue"]
 This gets the cookies from the request and puts them
  in the response.

These two beans, along with the
link:groovydoc/org/simplemes/eframe/security/service/RefreshTokenService.html[RefreshTokenService^] icon:share-square-o[role="link-blue"]
will only allow the refresh token to be used a limited number of times.
If used too many times, then the
existing refresh tokens for the user will be disabled and force a new login.



[[oauth-refresh]]
==== OAuth /oauth/access_token Endpoint Use

This endpoint is intentionally broken.  The replacement _/login/access_token_
provides a limited-use replacement refresh token cookie when used.  The
_RefreshTokenService.getUserDetails()_ RefreshTokenPersistence implementation
intentionally prevents use of the tokens via the OAuth _/oauth/access_token_ endpoint.


