
=== WorkCenterComponent

A Work Center Component defines a single component loaded onto the given work center.
This domain is also used to track long-term component usage history on the work center.

See <<guide.adoc#work-center-component-guide,Work Center Component>> for an overview.

==== Fields

The important fields defined for this object include:


[cols="1,4",width=75%]
|=== 
|Field | Description

| `workCenter`| This is the work center this component was loaded onto.(*required*)
| `sequence`| The sequence this component should be displayed in.  Duplicates allowed.
| `location` | The location name. Any string value is legal since a user may enter this
               during work center setup. (*Default:* '@')
| `component` | This is the <<guide.adoc#product,Product>> for the component. (*Required*)
| `assemblyData` | The <<{eframe-path}/guide.adoc#flexible-fields,Flexible Field>> used to define
               the assembly data for this component.
               The actual data is stored in a field `assemblyDataValues` in XML format.
| `qty` | The number of pieces loaded.  This is currently used for reference (*Optional*).
|
|=== 

