
[[scan-assy-service]]
=== ScanAssyService

The link:guide.html#scan-assy-service[Scan Assy Service^] icon:share-square-o[role="link-blue"]
supports scanning of assembly information in the link:{mes-core-path}/guide.html#scan-dashboard[Scan Dashboard^]
icon:share-square-o[role="link-blue"].
This service adds extensions to the core `ScanService.scan()` method to identify component barcodes
as scanned by the operator.  These scans will provide almost all of the information needed to assemble components.

The groovy doc is link:groovydoc/org/simplemes/mes/assy/system/ScanAssyService.html[ScanAssyService^]
icon:share-square-o[role="link-blue"].

==== Method Extensions

Some core methods of the ScanService are extended to support the new features.  These include:

* `postScan()` - Basic scan logic.  Handles component scans.
* `postGetBarcodePrefixMapping()` - Defines the <<Barcode Prefixes>> supported.  Adds Product, Vendor, Lot and Serial.

For more details on general barcode formats, see
link:{mes-core-path}/guide.html#barcode-formats[Barcode Formats^] icon:share-square-o[role="link-blue"].

NOTE: Do not call these extension methods directly.


==== Barcode Prefixes

Some barcodes can include multiple values such as the Product and Lot code.    Using the internal (simple)
format, this barcode might look like this:

  ^PRD^WHEEL-27^LOT^20171101-18

This module adds several types of barcode prefixes to the standard scan capability.
The new barcode prefixes added for assembly include:

[cols="1,1,4", width=75%]
|===
|Prefix | Meaning    | Description
| `PRD` | `PRODUCT`  | A product or component.
| `VND` | `VENDOR`   | The vendor that provides a component.
| `LOT` | `LOT`      | The component lot code used.
| `SN`  | `SERIAL`   | The serial number for the component.
|===


